db:
  connect: 'postgres://postgres:password@localhost:5432/example'
cors:
  allowedOrigins:
    - 'http://localhost:*'
    - 'https://stillbox.server'
auth:
  jwtsecret: 'super secret string'
  # this is the JWT cookie domain
  domain: example.com
  # this allows the JWT cookie to be served over plain HTTP only for these Host: header values
  allowInsecureFor:
    "localhost": true
listen: ':3050'
public: true
log:
  # level logs at or above the specified level
  # levels are trace, debug, info, warn, error, fatal, panic
  # an entry without a file: property indicates stderr
  - level: debug
  - level: error
    file: error.log
rateLimit:
  enable: true
  requests: 200
  over: 2m
