db:
  connect: 'postgres://postgres:password@localhost:5432/example'
cors:
  allowedOrigins:
    - 'http://localhost:*'
    - 'https://stillbox.server'
auth:
  jwtsecret: 'super secret string'
  # this is the JWT cookie domain
  domain: example.com
  # this allows the JWT cookie to be served over plain HTTP only for these Host: header values
  allowInsecureFor:
    "localhost": true
listen: ':3050'
public: true
log:
  # level logs at or above the specified level
  # levels are trace, debug, info, warn, error, fatal, panic
  # an entry without a file: property indicates stderr
  - level: debug
  - level: error
    file: error.log
rateLimit:
  enable: true
  requests: 200
  over: 2m
alerting:
  enable: true
  lookbackDays: 7
  halfLife: 30m
  recent: 2h
  alertThreshold: 0.3
  renotify: 30m
notify:
  - provider: slackwebhook
#   subjectTemplate: "Stillbox Alert ({{ highest . }})"
#   bodyTemplate: |
#     {{ range . -}}
#     {{ .TGName }}{{ if (and .Talkgroup .Talkgroup.AlphaTag) }} ({{ .Talkgroup.StringTag false -}}){{ end }} is active with a score of {{ f .Score.Score 4 }}! ({{ f .Score.RecentCount 0 }}/{{ .Score.Count }} recent calls)
#
#     {{ end -}}
    config:
      webhookURL: "http://somewhere"
# configure upstream relays here
relay:
    # `url` is the root of the instance
# - url: 'http://some.host:3051/'
#   apiKey: aaaabbbb-cccc-dddd-eeee-ffff11112222
    # `required` specifies whether we should report failure (i.e. HTTP 500 for rdio-http) to the source
    # if the relay call submission fails
#   required: false
