server:
  # this is used to compose URLs, for example in M3U responses.
  # set it to what users access the instance as.
  baseURL: "https://stillbox.example.com"
  listen: ':3050'
  public: true
  # set this to true only when using a reverse proxy that sets this header
  useXRealIP: false
  rateLimit:
    enable: true
    requests: 200
    over: 2m
  cors:
    allowedOrigins:
      - 'localhost:*'
      - 'stillbox.server'
  # if adminSocket is set/not null, it specifies a path where stillbox will
  # open a unix domain socket for local daemon control use
  adminSocket: /var/run/stillbox/stillbox.sock

db:
  connect: 'postgres://postgres:password@localhost:5432/example'
  partition:
    # whether to enable the built-in partition manager
    # note that when this is disabled, the calls table is still (by default) created as a partitioned table.
    # so, notwithstanding manual intervention or intermittent enabling,
    # disabling the partition manager means that no partitions exist to receive rows.
    enabled: true
    # the postgres schema containing our tables
    schema: public
    # daily|weekly|monthly|quarterly|yearly
    interval: monthly
    # number of partitions to retain, -1 to keep all
    retain: 3
    # whether to drop or simply detach
    drop: true
    # number of partitions to prepare ahead
    preProvision: 3

auth:
  jwtsecret: 'super secret string'
  # this is the JWT cookie domain
  domain: example.com
  # this allows the JWT cookie to be served over plain HTTP only for these Host: header values
  allowInsecureFor:
    "localhost": true
    "xenon": true
  # this instead changes the meaning of allowInsecureFor to the cookie being marked
  # Secure, but SameSite will be set to None
  sameSiteNoneForInsecure: false
  # only allow API key authenticated requests according to ACL
  # If this is totally unset, the default is deny
  apiKeyACL:
    allow:
      - 127.0.0.1
      - ::1
      - 192.168.3.4
      - 192.168.1.0/24
      - 2001:dead:beef::4/128
    deny:
      - 192.168.1.54
    # allow, deny means allow entries are evaluated first;
    # at least one must match, or the request is rejected. Next, all deny entries are evaluated.
    # If any match, the request is denied. Last, any requests which do not match an allow or a
    # deny entry are denied by default.
    # deny, allow means all deny entries are evaluated; if any match, the request is denied
    # unless it also matches an allow entry. Any requests which do not match any entries are permitted.
    # Use deny, allow with no list entries if you really want to allow any client to use API key auth.
    order: deny, allow

log:
  # level logs at or above the specifies level
  # levels are trace, debug, info, warn, error, fatal, panic
  # an entry without a file: property indicates stderr
  - level: debug
  - level: error
    file: error.log

alerting:
  enable: true
  lookbackDays: 7
  halfLife: 30m
  recent: 2h
  alertThreshold: 0.3
  renotify: 30m
  # if maxContext is >0, it specifies the number of transcripts to search for in alerts
  maxContext: 3
  # callLengthThreshold specifies the minimum call length to get transcripts for; default is 4 seconds
  callLengthThreshold: 4s
  # contextLookback specifies how far back to look for transcripts
  contextLookback: 20m

notify:
  - provider: slackwebhook
#   subjectTemplate: "Stillbox Alert ({{ highest . }})"
#   bodyTemplate: |
#     {{ range . -}}
#     {{ .TGName }}{{ if (and .Talkgroup .Talkgroup.AlphaTag) }} ({{ .Talkgroup.StringTag false -}}){{ end }} is active with a score of {{ f .Score.Score 4 }}! ({{ f .Score.RecentCount 0 }}/{{ .Score.Count }} recent calls)
#     {{- range .Context }}
#     {{ .Date | fmtTime "03:04:05" }} {{ .Transcript }}
#     {{- end }}
#
#     {{ end -}}
    config:
      webhookURL: "http://somewhere"

# configure upstream relays here
relay:
    # `url` is the root of the instance
# - url: 'http://some.host:3051/'
#   apiKey: aaaabbbb-cccc-dddd-eeee-ffff11112222
    # `required` specifies whether we should report failure (i.e. HTTP 500 for rdio-http) to the source
    # if the relay call submission fails
#   required: false

# callStorage backends have filters tested until one matches, then that one wins for storage of new calls
# null filter always matches
# ingest specifies whether to try to store audio in this backend
# if none are configured/evaluate during ingestion, calls are simply stored as blobs in the DB
callStorage:
  # name of the backend ends up being stored in the DB and
  # should not change once chosen, otherwise every record must be
  # updated.
  - name: s3
    backend: s3
    # if this backend fails:
    # next-then-fail (default) - try next backend (including filter), if no other backends store then fail ingest
    # next-then-db - try next backend (including filter) or ultimately the DB
    # fail - fail the ingest immediately
    # db - stop processing backends, store in DB
    onError: next-then-fail
    # ingest specifies whether this is not to be used to store new calls
    # but exists to serve requests for calls referencing this backend in the DB
    ingest: true
    # filter is same as below, or can be null or unspecified
#   filter:
#     talkgroups:
#       - "197:10101"
#     talkgroupTagsAny:
#       - fire dispatch
#       - law dispatch
    config:
      bucket: 'stillbox'
      # secure is whether to use https when accessing the endpoint.
      secure: false
      # endpoint is how stillbox will access the object server
      endpoint: 'garage:3900'
      region: 'garage'
      # if externalHost is set, this host will be used to generate presigned URLs
      # for call audio redirect to clients rather than endpoint above
      externalHost: 'garage.example.com'
      # if externalHost is set, externalSecure specifies whether to use https for presigned URLs
      externalSecure: true
      # timeout is the amount of time for S3 request deadline before next action (store in DB or fail)
      timeout: 10s
      keyID: 'GK7894947fffaacacd83664923'
      secretKey: 'bacba7892843792347987293874923847293487239487234987234bababababa'
  - name: fs
    backend: fs
    config:
      # root path to store call audio in, must be a directory
      root: "/tank/stillbox"

transcription:
# - type: http
#   atLeastSeconds: 2
#   filter:
#     talkgroups:
#       - "197:10101"
#     talkgroupTagsAny:
#       - fire dispatch
#       - law dispatch
#   config:
#     url: "http://transcriber:3053/"
#     callbackBase: "http://stillboxinternal:3050/"

metrics:
  # Enable prometheus metrics
  enabled: true
  # Metrics path, default /metrics
  path: /metrics
  # metrics endpoint basic auth. If either are empty or unset, auth is disabled.
  # username
  username: metrics
  # password
  password: changeme1234
  # ACL same as for API key ACL above
  acl:
    allow:
      - 127.0.0.1
      - ::1
      - 192.168.3.4
      - 192.168.1.0/24
      - 2001:dead:beef::4/128
    deny:
      - 192.168.1.54
