// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAlert = `-- name: AddAlert :exec
INSERT INTO alerts (time, tgid, system_id, weight, score, orig_score, notified, metadata, context_window, url_tag)
VALUES
(
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8,
	$9,
	$10
)
`

type AddAlertParams struct {
	Time          time.Time                        `db:"time" json:"time"`
	TGID          int                              `db:"tgid" json:"tgid"`
	SystemID      int                              `db:"system_id" json:"systemId"`
	Weight        *float32                         `db:"weight" json:"weight"`
	Score         *float32                         `db:"score" json:"score"`
	OrigScore     *float32                         `db:"orig_score" json:"origScore"`
	Notified      bool                             `db:"notified" json:"notified"`
	Metadata      []byte                           `db:"metadata" json:"metadata"`
	ContextWindow pgtype.Range[pgtype.Timestamptz] `db:"context_window" json:"contextWindow"`
	URLTag        *string                          `db:"url_tag" json:"urlTag"`
}

func (q *Queries) AddAlert(ctx context.Context, arg AddAlertParams) error {
	_, err := q.db.Exec(ctx, addAlert,
		arg.Time,
		arg.TGID,
		arg.SystemID,
		arg.Weight,
		arg.Score,
		arg.OrigScore,
		arg.Notified,
		arg.Metadata,
		arg.ContextWindow,
		arg.URLTag,
	)
	return err
}

const getAlertByURLTag = `-- name: GetAlertByURLTag :one
SELECT
	id,
	time,
	tgid,
	system_id,
	weight,
	score,
	orig_score,
	notified,
	metadata,
	context_window,
	url_tag
FROM alerts
WHERE url_tag = $1
`

func (q *Queries) GetAlertByURLTag(ctx context.Context, urlTag *string) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertByURLTag, urlTag)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Time,
		&i.TGID,
		&i.SystemID,
		&i.Weight,
		&i.Score,
		&i.OrigScore,
		&i.Notified,
		&i.Metadata,
		&i.ContextWindow,
		&i.URLTag,
	)
	return i, err
}

const pruneAlerts = `-- name: PruneAlerts :execrows
DELETE FROM alerts WHERE time < $1
`

func (q *Queries) PruneAlerts(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneAlerts, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
