// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calls.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCall = `-- name: AddCall :exec
INSERT INTO calls (
id,
submitter,
system,
talkgroup,
call_date,
audio_name,
audio_blob,
audio_type,
audio_ref,
duration,
frequency,
frequencies,
patches,
talker_alias,
tg_label,
tg_alpha_tag,
tg_group,
source
) VALUES (
$1,
$2,
$3,
$4,
$5,
$6,
$7,
$8,
$9,
$10,
$11,
$12,
$13,
$14,
$15,
$16,
$17,
$18
)
`

type AddCallParams struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	Submitter   *int32        `db:"submitter" json:"submitter"`
	System      int           `db:"system" json:"system"`
	Talkgroup   int           `db:"talkgroup" json:"talkgroup"`
	CallDate    time.Time     `db:"call_date" json:"callDate"`
	AudioName   *string       `db:"audio_name" json:"audioName"`
	AudioBlob   []byte        `db:"audio_blob" json:"audioBlob"`
	AudioType   NullAudioMIME `db:"audio_type" json:"audioType"`
	AudioRef    []byte        `db:"audio_ref" json:"audioRef"`
	Duration    *int32        `db:"duration" json:"duration"`
	Frequency   int           `db:"frequency" json:"frequency"`
	Frequencies []int         `db:"frequencies" json:"frequencies"`
	Patches     []int         `db:"patches" json:"patches"`
	TalkerAlias *string       `db:"talker_alias" json:"talkerAlias,omitempty"`
	TGLabel     *string       `db:"tg_label" json:"tgLabel"`
	TGAlphaTag  *string       `db:"tg_alpha_tag" json:"tgAlphaTag"`
	TGGroup     *string       `db:"tg_group" json:"tgGroup"`
	Source      int           `db:"source" json:"source"`
}

func (q *Queries) AddCall(ctx context.Context, arg AddCallParams) error {
	_, err := q.db.Exec(ctx, addCall,
		arg.ID,
		arg.Submitter,
		arg.System,
		arg.Talkgroup,
		arg.CallDate,
		arg.AudioName,
		arg.AudioBlob,
		arg.AudioType,
		arg.AudioRef,
		arg.Duration,
		arg.Frequency,
		arg.Frequencies,
		arg.Patches,
		arg.TalkerAlias,
		arg.TGLabel,
		arg.TGAlphaTag,
		arg.TGGroup,
		arg.Source,
	)
	return err
}

const addRefJournal = `-- name: AddRefJournal :one
INSERT INTO audio_ref_journal (
	call_id,
	backend,
	ref,
	prune_after,
	last_try,
	tries
) VALUES (
	$1,
	$2,
	$3,
	$4,
	NOW(),
	$5
) RETURNING id
`

type AddRefJournalParams struct {
	CallID     pgtype.UUID `db:"call_id" json:"callId"`
	Backend    string      `db:"backend" json:"backend"`
	Ref        []byte      `db:"ref" json:"ref"`
	PruneAfter *time.Time  `db:"prune_after" json:"pruneAfter"`
	Tries      int         `db:"tries" json:"tries"`
}

func (q *Queries) AddRefJournal(ctx context.Context, arg AddRefJournalParams) (int64, error) {
	row := q.db.QueryRow(ctx, addRefJournal,
		arg.CallID,
		arg.Backend,
		arg.Ref,
		arg.PruneAfter,
		arg.Tries,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const cleanupSweptCalls = `-- name: CleanupSweptCalls :execrows
WITH to_sweep AS (
	SELECT id FROM calls
	JOIN incidents_calls ic ON ic.call_id = calls.id
	WHERE calls.call_date >= $1 AND calls.call_date < $2
) UPDATE incidents_calls
	SET
		swept_call_id = call_id,
		calls_tbl_id = NULL
	WHERE call_id IN (SELECT id FROM to_sweep)
`

func (q *Queries) CleanupSweptCalls(ctx context.Context, rangeStart time.Time, rangeEnd time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupSweptCalls, rangeStart, rangeEnd)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRefJournal = `-- name: CountRefJournal :one
SELECT COUNT(*)
FROM
audio_ref_journal
WHERE
	(prune_after IS NULL OR NOW() > prune_after) AND
	CASE
		WHEN $1::BOOLEAN IS TRUE THEN ref IS NULL
		WHEN $1::BOOLEAN IS FALSE THEN ref IS NOT NULL
		ELSE TRUE
	END AND
	CASE WHEN $2::TIMESTAMPTZ IS NOT NULL THEN last_try > $2 ELSE TRUE END AND
	CASE WHEN $3::TIMESTAMPTZ IS NOT NULL THEN last_try <= $3 ELSE TRUE END
`

func (q *Queries) CountRefJournal(ctx context.Context, missing *bool, since *time.Time, until *time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countRefJournal, missing, since, until)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCall = `-- name: DeleteCall :exec
DELETE FROM calls WHERE id = $1
`

func (q *Queries) DeleteCall(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCall, id)
	return err
}

const detailedCountRefJournal = `-- name: DetailedCountRefJournal :many
SELECT
COUNT(*), backend, (ref IS NULL)::BOOLEAN has_ref
FROM audio_ref_journal
GROUP BY backend, has_ref
`

type DetailedCountRefJournalRow struct {
	Count   int64  `db:"count" json:"count"`
	Backend string `db:"backend" json:"backend"`
	HasRef  bool   `db:"has_ref" json:"hasRef"`
}

func (q *Queries) DetailedCountRefJournal(ctx context.Context) ([]DetailedCountRefJournalRow, error) {
	rows, err := q.db.Query(ctx, detailedCountRefJournal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DetailedCountRefJournalRow
	for rows.Next() {
		var i DetailedCountRefJournalRow
		if err := rows.Scan(&i.Count, &i.Backend, &i.HasRef); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dropRefJournal = `-- name: DropRefJournal :exec
DELETE FROM audio_ref_journal
WHERE id = $1
`

func (q *Queries) DropRefJournal(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, dropRefJournal, id)
	return err
}

const getCall = `-- name: GetCall :one
SELECT
	id,
	submitter,
	system,
	talkgroup,
	call_date,
	audio_name,
	audio_type,
	audio_ref,
	duration,
	frequency,
	frequencies,
	patches,
	talker_alias,
	tg_label,
	tg_alpha_tag,
	tg_group,
	source,
	transcript
FROM calls
WHERE id = $1
`

type GetCallRow struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	Submitter   *int32        `db:"submitter" json:"submitter"`
	System      int           `db:"system" json:"system"`
	Talkgroup   int           `db:"talkgroup" json:"talkgroup"`
	CallDate    time.Time     `db:"call_date" json:"callDate"`
	AudioName   *string       `db:"audio_name" json:"audioName"`
	AudioType   NullAudioMIME `db:"audio_type" json:"audioType"`
	AudioRef    []byte        `db:"audio_ref" json:"audioRef"`
	Duration    *int32        `db:"duration" json:"duration"`
	Frequency   int           `db:"frequency" json:"frequency"`
	Frequencies []int         `db:"frequencies" json:"frequencies"`
	Patches     []int         `db:"patches" json:"patches"`
	TalkerAlias *string       `db:"talker_alias" json:"talkerAlias,omitempty"`
	TGLabel     *string       `db:"tg_label" json:"tgLabel"`
	TGAlphaTag  *string       `db:"tg_alpha_tag" json:"tgAlphaTag"`
	TGGroup     *string       `db:"tg_group" json:"tgGroup"`
	Source      int           `db:"source" json:"source"`
	Transcript  *string       `db:"transcript" json:"transcript"`
}

func (q *Queries) GetCall(ctx context.Context, id uuid.UUID) (GetCallRow, error) {
	row := q.db.QueryRow(ctx, getCall, id)
	var i GetCallRow
	err := row.Scan(
		&i.ID,
		&i.Submitter,
		&i.System,
		&i.Talkgroup,
		&i.CallDate,
		&i.AudioName,
		&i.AudioType,
		&i.AudioRef,
		&i.Duration,
		&i.Frequency,
		&i.Frequencies,
		&i.Patches,
		&i.TalkerAlias,
		&i.TGLabel,
		&i.TGAlphaTag,
		&i.TGGroup,
		&i.Source,
		&i.Transcript,
	)
	return i, err
}

const getCallAudio = `-- name: GetCallAudio :many
SELECT
	c.id,
	c.call_date,
	c.audio_name,
	c.audio_type,
	c.audio_ref,
	c.audio_blob,
	FALSE AS swept
FROM calls c
JOIN talkgroups tgs ON c.talkgroup = tgs.tgid AND c.system = tgs.system_id
LEFT JOIN incidents_calls ic ON c.id = ic.calls_tbl_id AND c.call_date = ic.call_date
WHERE
CASE WHEN $2::BOOLEAN = TRUE THEN
	FALSE ELSE TRUE END AND
CASE WHEN $3::TIMESTAMPTZ IS NOT NULL THEN
	c.call_date >= $3 ELSE TRUE END AND
CASE WHEN $4::TIMESTAMPTZ IS NOT NULL THEN
	c.call_date <= $4 ELSE TRUE END AND
CASE WHEN $5::TEXT[] IS NOT NULL THEN
	tgs.tags && ARRAY[$5] ELSE TRUE END AND
CASE WHEN $6::TEXT[] IS NOT NULL THEN
	(NOT (tgs.tags && ARRAY[$6])) ELSE TRUE END AND
CASE WHEN $7::NUMERIC IS NOT NULL THEN (
		c.duration > $7
	) ELSE TRUE END AND
CASE WHEN $8::TEXT IS NOT NULL THEN (
	c.audio_ref IS NOT NULL AND c.audio_ref ? $8) ELSE TRUE END AND
CASE WHEN $9::TEXT IS NOT NULL THEN (
	c.audio_ref IS NULL OR (NOT c.audio_ref ? $9)) ELSE TRUE END
AND CASE
	WHEN $10::BOOLEAN IS NULL THEN TRUE
	WHEN $10::BOOLEAN = TRUE THEN (c.audio_blob IS NOT NULL)
	WHEN $10::BOOLEAN = FALSE THEN (c.audio_blob IS NULL)
END
UNION
SELECT
	sc.id,
	sc.call_date,
	sc.audio_name,
	sc.audio_type,
	sc.audio_ref,
	sc.audio_blob,
	TRUE AS swept
FROM swept_calls sc
JOIN talkgroups tgs ON sc.talkgroup = tgs.tgid AND sc.system = tgs.system_id
LEFT JOIN incidents_calls ic ON sc.id = ic.calls_tbl_id AND sc.call_date = ic.call_date
WHERE 
CASE WHEN $2::BOOLEAN = FALSE THEN
	FALSE ELSE TRUE END AND
CASE WHEN $3::TIMESTAMPTZ IS NOT NULL THEN
	sc.call_date >= $3 ELSE TRUE END AND
CASE WHEN $4::TIMESTAMPTZ IS NOT NULL THEN
	sc.call_date <= $4 ELSE TRUE END AND
CASE WHEN $5::TEXT[] IS NOT NULL THEN
	tgs.tags && ARRAY[$5] ELSE TRUE END AND
CASE WHEN $6::TEXT[] IS NOT NULL THEN
	(NOT (tgs.tags && ARRAY[$6])) ELSE TRUE END AND
CASE WHEN $7::NUMERIC IS NOT NULL THEN (
		sc.duration > $7
	) ELSE TRUE END AND
CASE WHEN $8::TEXT IS NOT NULL THEN (
	sc.audio_ref IS NOT NULL AND sc.audio_ref ? $8) ELSE TRUE END AND
CASE WHEN $9::TEXT IS NOT NULL THEN (
	sc.audio_ref IS NULL OR (NOT sc.audio_ref ? $9)) ELSE TRUE END
AND CASE
	WHEN $10::BOOLEAN IS NULL THEN TRUE
	WHEN $10::BOOLEAN = TRUE THEN (sc.audio_blob IS NOT NULL)
	WHEN $10::BOOLEAN = FALSE THEN (sc.audio_blob IS NULL)
END
ORDER BY call_date ASC
FETCH NEXT $1 ROWS ONLY
`

type GetCallAudioParams struct {
	Count         int32          `db:"count" json:"count"`
	Swept         *bool          `db:"swept" json:"swept"`
	Start         *time.Time     `db:"start" json:"start"`
	End           *time.Time     `db:"end" json:"end"`
	TagsAny       []string       `db:"tags_any" json:"tagsAny"`
	TagsNot       []string       `db:"tags_not" json:"tagsNot"`
	LongerThan    pgtype.Numeric `db:"longer_than" json:"longerThan"`
	HasBackend    *string        `db:"has_backend" json:"hasBackend"`
	NotHasBackend *string        `db:"not_has_backend" json:"notHasBackend"`
	HasBlob       *bool          `db:"has_blob" json:"hasBlob"`
}

type GetCallAudioRow struct {
	ID        uuid.UUID     `db:"id" json:"id"`
	CallDate  time.Time     `db:"call_date" json:"callDate"`
	AudioName *string       `db:"audio_name" json:"audioName"`
	AudioType NullAudioMIME `db:"audio_type" json:"audioType"`
	AudioRef  []byte        `db:"audio_ref" json:"audioRef"`
	AudioBlob []byte        `db:"audio_blob" json:"audioBlob"`
	Swept     bool          `db:"swept" json:"swept"`
}

// For now, this must be kept in sync with pkg/database/calls.go GetCallAudioCount and GetCallAudioCb Scan
func (q *Queries) GetCallAudio(ctx context.Context, arg GetCallAudioParams) ([]GetCallAudioRow, error) {
	rows, err := q.db.Query(ctx, getCallAudio,
		arg.Count,
		arg.Swept,
		arg.Start,
		arg.End,
		arg.TagsAny,
		arg.TagsNot,
		arg.LongerThan,
		arg.HasBackend,
		arg.NotHasBackend,
		arg.HasBlob,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCallAudioRow
	for rows.Next() {
		var i GetCallAudioRow
		if err := rows.Scan(
			&i.ID,
			&i.CallDate,
			&i.AudioName,
			&i.AudioType,
			&i.AudioRef,
			&i.AudioBlob,
			&i.Swept,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCallAudioByID = `-- name: GetCallAudioByID :one
SELECT
	c.call_date,
	c.audio_name,
	c.audio_type,
	c.audio_ref,
	c.audio_blob
FROM calls c
WHERE c.id = $1
UNION
SELECT
	sc.call_date,
	sc.audio_name,
	sc.audio_type,
	sc.audio_ref,
	sc.audio_blob
FROM swept_calls sc
WHERE sc.id = $1
`

type GetCallAudioByIDRow struct {
	CallDate  time.Time     `db:"call_date" json:"callDate"`
	AudioName *string       `db:"audio_name" json:"audioName"`
	AudioType NullAudioMIME `db:"audio_type" json:"audioType"`
	AudioRef  []byte        `db:"audio_ref" json:"audioRef"`
	AudioBlob []byte        `db:"audio_blob" json:"audioBlob"`
}

func (q *Queries) GetCallAudioByID(ctx context.Context, id uuid.UUID) (GetCallAudioByIDRow, error) {
	row := q.db.QueryRow(ctx, getCallAudioByID, id)
	var i GetCallAudioByIDRow
	err := row.Scan(
		&i.CallDate,
		&i.AudioName,
		&i.AudioType,
		&i.AudioRef,
		&i.AudioBlob,
	)
	return i, err
}

const getCallSubmitter = `-- name: GetCallSubmitter :one
SELECT submitter FROM calls WHERE id = $1
`

func (q *Queries) GetCallSubmitter(ctx context.Context, id uuid.UUID) (*int32, error) {
	row := q.db.QueryRow(ctx, getCallSubmitter, id)
	var submitter *int32
	err := row.Scan(&submitter)
	return submitter, err
}

const getCalls = `-- name: GetCalls :many
SELECT calls.id, calls.submitter, calls.system, calls.talkgroup, calls.call_date, calls.audio_name, calls.audio_blob, calls.duration, calls.audio_type, calls.audio_ref, calls.frequency, calls.frequencies, calls.patches, calls.talker_alias, calls.tg_label, calls.tg_alpha_tag, calls.tg_group, calls.source, calls.transcript FROM calls WHERE id = ANY($1::UUID[])
`

type GetCallsRow struct {
	Call Call `db:"call" json:"call"`
}

func (q *Queries) GetCalls(ctx context.Context, ids []uuid.UUID) ([]GetCallsRow, error) {
	rows, err := q.db.Query(ctx, getCalls, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCallsRow
	for rows.Next() {
		var i GetCallsRow
		if err := rows.Scan(
			&i.Call.ID,
			&i.Call.Submitter,
			&i.Call.System,
			&i.Call.Talkgroup,
			&i.Call.CallDate,
			&i.Call.AudioName,
			&i.Call.AudioBlob,
			&i.Call.Duration,
			&i.Call.AudioType,
			&i.Call.AudioRef,
			&i.Call.Frequency,
			&i.Call.Frequencies,
			&i.Call.Patches,
			&i.Call.TalkerAlias,
			&i.Call.TGLabel,
			&i.Call.TGAlphaTag,
			&i.Call.TGGroup,
			&i.Call.Source,
			&i.Call.Transcript,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatabaseSize = `-- name: GetDatabaseSize :one
SELECT pg_size_pretty(pg_database_size(current_database()))
`

func (q *Queries) GetDatabaseSize(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getDatabaseSize)
	var pg_size_pretty string
	err := row.Scan(&pg_size_pretty)
	return pg_size_pretty, err
}

const getPrunableAudioRefs = `-- name: GetPrunableAudioRefs :many
SELECT
	r.backend::TEXT backend,
	LEFT(r.ref, POSITION('/' IN r.ref)) path_first
FROM
	calls
CROSS JOIN
	jsonb_each_text(audio_ref) AS r (backend, ref)
WHERE
	call_date > $1 AND call_date <= $2
GROUP BY
	r.backend, path_first
`

type GetPrunableAudioRefsRow struct {
	Backend   string `db:"backend" json:"backend"`
	PathFirst string `db:"path_first" json:"pathFirst"`
}

func (q *Queries) GetPrunableAudioRefs(ctx context.Context, partitionStart time.Time, partitionEnd time.Time) ([]GetPrunableAudioRefsRow, error) {
	rows, err := q.db.Query(ctx, getPrunableAudioRefs, partitionStart, partitionEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPrunableAudioRefsRow
	for rows.Next() {
		var i GetPrunableAudioRefsRow
		if err := rows.Scan(&i.Backend, &i.PathFirst); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefJournal = `-- name: GetRefJournal :many
SELECT id, call_id, backend, ref, prune_after, last_try, tries
FROM
audio_ref_journal
WHERE
	(prune_after IS NULL OR NOW() > prune_after) AND
	CASE
		WHEN $1::BOOLEAN IS TRUE THEN ref IS NULL
		WHEN $1::BOOLEAN IS FALSE THEN ref IS NOT NULL
		ELSE TRUE
	END AND
	CASE WHEN $2::TIMESTAMPTZ IS NOT NULL THEN last_try > $2 ELSE TRUE END AND
	CASE WHEN $3::TIMESTAMPTZ IS NOT NULL THEN last_try <= $3 ELSE TRUE END
ORDER BY backend, last_try ASC
LIMIT (CASE WHEN $4::INTEGER IS NOT NULL THEN $4 ELSE 10000000000 END)
`

type GetRefJournalParams struct {
	Missing *bool      `db:"missing" json:"missing"`
	Since   *time.Time `db:"since" json:"since"`
	Until   *time.Time `db:"until" json:"until"`
	Num     *int32     `db:"num" json:"num"`
}

func (q *Queries) GetRefJournal(ctx context.Context, arg GetRefJournalParams) ([]AudioRefJournal, error) {
	rows, err := q.db.Query(ctx, getRefJournal,
		arg.Missing,
		arg.Since,
		arg.Until,
		arg.Num,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AudioRefJournal
	for rows.Next() {
		var i AudioRefJournal
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.Backend,
			&i.Ref,
			&i.PruneAfter,
			&i.LastTry,
			&i.Tries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSweptCallsWithRef = `-- name: GetSweptCallsWithRef :many
SELECT id, call_date, audio_ref, audio_blob FROM swept_calls WHERE audio_ref IS NOT NULL
`

type GetSweptCallsWithRefRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CallDate  time.Time `db:"call_date" json:"callDate"`
	AudioRef  []byte    `db:"audio_ref" json:"audioRef"`
	AudioBlob []byte    `db:"audio_blob" json:"audioBlob"`
}

func (q *Queries) GetSweptCallsWithRef(ctx context.Context) ([]GetSweptCallsWithRefRow, error) {
	rows, err := q.db.Query(ctx, getSweptCallsWithRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSweptCallsWithRefRow
	for rows.Next() {
		var i GetSweptCallsWithRefRow
		if err := rows.Scan(
			&i.ID,
			&i.CallDate,
			&i.AudioRef,
			&i.AudioBlob,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTranscriptsContext = `-- name: GetTranscriptsContext :many
SELECT c.call_date, c.transcript FROM calls c
WHERE
(c.system, c.talkgroup) = ($1, $2) AND
c.call_date >= NOW() - $3::interval AND
c.transcript IS NOT NULL AND
c.duration > $4
ORDER BY c.call_date DESC
LIMIT $5
`

type GetTranscriptsContextParams struct {
	System         int             `db:"system" json:"system"`
	Talkgroup      int             `db:"talkgroup" json:"talkgroup"`
	Lookback       pgtype.Interval `db:"lookback" json:"lookback"`
	DurationMS     *int32          `db:"duration_ms" json:"durationMs"`
	NumTranscripts int32           `db:"num_transcripts" json:"numTranscripts"`
}

type GetTranscriptsContextRow struct {
	CallDate   time.Time `db:"call_date" json:"callDate"`
	Transcript *string   `db:"transcript" json:"transcript"`
}

func (q *Queries) GetTranscriptsContext(ctx context.Context, arg GetTranscriptsContextParams) ([]GetTranscriptsContextRow, error) {
	rows, err := q.db.Query(ctx, getTranscriptsContext,
		arg.System,
		arg.Talkgroup,
		arg.Lookback,
		arg.DurationMS,
		arg.NumTranscripts,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTranscriptsContextRow
	for rows.Next() {
		var i GetTranscriptsContextRow
		if err := rows.Scan(&i.CallDate, &i.Transcript); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementRefJournal = `-- name: IncrementRefJournal :exec
UPDATE audio_ref_journal SET
	tries = tries + 1,
	last_try = NOW()
WHERE id = $1
`

func (q *Queries) IncrementRefJournal(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementRefJournal, id)
	return err
}

const listCallsCount = `-- name: ListCallsCount :one
SELECT
COUNT(*)
FROM calls c
JOIN talkgroups tgs ON c.talkgroup = tgs.tgid AND c.system = tgs.system_id
WHERE
CASE WHEN $1::TIMESTAMPTZ IS NOT NULL THEN
	c.call_date >= $1 ELSE TRUE END AND
CASE WHEN $2::TIMESTAMPTZ IS NOT NULL THEN
	c.call_date <= $2 ELSE TRUE END AND
CASE WHEN $3::TEXT[] IS NOT NULL THEN
	tgs.tags && ARRAY[$3] ELSE TRUE END AND
CASE WHEN $4::TEXT[] IS NOT NULL THEN
	(NOT (tgs.tags && ARRAY[$4])) ELSE TRUE END AND
(CASE WHEN $5::TEXT IS NOT NULL THEN (
		tgs.tg_group ILIKE '%' || $5 || '%' OR
		tgs.name ILIKE '%' || $5 || '%' OR
		tgs.alpha_tag ILIKE '%' || $5 || '%'
	) ELSE TRUE END) AND
(CASE WHEN $6::TEXT IS NOT NULL THEN (
		c.talker_alias ILIKE '%' || $6 || '%'
	) ELSE TRUE END) AND
(CASE WHEN $7::NUMERIC IS NOT NULL THEN (
		c.duration > $7
	) ELSE TRUE END) AND
(CASE WHEN $8::BOOLEAN = TRUE THEN (
	tgs.tgid IS NULL
	) ELSE TRUE END) AND
(CASE WHEN $9::TEXT IS NOT NULL AND $9 != '' THEN (
	to_tsvector('english', transcript) @@ websearch_to_tsquery('english', $9)
	) ELSE TRUE END)
`

type ListCallsCountParams struct {
	Start            *time.Time     `db:"start" json:"start"`
	End              *time.Time     `db:"end" json:"end"`
	TagsAny          []string       `db:"tags_any" json:"tagsAny"`
	TagsNot          []string       `db:"tags_not" json:"tagsNot"`
	TGFilter         *string        `db:"tg_filter" json:"tgFilter"`
	SourceFilter     *string        `db:"source_filter" json:"sourceFilter"`
	LongerThan       pgtype.Numeric `db:"longer_than" json:"longerThan"`
	UnknownTG        bool           `db:"unknown_tg" json:"unknownTg"`
	TranscriptSearch *string        `db:"transcript_search" json:"transcriptSearch"`
}

func (q *Queries) ListCallsCount(ctx context.Context, arg ListCallsCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, listCallsCount,
		arg.Start,
		arg.End,
		arg.TagsAny,
		arg.TagsNot,
		arg.TGFilter,
		arg.SourceFilter,
		arg.LongerThan,
		arg.UnknownTG,
		arg.TranscriptSearch,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCallsP = `-- name: ListCallsP :many
SELECT
c.id,
c.call_date,
c.duration,
c.system system_id,
c.talkgroup tgid,
c.talker_alias,
c.source,
(CASE
	WHEN $1::TEXT = '' THEN c.transcript
	WHEN $1 IS NOT NULL THEN 
	ts_headline(c.transcript,
		websearch_to_tsquery('english', $1),
		'HighlightAll=true')
	ELSE NULL END) transcript,
COUNT(ic.incident_id) incidents,
(c.transcript IS NOT NULL)::BOOLEAN has_transcript
FROM calls c
JOIN talkgroups tgs ON c.talkgroup = tgs.tgid AND c.system = tgs.system_id
LEFT JOIN incidents_calls ic ON c.id = ic.calls_tbl_id AND c.call_date = ic.call_date
WHERE
CASE WHEN $2::TIMESTAMPTZ IS NOT NULL THEN
	c.call_date >= $2 ELSE TRUE END AND
CASE WHEN $3::TIMESTAMPTZ IS NOT NULL THEN
	c.call_date <= $3 ELSE TRUE END AND
CASE WHEN $4::TEXT[] IS NOT NULL THEN
	tgs.tags && ARRAY[$4] ELSE TRUE END AND
CASE WHEN $5::TEXT[] IS NOT NULL THEN
	(NOT (tgs.tags && ARRAY[$5])) ELSE TRUE END AND
(CASE WHEN $6::TEXT IS NOT NULL THEN (
		tgs.tg_group ILIKE '%' || $6 || '%' OR
		tgs.name ILIKE '%' || $6 || '%' OR
		tgs.alpha_tag ILIKE '%' || $6 || '%'
	) ELSE TRUE END) AND
(CASE WHEN $7::TEXT IS NOT NULL THEN (
		c.talker_alias ILIKE '%' || $7 || '%'
	) ELSE TRUE END) AND
(CASE WHEN $8::NUMERIC IS NOT NULL THEN (
		c.duration > $8
	) ELSE TRUE END) AND
(CASE WHEN $9::BOOLEAN = TRUE THEN (
	tgs.tgid IS NULL
	) ELSE TRUE END) AND
(CASE WHEN $1::TEXT IS NOT NULL AND $1 != '' THEN (
	to_tsvector('english', c.transcript) @@ websearch_to_tsquery('english', $1)
	) ELSE TRUE END)
GROUP BY c.id, c.call_date
ORDER BY
CASE WHEN $10::TEXT = 'asc' THEN c.call_date END ASC,
CASE WHEN $10 = 'desc' THEN c.call_date END DESC
OFFSET $11 ROWS
FETCH NEXT $12 ROWS ONLY
`

type ListCallsPParams struct {
	TranscriptSearch *string        `db:"transcript_search" json:"transcriptSearch"`
	Start            *time.Time     `db:"start" json:"start"`
	End              *time.Time     `db:"end" json:"end"`
	TagsAny          []string       `db:"tags_any" json:"tagsAny"`
	TagsNot          []string       `db:"tags_not" json:"tagsNot"`
	TGFilter         *string        `db:"tg_filter" json:"tgFilter"`
	SourceFilter     *string        `db:"source_filter" json:"sourceFilter"`
	LongerThan       pgtype.Numeric `db:"longer_than" json:"longerThan"`
	UnknownTG        bool           `db:"unknown_tg" json:"unknownTg"`
	Direction        string         `db:"direction" json:"direction"`
	Offset           int32          `db:"offset" json:"offset"`
	PerPage          int32          `db:"per_page" json:"perPage"`
}

type ListCallsPRow struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	CallDate      time.Time   `db:"call_date" json:"callDate"`
	Duration      *int32      `db:"duration" json:"duration"`
	SystemID      int         `db:"system_id" json:"systemId"`
	TGID          int         `db:"tgid" json:"tgid"`
	TalkerAlias   *string     `db:"talker_alias" json:"talkerAlias,omitempty"`
	Source        int         `db:"source" json:"source,omitzero"`
	Transcript    interface{} `db:"transcript" json:"transcript,omitempty"`
	Incidents     int64       `db:"incidents" json:"incidents,omitempty,omitzero"`
	HasTranscript bool        `db:"has_transcript" json:"hasTranscript,omitzero"`
}

func (q *Queries) ListCallsP(ctx context.Context, arg ListCallsPParams) ([]ListCallsPRow, error) {
	rows, err := q.db.Query(ctx, listCallsP,
		arg.TranscriptSearch,
		arg.Start,
		arg.End,
		arg.TagsAny,
		arg.TagsNot,
		arg.TGFilter,
		arg.SourceFilter,
		arg.LongerThan,
		arg.UnknownTG,
		arg.Direction,
		arg.Offset,
		arg.PerPage,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCallsPRow
	for rows.Next() {
		var i ListCallsPRow
		if err := rows.Scan(
			&i.ID,
			&i.CallDate,
			&i.Duration,
			&i.SystemID,
			&i.TGID,
			&i.TalkerAlias,
			&i.Source,
			&i.Transcript,
			&i.Incidents,
			&i.HasTranscript,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCallAudio = `-- name: SetCallAudio :exec
UPDATE calls SET audio_ref = $2, audio_blob = $3
WHERE id = $1
`

func (q *Queries) SetCallAudio(ctx context.Context, iD uuid.UUID, audioRef []byte, audioBlob []byte) error {
	_, err := q.db.Exec(ctx, setCallAudio, iD, audioRef, audioBlob)
	return err
}

const setCallTranscript = `-- name: SetCallTranscript :one
UPDATE calls SET transcript = $2 WHERE id = $1
RETURNING call_date, system, talkgroup, patches
`

type SetCallTranscriptRow struct {
	CallDate  time.Time `db:"call_date" json:"callDate"`
	System    int       `db:"system" json:"system"`
	Talkgroup int       `db:"talkgroup" json:"talkgroup"`
	Patches   []int     `db:"patches" json:"patches"`
}

func (q *Queries) SetCallTranscript(ctx context.Context, iD uuid.UUID, transcript *string) (SetCallTranscriptRow, error) {
	row := q.db.QueryRow(ctx, setCallTranscript, iD, transcript)
	var i SetCallTranscriptRow
	err := row.Scan(
		&i.CallDate,
		&i.System,
		&i.Talkgroup,
		&i.Patches,
	)
	return i, err
}

const setRefJournalPrune = `-- name: SetRefJournalPrune :exec
UPDATE audio_ref_journal SET
	prune_after = $2
WHERE
	id = $1
`

func (q *Queries) SetRefJournalPrune(ctx context.Context, iD int64, pruneAfter *time.Time) error {
	_, err := q.db.Exec(ctx, setRefJournalPrune, iD, pruneAfter)
	return err
}

const setSweptAudioAndClearRef = `-- name: SetSweptAudioAndClearRef :exec
UPDATE swept_calls SET audio_blob = $1, audio_ref = NULL WHERE id = $2
`

func (q *Queries) SetSweptAudioAndClearRef(ctx context.Context, audioBlob []byte, iD uuid.UUID) error {
	_, err := q.db.Exec(ctx, setSweptAudioAndClearRef, audioBlob, iD)
	return err
}

const setSweptCallAudio = `-- name: SetSweptCallAudio :exec
UPDATE swept_calls SET audio_ref = $2, audio_blob = $3
WHERE id = $1
`

func (q *Queries) SetSweptCallAudio(ctx context.Context, iD uuid.UUID, audioRef []byte, audioBlob []byte) error {
	_, err := q.db.Exec(ctx, setSweptCallAudio, iD, audioRef, audioBlob)
	return err
}

const sweepCalls = `-- name: SweepCalls :execrows
WITH to_sweep AS (
	SELECT id,
	submitter,
	system,
	talkgroup,
	calls.call_date,
	audio_name,
	audio_blob,
	duration,
	audio_type,
	audio_ref,
	frequency,
	frequencies,
	patches,
	talker_alias,
	tg_label,
	tg_alpha_tag,
	tg_group,
	source,
	transcript
	FROM calls
	JOIN incidents_calls ic ON ic.call_id = calls.id
	WHERE calls.call_date >= $1 AND calls.call_date < $2
) INSERT INTO swept_calls (
	id,
	submitter,
	system,
	talkgroup,
	call_date,
	audio_name,
	audio_blob,
	duration,
	audio_type,
	audio_ref,
	frequency,
	frequencies,
	patches,
	talker_alias,
	tg_label,
	tg_alpha_tag,
	tg_group,
	source,
	transcript
) SELECT 
	id,
	submitter,
	system,
	talkgroup,
	call_date,
	audio_name,
	audio_blob,
	duration,
	audio_type,
	audio_ref,
	frequency,
	frequencies,
	patches,
	talker_alias,
	tg_label,
	tg_alpha_tag,
	tg_group,
	source,
	transcript
FROM to_sweep ON CONFLICT DO NOTHING
`

// This is used to sweep calls that are part of an incident prior to pruning a partition.
func (q *Queries) SweepCalls(ctx context.Context, rangeStart time.Time, rangeEnd time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, sweepCalls, rangeStart, rangeEnd)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
