// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incidents.sql

package database

import (
	"context"
	"time"

	"dynatron.me/x/stillbox/internal/jsontypes"
	"github.com/google/uuid"
)

const addToIncident = `-- name: AddToIncident :exec
WITH inp AS (
SELECT
	UNNEST($2::UUID[]) id,
	UNNEST($3::JSONB[]) notes
) INSERT INTO incidents_calls(
	incident_id,
	call_id,
	calls_tbl_id,
	call_date,
	notes
)
SELECT
	$1::UUID,
	inp.id,
	inp.id,
	c.call_date,
	inp.notes
FROM inp
JOIN calls c ON c.id = inp.id
ON CONFLICT DO NOTHING
`

func (q *Queries) AddToIncident(ctx context.Context, incidentID uuid.UUID, callIds []uuid.UUID, notes [][]byte) error {
	_, err := q.db.Exec(ctx, addToIncident, incidentID, callIds, notes)
	return err
}

const callInIncident = `-- name: CallInIncident :one
SELECT EXISTS
	(SELECT 1 FROM incidents_calls ic
	WHERE
	ic.incident_id = $1 AND
	ic.call_id = $2)
`

func (q *Queries) CallInIncident(ctx context.Context, incidentID uuid.UUID, callID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, callInIncident, incidentID, callID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (
	id,
	name,
	owner_id,
	description,
	created_at,
	start_time,
	end_time,
	location,
	metadata
) VALUES (
	$1,
	$2,
	$3,
	$4,
	NOW(),
	$5,
	$6,
	$7,
	$8
)
RETURNING id, name, owner_id, description, created_at, start_time, end_time, location, metadata
`

type CreateIncidentParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	OwnerID     int                `db:"owner_id" json:"ownerId"`
	Description *string            `db:"description" json:"description"`
	StartTime   *time.Time         `db:"start_time" json:"startTime"`
	EndTime     *time.Time         `db:"end_time" json:"endTime"`
	Location    []byte             `db:"location" json:"location"`
	Metadata    jsontypes.Metadata `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.ID,
		arg.Name,
		arg.OwnerID,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.Metadata,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Description,
		&i.CreatedAt,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Metadata,
	)
	return i, err
}

const deleteIncident = `-- name: DeleteIncident :exec
DELETE FROM incidents CASCADE WHERE id = $1
`

func (q *Queries) DeleteIncident(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIncident, id)
	return err
}

const getIncident = `-- name: GetIncident :one
SELECT
	incidents.id, incidents.name, incidents.owner_id, incidents.description, incidents.created_at, incidents.start_time, incidents.end_time, incidents.location, incidents.metadata,
	COALESCE(incidents.start_time, MIN(ic.call_date)) start_time,
	COALESCE(incidents.end_time, MAX(ic.call_date)) end_time,
	users.username owner
FROM incidents
LEFT JOIN incidents_calls ic ON incidents.id = ic.incident_id
JOIN users ON incidents.owner_id = users.id
WHERE incidents.id = $1
GROUP BY incidents.id, users.username
`

type GetIncidentRow struct {
	Incident  Incident   `db:"incident" json:"incident"`
	StartTime *time.Time `db:"start_time" json:"startTime"`
	EndTime   *time.Time `db:"end_time" json:"endTime"`
	Owner     string     `db:"owner" json:"owner"`
}

func (q *Queries) GetIncident(ctx context.Context, id uuid.UUID) (GetIncidentRow, error) {
	row := q.db.QueryRow(ctx, getIncident, id)
	var i GetIncidentRow
	err := row.Scan(
		&i.Incident.ID,
		&i.Incident.Name,
		&i.Incident.OwnerID,
		&i.Incident.Description,
		&i.Incident.CreatedAt,
		&i.Incident.StartTime,
		&i.Incident.EndTime,
		&i.Incident.Location,
		&i.Incident.Metadata,
		&i.StartTime,
		&i.EndTime,
		&i.Owner,
	)
	return i, err
}

const getIncidentCallCount = `-- name: GetIncidentCallCount :one
SELECT COUNT(*) FROM incidents_calls
WHERE incident_id = $1
`

func (q *Queries) GetIncidentCallCount(ctx context.Context, incidentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getIncidentCallCount, incidentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getIncidentCalls = `-- name: GetIncidentCalls :many
SELECT
	ic.call_id,
	ic.call_date,
	c.duration,
	c.system system_id,
	c.talkgroup tgid,
	ic.notes,
	c.submitter,
	c.audio_name,
	c.audio_type,
	c.audio_ref,
	c.frequency,
	c.frequencies,
	c.talker_alias,
	c.patches,
	c.source,
	c.transcript
FROM incidents_calls ic, LATERAL (
	SELECT 
	ca.submitter,
	ca.system,
	ca.talkgroup,
	ca.audio_name,
	ca.duration,
	ca.audio_type,
	ca.audio_ref,
	ca.frequency,
	ca.frequencies,
	ca.talker_alias,
	ca.patches,
	ca.source,
	ca.transcript
	FROM calls ca WHERE ca.id = ic.calls_tbl_id AND ca.call_date = ic.call_date
	UNION
	SELECT
	sc.submitter,
	sc.system,
	sc.talkgroup,
	sc.audio_name,
	sc.duration,
	sc.audio_type,
	sc.audio_ref,
	sc.frequency,
	sc.frequencies,
	sc.talker_alias,
	sc.patches,
	sc.source,
	sc.transcript
	FROM swept_calls sc WHERE sc.id = ic.swept_call_id
) c
WHERE ic.incident_id = $1
ORDER BY ic.call_date ASC
OFFSET $2 ROWS
FETCH NEXT $3 ROWS ONLY
`

type GetIncidentCallsRow struct {
	CallID      uuid.UUID     `db:"call_id" json:"callId"`
	CallDate    *time.Time    `db:"call_date" json:"callDate"`
	Duration    *int32        `db:"duration" json:"duration"`
	SystemID    int           `db:"system_id" json:"systemId"`
	TGID        int           `db:"tgid" json:"tgid"`
	Notes       []byte        `db:"notes" json:"notes"`
	Submitter   *int32        `db:"submitter" json:"submitter"`
	AudioName   *string       `db:"audio_name" json:"audioName"`
	AudioType   NullAudioMIME `db:"audio_type" json:"audioType"`
	AudioRef    []byte        `db:"audio_ref" json:"audioRef"`
	Frequency   int           `db:"frequency" json:"frequency"`
	Frequencies []int         `db:"frequencies" json:"frequencies"`
	TalkerAlias *string       `db:"talker_alias" json:"talkerAlias"`
	Patches     []int         `db:"patches" json:"patches"`
	Source      int           `db:"source" json:"source"`
	Transcript  *string       `db:"transcript" json:"transcript"`
}

func (q *Queries) GetIncidentCalls(ctx context.Context, iD uuid.UUID, offset int32, perPage *int32) ([]GetIncidentCallsRow, error) {
	rows, err := q.db.Query(ctx, getIncidentCalls, iD, offset, perPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIncidentCallsRow
	for rows.Next() {
		var i GetIncidentCallsRow
		if err := rows.Scan(
			&i.CallID,
			&i.CallDate,
			&i.Duration,
			&i.SystemID,
			&i.TGID,
			&i.Notes,
			&i.Submitter,
			&i.AudioName,
			&i.AudioType,
			&i.AudioRef,
			&i.Frequency,
			&i.Frequencies,
			&i.TalkerAlias,
			&i.Patches,
			&i.Source,
			&i.Transcript,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncidentOwner = `-- name: GetIncidentOwner :one
SELECT owner_id FROM incidents WHERE id = $1
`

func (q *Queries) GetIncidentOwner(ctx context.Context, id uuid.UUID) (int, error) {
	row := q.db.QueryRow(ctx, getIncidentOwner, id)
	var owner_id int
	err := row.Scan(&owner_id)
	return owner_id, err
}

const listIncidentsCount = `-- name: ListIncidentsCount :one
SELECT COUNT(*)
FROM incidents i
WHERE
CASE WHEN $1::TIMESTAMPTZ IS NOT NULL THEN
	i.start_time >= $1 ELSE TRUE END AND
CASE WHEN $2::TIMESTAMPTZ IS NOT NULL THEN
	i.start_time <= $2 ELSE TRUE END AND
(CASE WHEN $3::TEXT IS NOT NULL THEN (
		i.name ILIKE '%' || $3 || '%' OR
		i.description ILIKE '%' || $3 || '%'
	) ELSE TRUE END)
`

func (q *Queries) ListIncidentsCount(ctx context.Context, start *time.Time, end *time.Time, filter *string) (int64, error) {
	row := q.db.QueryRow(ctx, listIncidentsCount, start, end, filter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listIncidentsP = `-- name: ListIncidentsP :many
SELECT
	i.id,
	i.name,
	i.owner_id,
	i.description,
	i.created_at,
	COALESCE(i.start_time, MIN(ic.call_date)) start_time,
	COALESCE(i.end_time, MAX(ic.call_date)) end_time,
	i.location,
	i.metadata,
	u.username owner,
	COUNT(ic.incident_id) calls_count
FROM incidents i
LEFT JOIN incidents_calls ic ON i.id = ic.incident_id
JOIN users u ON i.owner_id = u.id
WHERE
CASE WHEN $1::TIMESTAMPTZ IS NOT NULL THEN
	i.start_time >= $1 ELSE TRUE END AND
CASE WHEN $2::TIMESTAMPTZ IS NOT NULL THEN
	i.start_time <= $2 ELSE TRUE END AND
(CASE WHEN $3::TEXT IS NOT NULL THEN (
		i.name ILIKE '%' || $3 || '%' OR
		i.description ILIKE '%' || $3 || '%'
	) ELSE TRUE END)
GROUP BY i.id, u.username
ORDER BY
CASE WHEN $4::TEXT = 'asc' THEN i.start_time END ASC,
CASE WHEN $4::TEXT = 'desc' THEN i.start_time END DESC
OFFSET $5 ROWS
FETCH NEXT $6 ROWS ONLY
`

type ListIncidentsPParams struct {
	Start     *time.Time `db:"start" json:"start"`
	End       *time.Time `db:"end" json:"end"`
	Filter    *string    `db:"filter" json:"filter"`
	Direction string     `db:"direction" json:"direction"`
	Offset    int32      `db:"offset" json:"offset"`
	PerPage   int32      `db:"per_page" json:"perPage"`
}

type ListIncidentsPRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	OwnerID     int                `db:"owner_id" json:"ownerId"`
	Description *string            `db:"description" json:"description"`
	CreatedAt   *time.Time         `db:"created_at" json:"createdAt"`
	StartTime   *time.Time         `db:"start_time" json:"startTime"`
	EndTime     *time.Time         `db:"end_time" json:"endTime"`
	Location    []byte             `db:"location" json:"location"`
	Metadata    jsontypes.Metadata `db:"metadata" json:"metadata"`
	Owner       string             `db:"owner" json:"owner"`
	CallsCount  int64              `db:"calls_count" json:"callsCount"`
}

func (q *Queries) ListIncidentsP(ctx context.Context, arg ListIncidentsPParams) ([]ListIncidentsPRow, error) {
	rows, err := q.db.Query(ctx, listIncidentsP,
		arg.Start,
		arg.End,
		arg.Filter,
		arg.Direction,
		arg.Offset,
		arg.PerPage,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncidentsPRow
	for rows.Next() {
		var i ListIncidentsPRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.Description,
			&i.CreatedAt,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.Metadata,
			&i.Owner,
			&i.CallsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFromIncident = `-- name: RemoveFromIncident :exec
DELETE FROM incidents_calls ic
WHERE ic.incident_id = $1 AND ic.call_id = ANY($2::UUID[])
`

func (q *Queries) RemoveFromIncident(ctx context.Context, iD uuid.UUID, callIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeFromIncident, iD, callIds)
	return err
}

const updateCallIncidentNotes = `-- name: UpdateCallIncidentNotes :exec
UPDATE incidents_Calls
SET notes = $1
WHERE incident_id = $2 AND call_id = $3
`

func (q *Queries) UpdateCallIncidentNotes(ctx context.Context, notes []byte, incidentID uuid.UUID, callID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateCallIncidentNotes, notes, incidentID, callID)
	return err
}

const updateIncident = `-- name: UpdateIncident :one
UPDATE incidents
SET
	name = COALESCE($1, name),
	description = COALESCE($2, description),
	start_time = COALESCE($3, start_time),
	end_time = COALESCE($4, end_time),
	location = COALESCE($5, location),
	metadata = COALESCE($6, metadata)
WHERE
	id = $7
RETURNING id, name, owner_id, description, created_at, start_time, end_time, location, metadata
`

type UpdateIncidentParams struct {
	Name        *string            `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	StartTime   *time.Time         `db:"start_time" json:"startTime"`
	EndTime     *time.Time         `db:"end_time" json:"endTime"`
	Location    []byte             `db:"location" json:"location"`
	Metadata    jsontypes.Metadata `db:"metadata" json:"metadata"`
	ID          uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncident,
		arg.Name,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.Metadata,
		arg.ID,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Description,
		&i.CreatedAt,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Metadata,
	)
	return i, err
}
