// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"dynatron.me/x/stillbox/internal/jsontypes"
	"dynatron.me/x/stillbox/pkg/alerting/rules"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AudioMIME string

const (
	AudioMIMEAudioMPEG AudioMIME = "audio/mpeg"
	AudioMIMEAudioWAV  AudioMIME = "audio/wav"
)

func (e *AudioMIME) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AudioMIME(s)
	case string:
		*e = AudioMIME(s)
	default:
		return fmt.Errorf("unsupported scan type for AudioMIME: %T", src)
	}
	return nil
}

type NullAudioMIME struct {
	AudioMIME AudioMIME `json:"audioMime,omitempty"`
	Valid     bool      `json:"valid,omitempty"` // Valid is true if AudioMIME is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAudioMIME) Scan(value interface{}) error {
	if value == nil {
		ns.AudioMIME, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AudioMIME.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAudioMIME) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AudioMIME), nil
}

type Alert struct {
	ID        int                `json:"id,omitempty"`
	Time      pgtype.Timestamptz `json:"time,omitempty"`
	TGID      int                `json:"tgid,omitempty"`
	SystemID  int                `json:"systemId,omitempty"`
	Weight    *float32           `json:"weight,omitempty"`
	Score     *float32           `json:"score,omitempty"`
	OrigScore *float32           `json:"origScore,omitempty"`
	Notified  bool               `json:"notified,omitempty"`
	Metadata  []byte             `json:"metadata,omitempty"`
}

type ApiKey struct {
	ID        int              `json:"id,omitempty"`
	Owner     int              `json:"owner,omitempty"`
	Name      *string          `json:"name,omitempty"`
	CreatedAt time.Time        `json:"createdAt,omitempty"`
	Expires   pgtype.Timestamp `json:"expires,omitempty"`
	Disabled  bool             `json:"disabled,omitempty"`
	ApiKey    string           `json:"apiKey,omitempty"`
}

type AudioRefJournal struct {
	ID         int64              `json:"id,omitempty"`
	CallID     pgtype.UUID        `json:"callId,omitempty"`
	Backend    string             `json:"backend,omitempty"`
	Ref        []byte             `json:"ref,omitempty"`
	PruneAfter pgtype.Timestamptz `json:"pruneAfter,omitempty"`
	LastTry    pgtype.Timestamptz `json:"lastTry,omitempty"`
	Tries      int                `json:"tries,omitempty"`
}

type Call struct {
	ID          uuid.UUID          `json:"id,omitempty"`
	Submitter   *int32             `json:"submitter,omitempty"`
	System      int                `json:"system,omitempty"`
	Talkgroup   int                `json:"talkgroup,omitempty"`
	CallDate    pgtype.Timestamptz `json:"callDate,omitempty"`
	AudioName   *string            `json:"audioName,omitempty"`
	AudioBlob   []byte             `json:"audioBlob,omitempty"`
	Duration    *int32             `json:"duration,omitempty"`
	AudioType   NullAudioMIME      `json:"audioType,omitempty"`
	AudioRef    []byte             `json:"audioRef,omitempty"`
	Frequency   int                `json:"frequency,omitempty"`
	Frequencies []int              `json:"frequencies,omitempty"`
	Patches     []int              `json:"patches,omitempty"`
	TalkerAlias *string            `json:"talkerAlias,omitempty"`
	TGLabel     *string            `json:"tgLabel,omitempty"`
	TGAlphaTag  *string            `json:"tgAlphaTag,omitempty"`
	TGGroup     *string            `json:"tgGroup,omitempty"`
	Source      int                `json:"source,omitempty"`
	Transcript  *string            `json:"transcript,omitempty"`
}

type Incident struct {
	ID          uuid.UUID          `json:"id,omitempty"`
	Name        string             `json:"name,omitempty"`
	Owner       int                `json:"owner,omitempty"`
	Description *string            `json:"description,omitempty"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt,omitempty"`
	StartTime   pgtype.Timestamptz `json:"startTime,omitempty"`
	EndTime     pgtype.Timestamptz `json:"endTime,omitempty"`
	Location    []byte             `json:"location,omitempty"`
	Metadata    jsontypes.Metadata `json:"metadata,omitempty"`
}

type IncidentsCall struct {
	IncidentID  uuid.UUID          `json:"incidentId,omitempty"`
	CallID      uuid.UUID          `json:"callId,omitempty"`
	CallsTblID  pgtype.UUID        `json:"callsTblId,omitempty"`
	SweptCallID pgtype.UUID        `json:"sweptCallId,omitempty"`
	CallDate    pgtype.Timestamptz `json:"callDate,omitempty"`
	Notes       []byte             `json:"notes,omitempty"`
}

type Setting struct {
	Name      string `json:"name,omitempty"`
	UpdatedBy *int32 `json:"updatedBy,omitempty"`
	Value     []byte `json:"value,omitempty"`
}

type Share struct {
	ID         string             `json:"id,omitempty"`
	EntityType string             `json:"entityType,omitempty"`
	EntityID   uuid.UUID          `json:"entityId,omitempty"`
	EntityDate pgtype.Timestamptz `json:"entityDate,omitempty"`
	Owner      int                `json:"owner,omitempty"`
	Expiration pgtype.Timestamptz `json:"expiration,omitempty"`
}

type SweptCall struct {
	ID          uuid.UUID          `json:"id,omitempty"`
	Submitter   *int32             `json:"submitter,omitempty"`
	System      int                `json:"system,omitempty"`
	Talkgroup   int                `json:"talkgroup,omitempty"`
	CallDate    pgtype.Timestamptz `json:"callDate,omitempty"`
	AudioName   *string            `json:"audioName,omitempty"`
	AudioBlob   []byte             `json:"audioBlob,omitempty"`
	Duration    *int32             `json:"duration,omitempty"`
	AudioType   NullAudioMIME      `json:"audioType,omitempty"`
	AudioRef    []byte             `json:"audioRef,omitempty"`
	Frequency   int                `json:"frequency,omitempty"`
	Frequencies []int              `json:"frequencies,omitempty"`
	Patches     []int              `json:"patches,omitempty"`
	TalkerAlias *string            `json:"talkerAlias,omitempty"`
	TGLabel     *string            `json:"tgLabel,omitempty"`
	TGAlphaTag  *string            `json:"tgAlphaTag,omitempty"`
	TGGroup     *string            `json:"tgGroup,omitempty"`
	Source      int                `json:"source,omitempty"`
	Transcript  *string            `json:"transcript,omitempty"`
}

type System struct {
	ID      int    `json:"id,omitempty"`
	Name    string `json:"name,omitempty"`
	Learned bool   `json:"learned,omitempty"`
}

type Talkgroup struct {
	ID         int                `json:"id,omitempty"`
	SystemID   int32              `json:"systemId,omitempty"`
	TGID       int32              `json:"tgid,omitempty"`
	Name       *string            `json:"name,omitempty"`
	AlphaTag   *string            `json:"alphaTag,omitempty"`
	TGGroup    *string            `json:"tgGroup,omitempty"`
	Frequency  *int32             `json:"frequency,omitempty"`
	Metadata   jsontypes.Metadata `json:"metadata,omitempty"`
	Tags       []string           `json:"tags,omitempty"`
	Alert      bool               `json:"alert,omitempty"`
	AlertRules rules.AlertRules   `json:"alertRules,omitempty"`
	Weight     float32            `json:"weight,omitempty"`
	Learned    bool               `json:"learned,omitempty"`
	Ignored    bool               `json:"ignored,omitempty"`
}

type TalkgroupVersion struct {
	ID         int                `json:"id,omitempty"`
	Time       pgtype.Timestamptz `json:"time,omitempty"`
	CreatedBy  *int32             `json:"createdBy,omitempty"`
	Deleted    *bool              `json:"deleted,omitempty"`
	SystemID   *int32             `json:"systemId,omitempty"`
	TGID       *int32             `json:"tgid,omitempty"`
	Name       *string            `json:"name,omitempty"`
	AlphaTag   *string            `json:"alphaTag,omitempty"`
	TGGroup    *string            `json:"tgGroup,omitempty"`
	Frequency  *int32             `json:"frequency,omitempty"`
	Metadata   []byte             `json:"metadata,omitempty"`
	Tags       []string           `json:"tags,omitempty"`
	Alert      *bool              `json:"alert,omitempty"`
	AlertRules []byte             `json:"alertRules,omitempty"`
	Weight     *float32           `json:"weight,omitempty"`
	Learned    *bool              `json:"learned,omitempty"`
	Ignored    *bool              `json:"ignored,omitempty"`
}

type User struct {
	ID            int                `json:"id,omitempty"`
	Username      string             `json:"username,omitempty"`
	Password      string             `json:"password,omitempty"`
	Email         string             `json:"email,omitempty"`
	Roles         []string           `json:"roles,omitempty"`
	LastLoginAt   pgtype.Timestamptz `json:"lastLoginAt,omitempty"`
	LastLoginFrom *netip.Addr        `json:"lastLoginFrom,omitempty"`
	PasswordSetAt pgtype.Timestamptz `json:"passwordSetAt,omitempty"`
	Prefs         []byte             `json:"prefs,omitempty"`
}
