// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddAlert(ctx context.Context, arg AddAlertParams) error
	AddCall(ctx context.Context, arg AddCallParams) error
	AddLearnedTalkgroup(ctx context.Context, arg AddLearnedTalkgroupParams) (Talkgroup, error)
	AddToIncident(ctx context.Context, incidentID uuid.UUID, callIds []uuid.UUID, notes [][]byte) error
	CallInIncident(ctx context.Context, incidentID uuid.UUID, callID uuid.UUID) (bool, error)
	CleanupSweptCalls(ctx context.Context, rangeStart pgtype.Timestamptz, rangeEnd pgtype.Timestamptz) (int64, error)
	CreateAPIKey(ctx context.Context, owner int, expires pgtype.Timestamp, disabled *bool) (ApiKey, error)
	CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error)
	CreateShare(ctx context.Context, arg CreateShareParams) error
	CreateSystem(ctx context.Context, iD int, name string) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIKey(ctx context.Context, apiKey string) error
	DeleteCall(ctx context.Context, id uuid.UUID) error
	DeleteIncident(ctx context.Context, id uuid.UUID) error
	DeleteShare(ctx context.Context, id string) error
	DeleteSystem(ctx context.Context, id int) error
	DeleteTalkgroup(ctx context.Context, systemID int32, tGID int32) error
	DeleteUser(ctx context.Context, username string) error
	GetAPIKey(ctx context.Context, apiKey string) (GetAPIKeyRow, error)
	GetAllTalkgroupTags(ctx context.Context) ([]string, error)
	GetAppPrefs(ctx context.Context, appName string, uid int) ([]byte, error)
	GetCall(ctx context.Context, id uuid.UUID) (GetCallRow, error)
	GetCallAudioByID(ctx context.Context, id uuid.UUID) (GetCallAudioByIDRow, error)
	GetCallSubmitter(ctx context.Context, id uuid.UUID) (*int32, error)
	GetDatabaseSize(ctx context.Context) (string, error)
	GetIncident(ctx context.Context, id uuid.UUID) (Incident, error)
	GetIncidentCalls(ctx context.Context, id uuid.UUID) ([]GetIncidentCallsRow, error)
	GetIncidentOwner(ctx context.Context, id uuid.UUID) (int, error)
	GetIncidentTalkgroups(ctx context.Context, incidentID uuid.UUID) ([]GetIncidentTalkgroupsRow, error)
	GetShare(ctx context.Context, id string) (Share, error)
	GetSystemName(ctx context.Context, systemID int) (string, error)
	GetTalkgroup(ctx context.Context, systemID int32, tGID int32) (GetTalkgroupRow, error)
	GetTalkgroupIDsByTags(ctx context.Context, anyTags []string, allTags []string, notTags []string) ([]GetTalkgroupIDsByTagsRow, error)
	GetTalkgroupTags(ctx context.Context, systemID int32, tGID int32) ([]string, error)
	GetTalkgroupWithLearned(ctx context.Context, systemID int32, tGID int32) (GetTalkgroupWithLearnedRow, error)
	GetTalkgroupsWithAllTags(ctx context.Context, tags []string) ([]GetTalkgroupsWithAllTagsRow, error)
	GetTalkgroupsWithAnyTags(ctx context.Context, tags []string) ([]GetTalkgroupsWithAnyTagsRow, error)
	GetTalkgroupsWithLearned(ctx context.Context) ([]GetTalkgroupsWithLearnedRow, error)
	GetTalkgroupsWithLearnedBySystem(ctx context.Context, system int32) ([]GetTalkgroupsWithLearnedBySystemRow, error)
	GetTalkgroupsWithLearnedBySystemCount(ctx context.Context, system int32, filter *string) (int64, error)
	GetTalkgroupsWithLearnedBySystemP(ctx context.Context, arg GetTalkgroupsWithLearnedBySystemPParams) ([]GetTalkgroupsWithLearnedBySystemPRow, error)
	GetTalkgroupsWithLearnedCount(ctx context.Context, filter *string) (int64, error)
	GetTalkgroupsWithLearnedP(ctx context.Context, arg GetTalkgroupsWithLearnedPParams) ([]GetTalkgroupsWithLearnedPRow, error)
	GetUserByID(ctx context.Context, id int) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	ListCallsCount(ctx context.Context, arg ListCallsCountParams) (int64, error)
	ListCallsP(ctx context.Context, arg ListCallsPParams) ([]ListCallsPRow, error)
	ListIncidentsCount(ctx context.Context, start pgtype.Timestamptz, end pgtype.Timestamptz, filter *string) (int64, error)
	ListIncidentsP(ctx context.Context, arg ListIncidentsPParams) ([]ListIncidentsPRow, error)
	PruneShares(ctx context.Context) error
	RemoveFromIncident(ctx context.Context, iD uuid.UUID, callIds []uuid.UUID) error
	RestoreTalkgroupVersion(ctx context.Context, versionIds int) (Talkgroup, error)
	SetAppPrefs(ctx context.Context, appName string, prefs []byte, uid int) error
	SetCallTranscript(ctx context.Context, iD uuid.UUID, transcript *string) error
	SetTalkgroupTags(ctx context.Context, tags []string, systemID int32, tGID int32) error
	StoreDeletedTGVersion(ctx context.Context, systemID *int32, tGID *int32, submitter *int32) error
	StoreTGVersion(ctx context.Context, arg []StoreTGVersionParams) *StoreTGVersionBatchResults
	// This is used to sweep calls that are part of an incident prior to pruning a partition.
	SweepCalls(ctx context.Context, rangeStart pgtype.Timestamptz, rangeEnd pgtype.Timestamptz) (int64, error)
	UpdateCallIncidentNotes(ctx context.Context, notes []byte, incidentID uuid.UUID, callID uuid.UUID) error
	UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (Incident, error)
	UpdatePassword(ctx context.Context, username string, password string) error
	UpdateTalkgroup(ctx context.Context, arg UpdateTalkgroupParams) (Talkgroup, error)
	UpdateUser(ctx context.Context, username string, email *string, isAdmin *bool) (User, error)
	UpsertTalkgroup(ctx context.Context, arg []UpsertTalkgroupParams) *UpsertTalkgroupBatchResults
}

var _ Querier = (*Queries)(nil)
