// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddAlert(ctx context.Context, arg AddAlertParams) error
	AddCall(ctx context.Context, arg AddCallParams) (uuid.UUID, error)
	BulkSetTalkgroupTags(ctx context.Context, iD int64, tags []string) error
	CreateAPIKey(ctx context.Context, owner int, expires pgtype.Timestamp, disabled *bool) (ApiKey, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIKey(ctx context.Context, apiKey string) error
	DeleteUser(ctx context.Context, username string) error
	GetAPIKey(ctx context.Context, apiKey string) (ApiKey, error)
	GetDatabaseSize(ctx context.Context) (string, error)
	GetSystemName(ctx context.Context, systemID int) (string, error)
	GetTalkgroup(ctx context.Context, systemID int, tgid int) (GetTalkgroupRow, error)
	GetTalkgroupIDsByTags(ctx context.Context, anytags []string, alltags []string, nottags []string) ([]GetTalkgroupIDsByTagsRow, error)
	GetTalkgroupTags(ctx context.Context, sys int, tg int) ([]string, error)
	GetTalkgroupWithLearned(ctx context.Context, systemID int, tgid int) (GetTalkgroupWithLearnedRow, error)
	GetTalkgroupWithLearnedByPackedIDs(ctx context.Context, dollar_1 []int64) ([]GetTalkgroupWithLearnedByPackedIDsRow, error)
	GetTalkgroupsByPackedIDs(ctx context.Context, dollar_1 []int64) ([]GetTalkgroupsByPackedIDsRow, error)
	GetTalkgroupsWithAllTags(ctx context.Context, tags []string) ([]GetTalkgroupsWithAllTagsRow, error)
	GetTalkgroupsWithAnyTags(ctx context.Context, tags []string) ([]GetTalkgroupsWithAnyTagsRow, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	SetCallTranscript(ctx context.Context, iD uuid.UUID, transcript *string) error
	SetTalkgroupTags(ctx context.Context, sys int, tg int, tags []string) error
	UpdatePassword(ctx context.Context, username string, password string) error
}

var _ Querier = (*Queries)(nil)
