// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: settings.sql

package database

import (
	"context"
)

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE name = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteSetting, name)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE name = $1
`

func (q *Queries) GetSetting(ctx context.Context, name string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSetting, name)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO settings (name, updated_by, value) VALUES ($1, $2, $3)
	ON CONFLICT (name) DO UPDATE SET
	value = $3,
	updated_by = $2
`

func (q *Queries) SetSetting(ctx context.Context, name string, updatedBy *int32, value []byte) error {
	_, err := q.db.Exec(ctx, setSetting, name, updatedBy, value)
	return err
}
