// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCallStatsByInterval = `-- name: GetCallStatsByInterval :many
SELECT
	COUNT(*),
	date_trunc($1, c.call_date)::TIMESTAMPTZ date
FROM calls c
WHERE
CASE WHEN $2::TIMESTAMPTZ IS NOT NULL THEN
	c.call_date >= $2 ELSE TRUE END AND
CASE WHEN $3::TIMESTAMPTZ IS NOT NULL THEN
	c.call_date < $3 ELSE TRUE END
GROUP BY date
ORDER BY date DESC
`

type GetCallStatsByIntervalRow struct {
	Count int64     `db:"count" json:"count"`
	Date  time.Time `db:"date" json:"date"`
}

func (q *Queries) GetCallStatsByInterval(ctx context.Context, truncField string, start *time.Time, end *time.Time) ([]GetCallStatsByIntervalRow, error) {
	rows, err := q.db.Query(ctx, getCallStatsByInterval, truncField, start, end)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCallStatsByIntervalRow
	for rows.Next() {
		var i GetCallStatsByIntervalRow
		if err := rows.Scan(&i.Count, &i.Date); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCallStatsByTalkgroup = `-- name: GetCallStatsByTalkgroup :many
SELECT
	COUNT(*),
	c.system,
	c.talkgroup,
	date_trunc($1, c.call_date)
FROM calls c
WHERE
CASE WHEN $2::TIMESTAMPTZ IS NOT NULL THEN
	c.call_date >= $2 ELSE TRUE END AND
CASE WHEN $3::TIMESTAMPTZ IS NOT NULL THEN
	c.call_date < $3 ELSE TRUE END
GROUP BY 2, 3, 4
ORDER BY 4 DESC
`

type GetCallStatsByTalkgroupRow struct {
	Count     int64           `db:"count" json:"count"`
	System    int             `db:"system" json:"system"`
	Talkgroup int             `db:"talkgroup" json:"talkgroup"`
	DateTrunc pgtype.Interval `db:"date_trunc" json:"dateTrunc"`
}

func (q *Queries) GetCallStatsByTalkgroup(ctx context.Context, truncField string, start *time.Time, end *time.Time) ([]GetCallStatsByTalkgroupRow, error) {
	rows, err := q.db.Query(ctx, getCallStatsByTalkgroup, truncField, start, end)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCallStatsByTalkgroupRow
	for rows.Next() {
		var i GetCallStatsByTalkgroupRow
		if err := rows.Scan(
			&i.Count,
			&i.System,
			&i.Talkgroup,
			&i.DateTrunc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
