// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys(
	owner_id,
	name,
	kind,
	created_at,
	expires,
	jwt_id,
	scopes,
	disabled,
	api_key
	) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateAPIKeyParams struct {
	OwnerID   int         `db:"owner_id" json:"ownerId"`
	Name      *string     `db:"name" json:"name"`
	Kind      int         `db:"kind" json:"kind"`
	CreatedAt time.Time   `db:"created_at" json:"createdAt"`
	Expires   *time.Time  `db:"expires" json:"expires"`
	JwtID     pgtype.UUID `db:"jwt_id" json:"jwtId"`
	Scopes    []string    `db:"scopes" json:"scopes"`
	Disabled  bool        `db:"disabled" json:"disabled"`
	HashedKey *string     `db:"hashed_key" json:"hashedKey"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey,
		arg.OwnerID,
		arg.Name,
		arg.Kind,
		arg.CreatedAt,
		arg.Expires,
		arg.JwtID,
		arg.Scopes,
		arg.Disabled,
		arg.HashedKey,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
		username,
		password,
		email,
		real_name,
		roles,
		password_set_at
	) VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, username, password, real_name, email, roles, disabled_at, last_login_at, last_login_from, password_set_at, prefs
`

type CreateUserParams struct {
	Username string   `db:"username" json:"username"`
	Password string   `db:"password" json:"password"`
	Email    string   `db:"email" json:"email"`
	RealName *string  `db:"real_name" json:"realName"`
	Roles    []string `db:"roles" json:"roles"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.RealName,
		arg.Roles,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.RealName,
		&i.Email,
		&i.Roles,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.LastLoginFrom,
		&i.PasswordSetAt,
		&i.Prefs,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE api_key = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, apiKey *string) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, apiKey)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE username = $1
`

func (q *Queries) DeleteUser(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, deleteUser, username)
	return err
}

const disableUser = `-- name: DisableUser :exec
UPDATE users SET disabled_at = NOW() WHERE username = $1
`

func (q *Queries) DisableUser(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, disableUser, username)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT
	a.id,
	a.owner_id,
	a.name,
	a.kind,
	a.created_at,
	a.expires,
	a.disabled,
	a.api_key,
	a.jwt_id,
	a.scopes,
	u.username
FROM api_keys a
JOIN users u ON (a.owner_id = u.id)
WHERE 
(CASE
	WHEN $1::TEXT IS NOT NULL THEN a.api_key = $1
	WHEN $2::UUID IS NOT NULL THEN a.jwt_id = $2
	ELSE FALSE END)
AND kind = $3
`

type GetAPIKeyRow struct {
	ID        int         `db:"id" json:"id"`
	OwnerID   int         `db:"owner_id" json:"ownerId"`
	Name      *string     `db:"name" json:"name"`
	Kind      int         `db:"kind" json:"kind"`
	CreatedAt time.Time   `db:"created_at" json:"createdAt"`
	Expires   *time.Time  `db:"expires" json:"expires"`
	Disabled  bool        `db:"disabled" json:"disabled"`
	ApiKey    *string     `db:"api_key" json:"apiKey"`
	JwtID     pgtype.UUID `db:"jwt_id" json:"jwtId"`
	Scopes    []string    `db:"scopes" json:"scopes"`
	Username  string      `db:"username" json:"username"`
}

func (q *Queries) GetAPIKey(ctx context.Context, key *string, jwtID pgtype.UUID, kind int) (GetAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getAPIKey, key, jwtID, kind)
	var i GetAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.Expires,
		&i.Disabled,
		&i.ApiKey,
		&i.JwtID,
		&i.Scopes,
		&i.Username,
	)
	return i, err
}

const getAppPrefs = `-- name: GetAppPrefs :one
SELECT (prefs->>($1::TEXT))::JSONB FROM users WHERE id = $2
`

func (q *Queries) GetAppPrefs(ctx context.Context, appName string, uid int) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAppPrefs, appName, uid)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, real_name, email, roles, disabled_at, last_login_at, last_login_from, password_set_at, prefs FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.RealName,
		&i.Email,
		&i.Roles,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.LastLoginFrom,
		&i.PasswordSetAt,
		&i.Prefs,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, real_name, email, roles, disabled_at, last_login_at, last_login_from, password_set_at, prefs FROM users
WHERE username = $1 AND disabled_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.RealName,
		&i.Email,
		&i.Roles,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.LastLoginFrom,
		&i.PasswordSetAt,
		&i.Prefs,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, password, real_name, email, roles, disabled_at, last_login_at, last_login_from, password_set_at, prefs FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.RealName,
			&i.Email,
			&i.Roles,
			&i.DisabledAt,
			&i.LastLoginAt,
			&i.LastLoginFrom,
			&i.PasswordSetAt,
			&i.Prefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordUserLogin = `-- name: RecordUserLogin :exec
UPDATE users SET
	last_login_at = $2,
	last_login_from = $3
WHERE username = $1
`

func (q *Queries) RecordUserLogin(ctx context.Context, username string, lastLoginAt *time.Time, lastLoginFrom *netip.Addr) error {
	_, err := q.db.Exec(ctx, recordUserLogin, username, lastLoginAt, lastLoginFrom)
	return err
}

const setAppPrefs = `-- name: SetAppPrefs :exec
UPDATE users SET prefs = COALESCE(prefs, '{}'::JSONB) || jsonb_build_object($1::TEXT, $2::JSONB) WHERE id = $3
`

func (q *Queries) SetAppPrefs(ctx context.Context, appName string, prefs []byte, uid int) error {
	_, err := q.db.Exec(ctx, setAppPrefs, appName, prefs, uid)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password = $2, password_set_at = NOW() WHERE username = $1
`

func (q *Queries) UpdatePassword(ctx context.Context, username string, password string) error {
	_, err := q.db.Exec(ctx, updatePassword, username, password)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
	email = COALESCE($2, email),
	real_name = COALESCE($3, real_name),
	roles = COALESCE($4, roles)
WHERE
	username = $1
RETURNING id, username, password, real_name, email, roles, disabled_at, last_login_at, last_login_from, password_set_at, prefs
`

type UpdateUserParams struct {
	Username string   `db:"username" json:"username"`
	Email    *string  `db:"email" json:"email"`
	RealName *string  `db:"real_name" json:"realName"`
	Roles    []string `db:"roles" json:"roles"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.RealName,
		arg.Roles,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.RealName,
		&i.Email,
		&i.Roles,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.LastLoginFrom,
		&i.PasswordSetAt,
		&i.Prefs,
	)
	return i, err
}
