// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys(
	owner,
	created_at,
	expires,
	disabled,
	api_key
	) VALUES ($1, NOW(), $2, $3, gen_random_uuid())
RETURNING id, owner, created_at, expires, disabled, api_key
`

func (q *Queries) CreateAPIKey(ctx context.Context, owner int, expires pgtype.Timestamp, disabled *bool) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey, owner, expires, disabled)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.CreatedAt,
		&i.Expires,
		&i.Disabled,
		&i.ApiKey,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
		username,
		password,
		email,
		is_admin,
		password_set_at
	) VALUES ($1, $2, $3, $4, NOW())
RETURNING id, username, password, email, is_admin, last_login_at, last_login_from, password_set_at, prefs
`

type CreateUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	IsAdmin  bool   `json:"isAdmin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.IsAdmin,
		&i.LastLoginAt,
		&i.LastLoginFrom,
		&i.PasswordSetAt,
		&i.Prefs,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE api_key = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, apiKey string) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, apiKey)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE username = $1
`

func (q *Queries) DeleteUser(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, deleteUser, username)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT
	a.id,
	a.owner,
	a.created_at,
	a.expires,
	a.disabled,
	a.api_key,
	u.username
FROM api_keys a
JOIN users u ON (a.owner = u.id)
WHERE api_key = $1
`

type GetAPIKeyRow struct {
	ID        int              `json:"id"`
	Owner     int              `json:"owner"`
	CreatedAt time.Time        `json:"createdAt"`
	Expires   pgtype.Timestamp `json:"expires"`
	Disabled  *bool            `json:"disabled"`
	ApiKey    string           `json:"apiKey"`
	Username  string           `json:"username"`
}

func (q *Queries) GetAPIKey(ctx context.Context, apiKey string) (GetAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getAPIKey, apiKey)
	var i GetAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.CreatedAt,
		&i.Expires,
		&i.Disabled,
		&i.ApiKey,
		&i.Username,
	)
	return i, err
}

const getAppPrefs = `-- name: GetAppPrefs :one
SELECT (prefs->>($1::TEXT))::JSONB FROM users WHERE id = $2
`

func (q *Queries) GetAppPrefs(ctx context.Context, appName string, uid int) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAppPrefs, appName, uid)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, email, is_admin, last_login_at, last_login_from, password_set_at, prefs FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.IsAdmin,
		&i.LastLoginAt,
		&i.LastLoginFrom,
		&i.PasswordSetAt,
		&i.Prefs,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, email, is_admin, last_login_at, last_login_from, password_set_at, prefs FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.IsAdmin,
		&i.LastLoginAt,
		&i.LastLoginFrom,
		&i.PasswordSetAt,
		&i.Prefs,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, password, email, is_admin, last_login_at, last_login_from, password_set_at, prefs FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.Email,
			&i.IsAdmin,
			&i.LastLoginAt,
			&i.LastLoginFrom,
			&i.PasswordSetAt,
			&i.Prefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordUserLogin = `-- name: RecordUserLogin :exec
UPDATE users SET
	last_login_at = $2,
	last_login_from = $3
WHERE username = $1
`

func (q *Queries) RecordUserLogin(ctx context.Context, username string, lastLoginAt pgtype.Timestamptz, lastLoginFrom *netip.Addr) error {
	_, err := q.db.Exec(ctx, recordUserLogin, username, lastLoginAt, lastLoginFrom)
	return err
}

const setAppPrefs = `-- name: SetAppPrefs :exec
UPDATE users SET prefs = COALESCE(prefs, '{}'::JSONB) || jsonb_build_object($1::TEXT, $2::JSONB) WHERE id = $3
`

func (q *Queries) SetAppPrefs(ctx context.Context, appName string, prefs []byte, uid int) error {
	_, err := q.db.Exec(ctx, setAppPrefs, appName, prefs, uid)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password = $2, password_set_at = NOW() WHERE username = $1
`

func (q *Queries) UpdatePassword(ctx context.Context, username string, password string) error {
	_, err := q.db.Exec(ctx, updatePassword, username, password)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
	email = COALESCE($2, email),
	is_admin = COALESCE($3, is_admin)
WHERE
	username = $1
RETURNING id, username, password, email, is_admin, last_login_at, last_login_from, password_set_at, prefs
`

func (q *Queries) UpdateUser(ctx context.Context, username string, email *string, isAdmin *bool) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, username, email, isAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.IsAdmin,
		&i.LastLoginAt,
		&i.LastLoginFrom,
		&i.PasswordSetAt,
		&i.Prefs,
	)
	return i, err
}
