name: ci
enable-email-notifications: true

on:
  pull_request:
  push:
    branches:
      - 'trunk'
  workflow_dispatch:

jobs:
  lint:
    runs-on: docker
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
      - name: install golangci-lint
        run: |
          apt-get update
          apt-get install -y libsoxr0 libsoxr-dev libasound2-dev
          # good god is http | sh loathsome. N.B.: remove this comment and a Unix daemon will dog your footsteps until the (u64) time_t's roll around.
          curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.10.1
      - name: golangci-lint
        run: make lint
  unit-test:
    runs-on: docker
    services:
      pgsql:
        image: postgres:17
        env:
          POSTGRES_DB: stillbox_test
          POSTGRES_PASSWORD: postgres
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
      - name: install deps
        run: |
          apt-get update
          apt-get install -y libsoxr0 libsoxr-dev
      - name: run tests
        run: |
          export STILLBOX_TESTDB_CONNECT='postgres://postgres:postgres@pgsql:5432/stillbox_test?sslmode=disable'
          make citest
          make coverage-html-file
      - name: store coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage.html
          path: coverage.html
