// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"dynatron.me/x/stillbox/pkg/authz"
	"dynatron.me/x/stillbox/pkg/authz/entities"
	"github.com/el-mike/restrict/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewRBAC creates a new instance of RBAC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRBAC(t interface {
	mock.TestingT
	Cleanup(func())
}) *RBAC {
	mock := &RBAC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RBAC is an autogenerated mock type for the RBAC type
type RBAC struct {
	mock.Mock
}

type RBAC_Expecter struct {
	mock *mock.Mock
}

func (_m *RBAC) EXPECT() *RBAC_Expecter {
	return &RBAC_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type RBAC
func (_mock *RBAC) Check(ctx context.Context, res restrict.Resource, opts ...authz.CheckOption) (entities.Subject, error) {
	// authz.CheckOption
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, res)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 entities.Subject
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, restrict.Resource, ...authz.CheckOption) (entities.Subject, error)); ok {
		return returnFunc(ctx, res, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, restrict.Resource, ...authz.CheckOption) entities.Subject); ok {
		r0 = returnFunc(ctx, res, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Subject)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, restrict.Resource, ...authz.CheckOption) error); ok {
		r1 = returnFunc(ctx, res, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RBAC_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type RBAC_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
//   - res restrict.Resource
//   - opts ...authz.CheckOption
func (_e *RBAC_Expecter) Check(ctx any, res any, opts ...any) *RBAC_Check_Call {
	return &RBAC_Check_Call{Call: _e.mock.On("Check",
		append([]any{ctx, res}, opts...)...)}
}

func (_c *RBAC_Check_Call) Run(run func(ctx context.Context, res restrict.Resource, opts ...authz.CheckOption)) *RBAC_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 restrict.Resource
		if args[1] != nil {
			arg1 = args[1].(restrict.Resource)
		}
		var arg2 []authz.CheckOption
		variadicArgs := make([]authz.CheckOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(authz.CheckOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RBAC_Check_Call) Return(subject entities.Subject, err error) *RBAC_Check_Call {
	_c.Call.Return(subject, err)
	return _c
}

func (_c *RBAC_Check_Call) RunAndReturn(run func(ctx context.Context, res restrict.Resource, opts ...authz.CheckOption) (entities.Subject, error)) *RBAC_Check_Call {
	_c.Call.Return(run)
	return _c
}
