{
 "title": "StillboxAPM",
 "description": "Stillbox performance monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prom_job_name", "label": "Prometheus Job Name", "query": { "query": "label_values(up, job)" } }
  ]
 },
 "panels": [
  {
   "title": "Calls ingested",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(stillbox_pipeline_ingested_calls_count{job=\"$prom_job_name\"}[$__rate_interval])*60",
     "legendFormat": "$prom_job_name calls per min"
    },
    {
     "expr": "rate(stillbox_pipeline_filtered_calls_count{job=\"$prom_job_name\"}[$__rate_interval])*60",
     "legendFormat": "$prom_job_name filtered calls per min"
    },
    {
     "expr": "rate(stillbox_callstore_ingest_error_count{job=\"$prom_job_name\"}[$__rate_interval])*60",
     "legendFormat": "$prom_job_name store call errors per min"
    }
   ]
  },
  {
   "title": "Transcription Dispatches",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(stillbox_workers_dispatch_count{job=\"$prom_job_name\"}[$__rate_interval])*60",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(stillbox_http_request_duration_ms_count{job=\"$prom_job_name\"}[$__rate_interval])*60",
     "legendFormat": "total requests"
    },
    {
     "expr": "sort_desc(sum by (code, method) (rate(stillbox_http_requests_count{job=\"$prom_job_name\"}[$__rate_interval])))*60",
     "legendFormat": "{{code}} {{method}}"
    },
    {
     "expr": "stillbox_nexus_active_ws_connection_count{job=\"$prom_job_name\"}",
     "legendFormat": "active nexus ws conns"
    }
   ]
  },
  {
   "title": "Transcribe duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(stillbox_transcribe_elapsed_seconds_bucket{job=\"$prom_job_name\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Go Memory Allocations (should not grow unboundedly)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job='$prom_job_name'}"
    }
   ]
  },
  {
   "title": "Auth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(stillbox_authn_successful_login_count{job=\"$prom_job_name\"}[$__rate_interval])",
     "legendFormat": "successful logins"
    },
    {
     "expr": "rate(stillbox_authn_failed_login_count{job=\"$prom_job_name\"}[$__rate_interval])",
     "legendFormat": "failed logins"
    },
    {
     "expr": "rate(stillbox_authn_token_refresh_count{job=\"$prom_job_name\"}[$__rate_interval])",
     "legendFormat": "token refreshes"
    },
    {
     "expr": "rate(stillbox_authn_failed_token_refresh_count{job=\"$prom_job_name\"}[$__rate_interval])",
     "legendFormat": "failed token refreshes"
    }
   ]
  },
  {
   "title": "Relayed Calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(stillbox_relay_relayed_success_count{job=\"$prom_job_name\"}[$__rate_interval])",
     "legendFormat": "OK {{url}}"
    },
    {
     "expr": "rate(stillbox_relay_relayed_failed_count{job=\"$prom_job_name\"}[$__rate_interval])",
     "legendFormat": "FAIL {{url}}"
    }
   ]
  },
  {
   "title": "request duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(stillbox_http_request_duration_seconds_bucket{job=\"$prom_job_name\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "number of goroutines (should not grow unboundedly)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job='$prom_job_name'}"
    }
   ]
  },
  {
   "title": "Audio Storage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(stillbox_callaudio_stored_total{job=\"$prom_job_name\"}[$__rate_interval])*60",
     "legendFormat": "$prom_job_name calls per min"
    },
    {
     "expr": "rate(stillbox_callaudio_failed_store_count{job=\"$prom_job_name\"}[$__rate_interval])*60",
     "legendFormat": "$prom_job_name filtered calls per min"
    },
    {
     "expr": "stillbox_callaudio_journal_size",
     "legendFormat": "journal {{backend}} {{kind}}"
    },
    {
     "expr": "stillbox_callaudio_journal_gc_error_count",
     "legendFormat": "journal errors {{backend}} {{kind}}"
    }
   ]
  },
  {
   "title": "Memory Allocated by the Go runtime from the OS (should not grow unboundedly)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job='$prom_job_name'}"
    }
   ]
  },
  {
   "title": "Talkgroup Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "increase(stillbox_tgstore_cache_hit_count{job=\"$prom_job_name\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(stillbox_tgstore_cache_miss_count{job=\"$prom_job_name\"}[$__rate_interval])",
     "legendFormat": "misses"
    }
   ]
  }
 ]
}