// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"dynatron.me/x/stillbox/pkg/calls"
	"dynatron.me/x/stillbox/pkg/config"
	"dynatron.me/x/stillbox/pkg/database"
	"dynatron.me/x/stillbox/pkg/talkgroups"
	"dynatron.me/x/stillbox/pkg/talkgroups/tgstore"
	mock "github.com/stretchr/testify/mock"
)

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// CreateSystem provides a mock function for the type Store
func (_mock *Store) CreateSystem(ctx context.Context, id int, name string, learned bool) error {
	ret := _mock.Called(ctx, id, name, learned)

	if len(ret) == 0 {
		panic("no return value specified for CreateSystem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, bool) error); ok {
		r0 = returnFunc(ctx, id, name, learned)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Store_CreateSystem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSystem'
type Store_CreateSystem_Call struct {
	*mock.Call
}

// CreateSystem is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - name string
//   - learned bool
func (_e *Store_Expecter) CreateSystem(ctx interface{}, id interface{}, name interface{}, learned interface{}) *Store_CreateSystem_Call {
	return &Store_CreateSystem_Call{Call: _e.mock.On("CreateSystem", ctx, id, name, learned)}
}

func (_c *Store_CreateSystem_Call) Run(run func(ctx context.Context, id int, name string, learned bool)) *Store_CreateSystem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Store_CreateSystem_Call) Return(err error) *Store_CreateSystem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Store_CreateSystem_Call) RunAndReturn(run func(ctx context.Context, id int, name string, learned bool) error) *Store_CreateSystem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSystem provides a mock function for the type Store
func (_mock *Store) DeleteSystem(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSystem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Store_DeleteSystem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSystem'
type Store_DeleteSystem_Call struct {
	*mock.Call
}

// DeleteSystem is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *Store_Expecter) DeleteSystem(ctx interface{}, id interface{}) *Store_DeleteSystem_Call {
	return &Store_DeleteSystem_Call{Call: _e.mock.On("DeleteSystem", ctx, id)}
}

func (_c *Store_DeleteSystem_Call) Run(run func(ctx context.Context, id int)) *Store_DeleteSystem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_DeleteSystem_Call) Return(err error) *Store_DeleteSystem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Store_DeleteSystem_Call) RunAndReturn(run func(ctx context.Context, id int) error) *Store_DeleteSystem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTG provides a mock function for the type Store
func (_mock *Store) DeleteTG(ctx context.Context, id talkgroups.ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTG")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, talkgroups.ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Store_DeleteTG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTG'
type Store_DeleteTG_Call struct {
	*mock.Call
}

// DeleteTG is a helper method to define mock.On call
//   - ctx context.Context
//   - id talkgroups.ID
func (_e *Store_Expecter) DeleteTG(ctx interface{}, id interface{}) *Store_DeleteTG_Call {
	return &Store_DeleteTG_Call{Call: _e.mock.On("DeleteTG", ctx, id)}
}

func (_c *Store_DeleteTG_Call) Run(run func(ctx context.Context, id talkgroups.ID)) *Store_DeleteTG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 talkgroups.ID
		if args[1] != nil {
			arg1 = args[1].(talkgroups.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_DeleteTG_Call) Return(err error) *Store_DeleteTG_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Store_DeleteTG_Call) RunAndReturn(run func(ctx context.Context, id talkgroups.ID) error) *Store_DeleteTG_Call {
	_c.Call.Return(run)
	return _c
}

// HUP provides a mock function for the type Store
func (_mock *Store) HUP(config1 *config.Config) {
	_mock.Called(config1)
	return
}

// Store_HUP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HUP'
type Store_HUP_Call struct {
	*mock.Call
}

// HUP is a helper method to define mock.On call
//   - config1 *config.Config
func (_e *Store_Expecter) HUP(config1 interface{}) *Store_HUP_Call {
	return &Store_HUP_Call{Call: _e.mock.On("HUP", config1)}
}

func (_c *Store_HUP_Call) Run(run func(config1 *config.Config)) *Store_HUP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *config.Config
		if args[0] != nil {
			arg0 = args[0].(*config.Config)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Store_HUP_Call) Return() *Store_HUP_Call {
	_c.Call.Return()
	return _c
}

func (_c *Store_HUP_Call) RunAndReturn(run func(config1 *config.Config)) *Store_HUP_Call {
	_c.Run(run)
	return _c
}

// Hint provides a mock function for the type Store
func (_mock *Store) Hint(ctx context.Context, tgs []talkgroups.ID) error {
	ret := _mock.Called(ctx, tgs)

	if len(ret) == 0 {
		panic("no return value specified for Hint")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []talkgroups.ID) error); ok {
		r0 = returnFunc(ctx, tgs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Store_Hint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hint'
type Store_Hint_Call struct {
	*mock.Call
}

// Hint is a helper method to define mock.On call
//   - ctx context.Context
//   - tgs []talkgroups.ID
func (_e *Store_Expecter) Hint(ctx interface{}, tgs interface{}) *Store_Hint_Call {
	return &Store_Hint_Call{Call: _e.mock.On("Hint", ctx, tgs)}
}

func (_c *Store_Hint_Call) Run(run func(ctx context.Context, tgs []talkgroups.ID)) *Store_Hint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []talkgroups.ID
		if args[1] != nil {
			arg1 = args[1].([]talkgroups.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_Hint_Call) Return(err error) *Store_Hint_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Store_Hint_Call) RunAndReturn(run func(ctx context.Context, tgs []talkgroups.ID) error) *Store_Hint_Call {
	_c.Call.Return(run)
	return _c
}

// Invalidate provides a mock function for the type Store
func (_mock *Store) Invalidate() {
	_mock.Called()
	return
}

// Store_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type Store_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
func (_e *Store_Expecter) Invalidate() *Store_Invalidate_Call {
	return &Store_Invalidate_Call{Call: _e.mock.On("Invalidate")}
}

func (_c *Store_Invalidate_Call) Run(run func()) *Store_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Store_Invalidate_Call) Return() *Store_Invalidate_Call {
	_c.Call.Return()
	return _c
}

func (_c *Store_Invalidate_Call) RunAndReturn(run func()) *Store_Invalidate_Call {
	_c.Run(run)
	return _c
}

// LearnSystem provides a mock function for the type Store
func (_mock *Store) LearnSystem(ctx context.Context, call *calls.Call) error {
	ret := _mock.Called(ctx, call)

	if len(ret) == 0 {
		panic("no return value specified for LearnSystem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *calls.Call) error); ok {
		r0 = returnFunc(ctx, call)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Store_LearnSystem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LearnSystem'
type Store_LearnSystem_Call struct {
	*mock.Call
}

// LearnSystem is a helper method to define mock.On call
//   - ctx context.Context
//   - call *calls.Call
func (_e *Store_Expecter) LearnSystem(ctx interface{}, call interface{}) *Store_LearnSystem_Call {
	return &Store_LearnSystem_Call{Call: _e.mock.On("LearnSystem", ctx, call)}
}

func (_c *Store_LearnSystem_Call) Run(run func(ctx context.Context, call *calls.Call)) *Store_LearnSystem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *calls.Call
		if args[1] != nil {
			arg1 = args[1].(*calls.Call)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_LearnSystem_Call) Return(err error) *Store_LearnSystem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Store_LearnSystem_Call) RunAndReturn(run func(ctx context.Context, call *calls.Call) error) *Store_LearnSystem_Call {
	_c.Call.Return(run)
	return _c
}

// LearnTG provides a mock function for the type Store
func (_mock *Store) LearnTG(ctx context.Context, call *calls.Call) (*talkgroups.Talkgroup, error) {
	ret := _mock.Called(ctx, call)

	if len(ret) == 0 {
		panic("no return value specified for LearnTG")
	}

	var r0 *talkgroups.Talkgroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *calls.Call) (*talkgroups.Talkgroup, error)); ok {
		return returnFunc(ctx, call)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *calls.Call) *talkgroups.Talkgroup); ok {
		r0 = returnFunc(ctx, call)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*talkgroups.Talkgroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *calls.Call) error); ok {
		r1 = returnFunc(ctx, call)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_LearnTG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LearnTG'
type Store_LearnTG_Call struct {
	*mock.Call
}

// LearnTG is a helper method to define mock.On call
//   - ctx context.Context
//   - call *calls.Call
func (_e *Store_Expecter) LearnTG(ctx interface{}, call interface{}) *Store_LearnTG_Call {
	return &Store_LearnTG_Call{Call: _e.mock.On("LearnTG", ctx, call)}
}

func (_c *Store_LearnTG_Call) Run(run func(ctx context.Context, call *calls.Call)) *Store_LearnTG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *calls.Call
		if args[1] != nil {
			arg1 = args[1].(*calls.Call)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_LearnTG_Call) Return(talkgroup *talkgroups.Talkgroup, err error) *Store_LearnTG_Call {
	_c.Call.Return(talkgroup, err)
	return _c
}

func (_c *Store_LearnTG_Call) RunAndReturn(run func(ctx context.Context, call *calls.Call) (*talkgroups.Talkgroup, error)) *Store_LearnTG_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type Store
func (_mock *Store) Load(ctx context.Context, tgs database.TGTuplesU) error {
	ret := _mock.Called(ctx, tgs)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.TGTuplesU) error); ok {
		r0 = returnFunc(ctx, tgs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Store_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Store_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - tgs database.TGTuplesU
func (_e *Store_Expecter) Load(ctx interface{}, tgs interface{}) *Store_Load_Call {
	return &Store_Load_Call{Call: _e.mock.On("Load", ctx, tgs)}
}

func (_c *Store_Load_Call) Run(run func(ctx context.Context, tgs database.TGTuplesU)) *Store_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.TGTuplesU
		if args[1] != nil {
			arg1 = args[1].(database.TGTuplesU)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_Load_Call) Return(err error) *Store_Load_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Store_Load_Call) RunAndReturn(run func(ctx context.Context, tgs database.TGTuplesU) error) *Store_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Metrics provides a mock function for the type Store
func (_mock *Store) Metrics() *tgstore.TGStoreMetrics {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metrics")
	}

	var r0 *tgstore.TGStoreMetrics
	if returnFunc, ok := ret.Get(0).(func() *tgstore.TGStoreMetrics); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tgstore.TGStoreMetrics)
		}
	}
	return r0
}

// Store_Metrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metrics'
type Store_Metrics_Call struct {
	*mock.Call
}

// Metrics is a helper method to define mock.On call
func (_e *Store_Expecter) Metrics() *Store_Metrics_Call {
	return &Store_Metrics_Call{Call: _e.mock.On("Metrics")}
}

func (_c *Store_Metrics_Call) Run(run func()) *Store_Metrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Store_Metrics_Call) Return(tGStoreMetrics *tgstore.TGStoreMetrics) *Store_Metrics_Call {
	_c.Call.Return(tGStoreMetrics)
	return _c
}

func (_c *Store_Metrics_Call) RunAndReturn(run func() *tgstore.TGStoreMetrics) *Store_Metrics_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterFilter provides a mock function for the type Store
func (_mock *Store) RegisterFilter(filter tgstore.Filter) {
	_mock.Called(filter)
	return
}

// Store_RegisterFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterFilter'
type Store_RegisterFilter_Call struct {
	*mock.Call
}

// RegisterFilter is a helper method to define mock.On call
//   - filter tgstore.Filter
func (_e *Store_Expecter) RegisterFilter(filter interface{}) *Store_RegisterFilter_Call {
	return &Store_RegisterFilter_Call{Call: _e.mock.On("RegisterFilter", filter)}
}

func (_c *Store_RegisterFilter_Call) Run(run func(filter tgstore.Filter)) *Store_RegisterFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tgstore.Filter
		if args[0] != nil {
			arg0 = args[0].(tgstore.Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Store_RegisterFilter_Call) Return() *Store_RegisterFilter_Call {
	_c.Call.Return()
	return _c
}

func (_c *Store_RegisterFilter_Call) RunAndReturn(run func(filter tgstore.Filter)) *Store_RegisterFilter_Call {
	_c.Run(run)
	return _c
}

// SystemName provides a mock function for the type Store
func (_mock *Store) SystemName(ctx context.Context, id int) (string, bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SystemName")
	}

	var r0 string
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (string, bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) bool); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Store_SystemName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SystemName'
type Store_SystemName_Call struct {
	*mock.Call
}

// SystemName is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *Store_Expecter) SystemName(ctx interface{}, id interface{}) *Store_SystemName_Call {
	return &Store_SystemName_Call{Call: _e.mock.On("SystemName", ctx, id)}
}

func (_c *Store_SystemName_Call) Run(run func(ctx context.Context, id int)) *Store_SystemName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_SystemName_Call) Return(s string, b bool, err error) *Store_SystemName_Call {
	_c.Call.Return(s, b, err)
	return _c
}

func (_c *Store_SystemName_Call) RunAndReturn(run func(ctx context.Context, id int) (string, bool, error)) *Store_SystemName_Call {
	_c.Call.Return(run)
	return _c
}

// SystemTGs provides a mock function for the type Store
func (_mock *Store) SystemTGs(ctx context.Context, systemID int, opts ...tgstore.Option) ([]*talkgroups.Talkgroup, error) {
	// tgstore.Option
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, systemID)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SystemTGs")
	}

	var r0 []*talkgroups.Talkgroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...tgstore.Option) ([]*talkgroups.Talkgroup, error)); ok {
		return returnFunc(ctx, systemID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...tgstore.Option) []*talkgroups.Talkgroup); ok {
		r0 = returnFunc(ctx, systemID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*talkgroups.Talkgroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, ...tgstore.Option) error); ok {
		r1 = returnFunc(ctx, systemID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_SystemTGs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SystemTGs'
type Store_SystemTGs_Call struct {
	*mock.Call
}

// SystemTGs is a helper method to define mock.On call
//   - ctx context.Context
//   - systemID int
//   - opts ...tgstore.Option
func (_e *Store_Expecter) SystemTGs(ctx interface{}, systemID interface{}, opts ...interface{}) *Store_SystemTGs_Call {
	return &Store_SystemTGs_Call{Call: _e.mock.On("SystemTGs",
		append([]interface{}{ctx, systemID}, opts...)...)}
}

func (_c *Store_SystemTGs_Call) Run(run func(ctx context.Context, systemID int, opts ...tgstore.Option)) *Store_SystemTGs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []tgstore.Option
		variadicArgs := make([]tgstore.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(tgstore.Option)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Store_SystemTGs_Call) Return(talkgroups1 []*talkgroups.Talkgroup, err error) *Store_SystemTGs_Call {
	_c.Call.Return(talkgroups1, err)
	return _c
}

func (_c *Store_SystemTGs_Call) RunAndReturn(run func(ctx context.Context, systemID int, opts ...tgstore.Option) ([]*talkgroups.Talkgroup, error)) *Store_SystemTGs_Call {
	_c.Call.Return(run)
	return _c
}

// TG provides a mock function for the type Store
func (_mock *Store) TG(ctx context.Context, tg talkgroups.ID) (*talkgroups.Talkgroup, error) {
	ret := _mock.Called(ctx, tg)

	if len(ret) == 0 {
		panic("no return value specified for TG")
	}

	var r0 *talkgroups.Talkgroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, talkgroups.ID) (*talkgroups.Talkgroup, error)); ok {
		return returnFunc(ctx, tg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, talkgroups.ID) *talkgroups.Talkgroup); ok {
		r0 = returnFunc(ctx, tg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*talkgroups.Talkgroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, talkgroups.ID) error); ok {
		r1 = returnFunc(ctx, tg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_TG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TG'
type Store_TG_Call struct {
	*mock.Call
}

// TG is a helper method to define mock.On call
//   - ctx context.Context
//   - tg talkgroups.ID
func (_e *Store_Expecter) TG(ctx interface{}, tg interface{}) *Store_TG_Call {
	return &Store_TG_Call{Call: _e.mock.On("TG", ctx, tg)}
}

func (_c *Store_TG_Call) Run(run func(ctx context.Context, tg talkgroups.ID)) *Store_TG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 talkgroups.ID
		if args[1] != nil {
			arg1 = args[1].(talkgroups.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_TG_Call) Return(talkgroup *talkgroups.Talkgroup, err error) *Store_TG_Call {
	_c.Call.Return(talkgroup, err)
	return _c
}

func (_c *Store_TG_Call) RunAndReturn(run func(ctx context.Context, tg talkgroups.ID) (*talkgroups.Talkgroup, error)) *Store_TG_Call {
	_c.Call.Return(run)
	return _c
}

// TGs provides a mock function for the type Store
func (_mock *Store) TGs(ctx context.Context, tgs talkgroups.IDs, opts ...tgstore.Option) ([]*talkgroups.Talkgroup, error) {
	// tgstore.Option
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, tgs)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for TGs")
	}

	var r0 []*talkgroups.Talkgroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, talkgroups.IDs, ...tgstore.Option) ([]*talkgroups.Talkgroup, error)); ok {
		return returnFunc(ctx, tgs, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, talkgroups.IDs, ...tgstore.Option) []*talkgroups.Talkgroup); ok {
		r0 = returnFunc(ctx, tgs, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*talkgroups.Talkgroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, talkgroups.IDs, ...tgstore.Option) error); ok {
		r1 = returnFunc(ctx, tgs, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_TGs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TGs'
type Store_TGs_Call struct {
	*mock.Call
}

// TGs is a helper method to define mock.On call
//   - ctx context.Context
//   - tgs talkgroups.IDs
//   - opts ...tgstore.Option
func (_e *Store_Expecter) TGs(ctx interface{}, tgs interface{}, opts ...interface{}) *Store_TGs_Call {
	return &Store_TGs_Call{Call: _e.mock.On("TGs",
		append([]interface{}{ctx, tgs}, opts...)...)}
}

func (_c *Store_TGs_Call) Run(run func(ctx context.Context, tgs talkgroups.IDs, opts ...tgstore.Option)) *Store_TGs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 talkgroups.IDs
		if args[1] != nil {
			arg1 = args[1].(talkgroups.IDs)
		}
		var arg2 []tgstore.Option
		variadicArgs := make([]tgstore.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(tgstore.Option)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Store_TGs_Call) Return(talkgroups1 []*talkgroups.Talkgroup, err error) *Store_TGs_Call {
	_c.Call.Return(talkgroups1, err)
	return _c
}

func (_c *Store_TGs_Call) RunAndReturn(run func(ctx context.Context, tgs talkgroups.IDs, opts ...tgstore.Option) ([]*talkgroups.Talkgroup, error)) *Store_TGs_Call {
	_c.Call.Return(run)
	return _c
}

// TGsByTags provides a mock function for the type Store
func (_mock *Store) TGsByTags(ctx context.Context, tagsAll []string, tagsAny []string, tagsNot []string) (talkgroups.IDs, error) {
	ret := _mock.Called(ctx, tagsAll, tagsAny, tagsNot)

	if len(ret) == 0 {
		panic("no return value specified for TGsByTags")
	}

	var r0 talkgroups.IDs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []string, []string) (talkgroups.IDs, error)); ok {
		return returnFunc(ctx, tagsAll, tagsAny, tagsNot)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []string, []string) talkgroups.IDs); ok {
		r0 = returnFunc(ctx, tagsAll, tagsAny, tagsNot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(talkgroups.IDs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, []string, []string) error); ok {
		r1 = returnFunc(ctx, tagsAll, tagsAny, tagsNot)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_TGsByTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TGsByTags'
type Store_TGsByTags_Call struct {
	*mock.Call
}

// TGsByTags is a helper method to define mock.On call
//   - ctx context.Context
//   - tagsAll []string
//   - tagsAny []string
//   - tagsNot []string
func (_e *Store_Expecter) TGsByTags(ctx interface{}, tagsAll interface{}, tagsAny interface{}, tagsNot interface{}) *Store_TGsByTags_Call {
	return &Store_TGsByTags_Call{Call: _e.mock.On("TGsByTags", ctx, tagsAll, tagsAny, tagsNot)}
}

func (_c *Store_TGsByTags_Call) Run(run func(ctx context.Context, tagsAll []string, tagsAny []string, tagsNot []string)) *Store_TGsByTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Store_TGsByTags_Call) Return(iDs talkgroups.IDs, err error) *Store_TGsByTags_Call {
	_c.Call.Return(iDs, err)
	return _c
}

func (_c *Store_TGsByTags_Call) RunAndReturn(run func(ctx context.Context, tagsAll []string, tagsAny []string, tagsNot []string) (talkgroups.IDs, error)) *Store_TGsByTags_Call {
	_c.Call.Return(run)
	return _c
}

// Tags provides a mock function for the type Store
func (_mock *Store) Tags(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Tags")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_Tags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tags'
type Store_Tags_Call struct {
	*mock.Call
}

// Tags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Store_Expecter) Tags(ctx interface{}) *Store_Tags_Call {
	return &Store_Tags_Call{Call: _e.mock.On("Tags", ctx)}
}

func (_c *Store_Tags_Call) Run(run func(ctx context.Context)) *Store_Tags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Store_Tags_Call) Return(strings []string, err error) *Store_Tags_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Store_Tags_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *Store_Tags_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterFilter provides a mock function for the type Store
func (_mock *Store) UnregisterFilter(filter tgstore.Filter) {
	_mock.Called(filter)
	return
}

// Store_UnregisterFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterFilter'
type Store_UnregisterFilter_Call struct {
	*mock.Call
}

// UnregisterFilter is a helper method to define mock.On call
//   - filter tgstore.Filter
func (_e *Store_Expecter) UnregisterFilter(filter interface{}) *Store_UnregisterFilter_Call {
	return &Store_UnregisterFilter_Call{Call: _e.mock.On("UnregisterFilter", filter)}
}

func (_c *Store_UnregisterFilter_Call) Run(run func(filter tgstore.Filter)) *Store_UnregisterFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tgstore.Filter
		if args[0] != nil {
			arg0 = args[0].(tgstore.Filter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Store_UnregisterFilter_Call) Return() *Store_UnregisterFilter_Call {
	_c.Call.Return()
	return _c
}

func (_c *Store_UnregisterFilter_Call) RunAndReturn(run func(filter tgstore.Filter)) *Store_UnregisterFilter_Call {
	_c.Run(run)
	return _c
}

// UpdateTG provides a mock function for the type Store
func (_mock *Store) UpdateTG(ctx context.Context, input database.UpdateTalkgroupParams) (*talkgroups.Talkgroup, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTG")
	}

	var r0 *talkgroups.Talkgroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.UpdateTalkgroupParams) (*talkgroups.Talkgroup, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.UpdateTalkgroupParams) *talkgroups.Talkgroup); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*talkgroups.Talkgroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, database.UpdateTalkgroupParams) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_UpdateTG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTG'
type Store_UpdateTG_Call struct {
	*mock.Call
}

// UpdateTG is a helper method to define mock.On call
//   - ctx context.Context
//   - input database.UpdateTalkgroupParams
func (_e *Store_Expecter) UpdateTG(ctx interface{}, input interface{}) *Store_UpdateTG_Call {
	return &Store_UpdateTG_Call{Call: _e.mock.On("UpdateTG", ctx, input)}
}

func (_c *Store_UpdateTG_Call) Run(run func(ctx context.Context, input database.UpdateTalkgroupParams)) *Store_UpdateTG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.UpdateTalkgroupParams
		if args[1] != nil {
			arg1 = args[1].(database.UpdateTalkgroupParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_UpdateTG_Call) Return(talkgroup *talkgroups.Talkgroup, err error) *Store_UpdateTG_Call {
	_c.Call.Return(talkgroup, err)
	return _c
}

func (_c *Store_UpdateTG_Call) RunAndReturn(run func(ctx context.Context, input database.UpdateTalkgroupParams) (*talkgroups.Talkgroup, error)) *Store_UpdateTG_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertTGs provides a mock function for the type Store
func (_mock *Store) UpsertTGs(ctx context.Context, system int, input []database.UpsertTalkgroupParams) ([]*talkgroups.Talkgroup, error) {
	ret := _mock.Called(ctx, system, input)

	if len(ret) == 0 {
		panic("no return value specified for UpsertTGs")
	}

	var r0 []*talkgroups.Talkgroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []database.UpsertTalkgroupParams) ([]*talkgroups.Talkgroup, error)); ok {
		return returnFunc(ctx, system, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []database.UpsertTalkgroupParams) []*talkgroups.Talkgroup); ok {
		r0 = returnFunc(ctx, system, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*talkgroups.Talkgroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, []database.UpsertTalkgroupParams) error); ok {
		r1 = returnFunc(ctx, system, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_UpsertTGs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertTGs'
type Store_UpsertTGs_Call struct {
	*mock.Call
}

// UpsertTGs is a helper method to define mock.On call
//   - ctx context.Context
//   - system int
//   - input []database.UpsertTalkgroupParams
func (_e *Store_Expecter) UpsertTGs(ctx interface{}, system interface{}, input interface{}) *Store_UpsertTGs_Call {
	return &Store_UpsertTGs_Call{Call: _e.mock.On("UpsertTGs", ctx, system, input)}
}

func (_c *Store_UpsertTGs_Call) Run(run func(ctx context.Context, system int, input []database.UpsertTalkgroupParams)) *Store_UpsertTGs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []database.UpsertTalkgroupParams
		if args[2] != nil {
			arg2 = args[2].([]database.UpsertTalkgroupParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Store_UpsertTGs_Call) Return(talkgroups1 []*talkgroups.Talkgroup, err error) *Store_UpsertTGs_Call {
	_c.Call.Return(talkgroups1, err)
	return _c
}

func (_c *Store_UpsertTGs_Call) RunAndReturn(run func(ctx context.Context, system int, input []database.UpsertTalkgroupParams) ([]*talkgroups.Talkgroup, error)) *Store_UpsertTGs_Call {
	_c.Call.Return(run)
	return _c
}

// Weight provides a mock function for the type Store
func (_mock *Store) Weight(ctx context.Context, id talkgroups.ID, t time.Time) float64 {
	ret := _mock.Called(ctx, id, t)

	if len(ret) == 0 {
		panic("no return value specified for Weight")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func(context.Context, talkgroups.ID, time.Time) float64); ok {
		r0 = returnFunc(ctx, id, t)
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// Store_Weight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Weight'
type Store_Weight_Call struct {
	*mock.Call
}

// Weight is a helper method to define mock.On call
//   - ctx context.Context
//   - id talkgroups.ID
//   - t time.Time
func (_e *Store_Expecter) Weight(ctx interface{}, id interface{}, t interface{}) *Store_Weight_Call {
	return &Store_Weight_Call{Call: _e.mock.On("Weight", ctx, id, t)}
}

func (_c *Store_Weight_Call) Run(run func(ctx context.Context, id talkgroups.ID, t time.Time)) *Store_Weight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 talkgroups.ID
		if args[1] != nil {
			arg1 = args[1].(talkgroups.ID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Store_Weight_Call) Return(f float64) *Store_Weight_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *Store_Weight_Call) RunAndReturn(run func(ctx context.Context, id talkgroups.ID, t time.Time) float64) *Store_Weight_Call {
	_c.Call.Return(run)
	return _c
}
