// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	calls "dynatron.me/x/stillbox/pkg/calls"
	config "dynatron.me/x/stillbox/pkg/config"

	context "context"

	database "dynatron.me/x/stillbox/pkg/database"

	mock "github.com/stretchr/testify/mock"

	talkgroups "dynatron.me/x/stillbox/pkg/talkgroups"

	tgstore "dynatron.me/x/stillbox/pkg/talkgroups/tgstore"

	time "time"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// CreateSystem provides a mock function with given fields: ctx, id, name
func (_m *Store) CreateSystem(ctx context.Context, id int, name string) error {
	ret := _m.Called(ctx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateSystem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, id, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_CreateSystem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSystem'
type Store_CreateSystem_Call struct {
	*mock.Call
}

// CreateSystem is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - name string
func (_e *Store_Expecter) CreateSystem(ctx interface{}, id interface{}, name interface{}) *Store_CreateSystem_Call {
	return &Store_CreateSystem_Call{Call: _e.mock.On("CreateSystem", ctx, id, name)}
}

func (_c *Store_CreateSystem_Call) Run(run func(ctx context.Context, id int, name string)) *Store_CreateSystem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *Store_CreateSystem_Call) Return(_a0 error) *Store_CreateSystem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_CreateSystem_Call) RunAndReturn(run func(context.Context, int, string) error) *Store_CreateSystem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSystem provides a mock function with given fields: ctx, id
func (_m *Store) DeleteSystem(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSystem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_DeleteSystem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSystem'
type Store_DeleteSystem_Call struct {
	*mock.Call
}

// DeleteSystem is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *Store_Expecter) DeleteSystem(ctx interface{}, id interface{}) *Store_DeleteSystem_Call {
	return &Store_DeleteSystem_Call{Call: _e.mock.On("DeleteSystem", ctx, id)}
}

func (_c *Store_DeleteSystem_Call) Run(run func(ctx context.Context, id int)) *Store_DeleteSystem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Store_DeleteSystem_Call) Return(_a0 error) *Store_DeleteSystem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_DeleteSystem_Call) RunAndReturn(run func(context.Context, int) error) *Store_DeleteSystem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTG provides a mock function with given fields: ctx, id
func (_m *Store) DeleteTG(ctx context.Context, id talkgroups.ID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTG")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, talkgroups.ID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_DeleteTG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTG'
type Store_DeleteTG_Call struct {
	*mock.Call
}

// DeleteTG is a helper method to define mock.On call
//   - ctx context.Context
//   - id talkgroups.ID
func (_e *Store_Expecter) DeleteTG(ctx interface{}, id interface{}) *Store_DeleteTG_Call {
	return &Store_DeleteTG_Call{Call: _e.mock.On("DeleteTG", ctx, id)}
}

func (_c *Store_DeleteTG_Call) Run(run func(ctx context.Context, id talkgroups.ID)) *Store_DeleteTG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(talkgroups.ID))
	})
	return _c
}

func (_c *Store_DeleteTG_Call) Return(_a0 error) *Store_DeleteTG_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_DeleteTG_Call) RunAndReturn(run func(context.Context, talkgroups.ID) error) *Store_DeleteTG_Call {
	_c.Call.Return(run)
	return _c
}

// HUP provides a mock function with given fields: _a0
func (_m *Store) HUP(_a0 *config.Config) {
	_m.Called(_a0)
}

// Store_HUP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HUP'
type Store_HUP_Call struct {
	*mock.Call
}

// HUP is a helper method to define mock.On call
//   - _a0 *config.Config
func (_e *Store_Expecter) HUP(_a0 interface{}) *Store_HUP_Call {
	return &Store_HUP_Call{Call: _e.mock.On("HUP", _a0)}
}

func (_c *Store_HUP_Call) Run(run func(_a0 *config.Config)) *Store_HUP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.Config))
	})
	return _c
}

func (_c *Store_HUP_Call) Return() *Store_HUP_Call {
	_c.Call.Return()
	return _c
}

func (_c *Store_HUP_Call) RunAndReturn(run func(*config.Config)) *Store_HUP_Call {
	_c.Run(run)
	return _c
}

// Hint provides a mock function with given fields: ctx, tgs
func (_m *Store) Hint(ctx context.Context, tgs []talkgroups.ID) error {
	ret := _m.Called(ctx, tgs)

	if len(ret) == 0 {
		panic("no return value specified for Hint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []talkgroups.ID) error); ok {
		r0 = rf(ctx, tgs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_Hint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hint'
type Store_Hint_Call struct {
	*mock.Call
}

// Hint is a helper method to define mock.On call
//   - ctx context.Context
//   - tgs []talkgroups.ID
func (_e *Store_Expecter) Hint(ctx interface{}, tgs interface{}) *Store_Hint_Call {
	return &Store_Hint_Call{Call: _e.mock.On("Hint", ctx, tgs)}
}

func (_c *Store_Hint_Call) Run(run func(ctx context.Context, tgs []talkgroups.ID)) *Store_Hint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]talkgroups.ID))
	})
	return _c
}

func (_c *Store_Hint_Call) Return(_a0 error) *Store_Hint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_Hint_Call) RunAndReturn(run func(context.Context, []talkgroups.ID) error) *Store_Hint_Call {
	_c.Call.Return(run)
	return _c
}

// Invalidate provides a mock function with no fields
func (_m *Store) Invalidate() {
	_m.Called()
}

// Store_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type Store_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
func (_e *Store_Expecter) Invalidate() *Store_Invalidate_Call {
	return &Store_Invalidate_Call{Call: _e.mock.On("Invalidate")}
}

func (_c *Store_Invalidate_Call) Run(run func()) *Store_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Store_Invalidate_Call) Return() *Store_Invalidate_Call {
	_c.Call.Return()
	return _c
}

func (_c *Store_Invalidate_Call) RunAndReturn(run func()) *Store_Invalidate_Call {
	_c.Run(run)
	return _c
}

// LearnTG provides a mock function with given fields: ctx, call
func (_m *Store) LearnTG(ctx context.Context, call *calls.Call) (*talkgroups.Talkgroup, error) {
	ret := _m.Called(ctx, call)

	if len(ret) == 0 {
		panic("no return value specified for LearnTG")
	}

	var r0 *talkgroups.Talkgroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *calls.Call) (*talkgroups.Talkgroup, error)); ok {
		return rf(ctx, call)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *calls.Call) *talkgroups.Talkgroup); ok {
		r0 = rf(ctx, call)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*talkgroups.Talkgroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *calls.Call) error); ok {
		r1 = rf(ctx, call)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_LearnTG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LearnTG'
type Store_LearnTG_Call struct {
	*mock.Call
}

// LearnTG is a helper method to define mock.On call
//   - ctx context.Context
//   - call *calls.Call
func (_e *Store_Expecter) LearnTG(ctx interface{}, call interface{}) *Store_LearnTG_Call {
	return &Store_LearnTG_Call{Call: _e.mock.On("LearnTG", ctx, call)}
}

func (_c *Store_LearnTG_Call) Run(run func(ctx context.Context, call *calls.Call)) *Store_LearnTG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*calls.Call))
	})
	return _c
}

func (_c *Store_LearnTG_Call) Return(_a0 *talkgroups.Talkgroup, _a1 error) *Store_LearnTG_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_LearnTG_Call) RunAndReturn(run func(context.Context, *calls.Call) (*talkgroups.Talkgroup, error)) *Store_LearnTG_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function with given fields: ctx, tgs
func (_m *Store) Load(ctx context.Context, tgs database.TGTuples) error {
	ret := _m.Called(ctx, tgs)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.TGTuples) error); ok {
		r0 = rf(ctx, tgs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Store_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - tgs database.TGTuples
func (_e *Store_Expecter) Load(ctx interface{}, tgs interface{}) *Store_Load_Call {
	return &Store_Load_Call{Call: _e.mock.On("Load", ctx, tgs)}
}

func (_c *Store_Load_Call) Run(run func(ctx context.Context, tgs database.TGTuples)) *Store_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.TGTuples))
	})
	return _c
}

func (_c *Store_Load_Call) Return(_a0 error) *Store_Load_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_Load_Call) RunAndReturn(run func(context.Context, database.TGTuples) error) *Store_Load_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterFilter provides a mock function with given fields: _a0
func (_m *Store) RegisterFilter(_a0 tgstore.Filter) {
	_m.Called(_a0)
}

// Store_RegisterFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterFilter'
type Store_RegisterFilter_Call struct {
	*mock.Call
}

// RegisterFilter is a helper method to define mock.On call
//   - _a0 tgstore.Filter
func (_e *Store_Expecter) RegisterFilter(_a0 interface{}) *Store_RegisterFilter_Call {
	return &Store_RegisterFilter_Call{Call: _e.mock.On("RegisterFilter", _a0)}
}

func (_c *Store_RegisterFilter_Call) Run(run func(_a0 tgstore.Filter)) *Store_RegisterFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(tgstore.Filter))
	})
	return _c
}

func (_c *Store_RegisterFilter_Call) Return() *Store_RegisterFilter_Call {
	_c.Call.Return()
	return _c
}

func (_c *Store_RegisterFilter_Call) RunAndReturn(run func(tgstore.Filter)) *Store_RegisterFilter_Call {
	_c.Run(run)
	return _c
}

// SystemName provides a mock function with given fields: ctx, id
func (_m *Store) SystemName(ctx context.Context, id int) (string, bool) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SystemName")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, int) (string, bool)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Store_SystemName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SystemName'
type Store_SystemName_Call struct {
	*mock.Call
}

// SystemName is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *Store_Expecter) SystemName(ctx interface{}, id interface{}) *Store_SystemName_Call {
	return &Store_SystemName_Call{Call: _e.mock.On("SystemName", ctx, id)}
}

func (_c *Store_SystemName_Call) Run(run func(ctx context.Context, id int)) *Store_SystemName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Store_SystemName_Call) Return(_a0 string, _a1 bool) *Store_SystemName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_SystemName_Call) RunAndReturn(run func(context.Context, int) (string, bool)) *Store_SystemName_Call {
	_c.Call.Return(run)
	return _c
}

// SystemTGs provides a mock function with given fields: ctx, systemID, opts
func (_m *Store) SystemTGs(ctx context.Context, systemID int, opts ...tgstore.Option) ([]*talkgroups.Talkgroup, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, systemID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SystemTGs")
	}

	var r0 []*talkgroups.Talkgroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, ...tgstore.Option) ([]*talkgroups.Talkgroup, error)); ok {
		return rf(ctx, systemID, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, ...tgstore.Option) []*talkgroups.Talkgroup); ok {
		r0 = rf(ctx, systemID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*talkgroups.Talkgroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, ...tgstore.Option) error); ok {
		r1 = rf(ctx, systemID, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_SystemTGs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SystemTGs'
type Store_SystemTGs_Call struct {
	*mock.Call
}

// SystemTGs is a helper method to define mock.On call
//   - ctx context.Context
//   - systemID int
//   - opts ...tgstore.Option
func (_e *Store_Expecter) SystemTGs(ctx interface{}, systemID interface{}, opts ...interface{}) *Store_SystemTGs_Call {
	return &Store_SystemTGs_Call{Call: _e.mock.On("SystemTGs",
		append([]interface{}{ctx, systemID}, opts...)...)}
}

func (_c *Store_SystemTGs_Call) Run(run func(ctx context.Context, systemID int, opts ...tgstore.Option)) *Store_SystemTGs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]tgstore.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(tgstore.Option)
			}
		}
		run(args[0].(context.Context), args[1].(int), variadicArgs...)
	})
	return _c
}

func (_c *Store_SystemTGs_Call) Return(_a0 []*talkgroups.Talkgroup, _a1 error) *Store_SystemTGs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_SystemTGs_Call) RunAndReturn(run func(context.Context, int, ...tgstore.Option) ([]*talkgroups.Talkgroup, error)) *Store_SystemTGs_Call {
	_c.Call.Return(run)
	return _c
}

// TG provides a mock function with given fields: ctx, tg
func (_m *Store) TG(ctx context.Context, tg talkgroups.ID) (*talkgroups.Talkgroup, error) {
	ret := _m.Called(ctx, tg)

	if len(ret) == 0 {
		panic("no return value specified for TG")
	}

	var r0 *talkgroups.Talkgroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, talkgroups.ID) (*talkgroups.Talkgroup, error)); ok {
		return rf(ctx, tg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, talkgroups.ID) *talkgroups.Talkgroup); ok {
		r0 = rf(ctx, tg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*talkgroups.Talkgroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, talkgroups.ID) error); ok {
		r1 = rf(ctx, tg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_TG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TG'
type Store_TG_Call struct {
	*mock.Call
}

// TG is a helper method to define mock.On call
//   - ctx context.Context
//   - tg talkgroups.ID
func (_e *Store_Expecter) TG(ctx interface{}, tg interface{}) *Store_TG_Call {
	return &Store_TG_Call{Call: _e.mock.On("TG", ctx, tg)}
}

func (_c *Store_TG_Call) Run(run func(ctx context.Context, tg talkgroups.ID)) *Store_TG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(talkgroups.ID))
	})
	return _c
}

func (_c *Store_TG_Call) Return(_a0 *talkgroups.Talkgroup, _a1 error) *Store_TG_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_TG_Call) RunAndReturn(run func(context.Context, talkgroups.ID) (*talkgroups.Talkgroup, error)) *Store_TG_Call {
	_c.Call.Return(run)
	return _c
}

// TGs provides a mock function with given fields: ctx, tgs, opts
func (_m *Store) TGs(ctx context.Context, tgs talkgroups.IDs, opts ...tgstore.Option) ([]*talkgroups.Talkgroup, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, tgs)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for TGs")
	}

	var r0 []*talkgroups.Talkgroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, talkgroups.IDs, ...tgstore.Option) ([]*talkgroups.Talkgroup, error)); ok {
		return rf(ctx, tgs, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, talkgroups.IDs, ...tgstore.Option) []*talkgroups.Talkgroup); ok {
		r0 = rf(ctx, tgs, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*talkgroups.Talkgroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, talkgroups.IDs, ...tgstore.Option) error); ok {
		r1 = rf(ctx, tgs, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_TGs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TGs'
type Store_TGs_Call struct {
	*mock.Call
}

// TGs is a helper method to define mock.On call
//   - ctx context.Context
//   - tgs talkgroups.IDs
//   - opts ...tgstore.Option
func (_e *Store_Expecter) TGs(ctx interface{}, tgs interface{}, opts ...interface{}) *Store_TGs_Call {
	return &Store_TGs_Call{Call: _e.mock.On("TGs",
		append([]interface{}{ctx, tgs}, opts...)...)}
}

func (_c *Store_TGs_Call) Run(run func(ctx context.Context, tgs talkgroups.IDs, opts ...tgstore.Option)) *Store_TGs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]tgstore.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(tgstore.Option)
			}
		}
		run(args[0].(context.Context), args[1].(talkgroups.IDs), variadicArgs...)
	})
	return _c
}

func (_c *Store_TGs_Call) Return(_a0 []*talkgroups.Talkgroup, _a1 error) *Store_TGs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_TGs_Call) RunAndReturn(run func(context.Context, talkgroups.IDs, ...tgstore.Option) ([]*talkgroups.Talkgroup, error)) *Store_TGs_Call {
	_c.Call.Return(run)
	return _c
}

// TGsByTags provides a mock function with given fields: ctx, tagsAll, tagsAny, tagsNot
func (_m *Store) TGsByTags(ctx context.Context, tagsAll []string, tagsAny []string, tagsNot []string) (talkgroups.IDs, error) {
	ret := _m.Called(ctx, tagsAll, tagsAny, tagsNot)

	if len(ret) == 0 {
		panic("no return value specified for TGsByTags")
	}

	var r0 talkgroups.IDs
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string, []string) (talkgroups.IDs, error)); ok {
		return rf(ctx, tagsAll, tagsAny, tagsNot)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string, []string) talkgroups.IDs); ok {
		r0 = rf(ctx, tagsAll, tagsAny, tagsNot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(talkgroups.IDs)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, []string, []string) error); ok {
		r1 = rf(ctx, tagsAll, tagsAny, tagsNot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_TGsByTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TGsByTags'
type Store_TGsByTags_Call struct {
	*mock.Call
}

// TGsByTags is a helper method to define mock.On call
//   - ctx context.Context
//   - tagsAll []string
//   - tagsAny []string
//   - tagsNot []string
func (_e *Store_Expecter) TGsByTags(ctx interface{}, tagsAll interface{}, tagsAny interface{}, tagsNot interface{}) *Store_TGsByTags_Call {
	return &Store_TGsByTags_Call{Call: _e.mock.On("TGsByTags", ctx, tagsAll, tagsAny, tagsNot)}
}

func (_c *Store_TGsByTags_Call) Run(run func(ctx context.Context, tagsAll []string, tagsAny []string, tagsNot []string)) *Store_TGsByTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].([]string), args[3].([]string))
	})
	return _c
}

func (_c *Store_TGsByTags_Call) Return(_a0 talkgroups.IDs, _a1 error) *Store_TGsByTags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_TGsByTags_Call) RunAndReturn(run func(context.Context, []string, []string, []string) (talkgroups.IDs, error)) *Store_TGsByTags_Call {
	_c.Call.Return(run)
	return _c
}

// Tags provides a mock function with given fields: ctx
func (_m *Store) Tags(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Tags")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_Tags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tags'
type Store_Tags_Call struct {
	*mock.Call
}

// Tags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Store_Expecter) Tags(ctx interface{}) *Store_Tags_Call {
	return &Store_Tags_Call{Call: _e.mock.On("Tags", ctx)}
}

func (_c *Store_Tags_Call) Run(run func(ctx context.Context)) *Store_Tags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Store_Tags_Call) Return(_a0 []string, _a1 error) *Store_Tags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_Tags_Call) RunAndReturn(run func(context.Context) ([]string, error)) *Store_Tags_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterFilter provides a mock function with given fields: _a0
func (_m *Store) UnregisterFilter(_a0 tgstore.Filter) {
	_m.Called(_a0)
}

// Store_UnregisterFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterFilter'
type Store_UnregisterFilter_Call struct {
	*mock.Call
}

// UnregisterFilter is a helper method to define mock.On call
//   - _a0 tgstore.Filter
func (_e *Store_Expecter) UnregisterFilter(_a0 interface{}) *Store_UnregisterFilter_Call {
	return &Store_UnregisterFilter_Call{Call: _e.mock.On("UnregisterFilter", _a0)}
}

func (_c *Store_UnregisterFilter_Call) Run(run func(_a0 tgstore.Filter)) *Store_UnregisterFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(tgstore.Filter))
	})
	return _c
}

func (_c *Store_UnregisterFilter_Call) Return() *Store_UnregisterFilter_Call {
	_c.Call.Return()
	return _c
}

func (_c *Store_UnregisterFilter_Call) RunAndReturn(run func(tgstore.Filter)) *Store_UnregisterFilter_Call {
	_c.Run(run)
	return _c
}

// UpdateTG provides a mock function with given fields: ctx, input
func (_m *Store) UpdateTG(ctx context.Context, input database.UpdateTalkgroupParams) (*talkgroups.Talkgroup, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTG")
	}

	var r0 *talkgroups.Talkgroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateTalkgroupParams) (*talkgroups.Talkgroup, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateTalkgroupParams) *talkgroups.Talkgroup); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*talkgroups.Talkgroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.UpdateTalkgroupParams) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_UpdateTG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTG'
type Store_UpdateTG_Call struct {
	*mock.Call
}

// UpdateTG is a helper method to define mock.On call
//   - ctx context.Context
//   - input database.UpdateTalkgroupParams
func (_e *Store_Expecter) UpdateTG(ctx interface{}, input interface{}) *Store_UpdateTG_Call {
	return &Store_UpdateTG_Call{Call: _e.mock.On("UpdateTG", ctx, input)}
}

func (_c *Store_UpdateTG_Call) Run(run func(ctx context.Context, input database.UpdateTalkgroupParams)) *Store_UpdateTG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.UpdateTalkgroupParams))
	})
	return _c
}

func (_c *Store_UpdateTG_Call) Return(_a0 *talkgroups.Talkgroup, _a1 error) *Store_UpdateTG_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_UpdateTG_Call) RunAndReturn(run func(context.Context, database.UpdateTalkgroupParams) (*talkgroups.Talkgroup, error)) *Store_UpdateTG_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertTGs provides a mock function with given fields: ctx, system, input
func (_m *Store) UpsertTGs(ctx context.Context, system int, input []database.UpsertTalkgroupParams) ([]*talkgroups.Talkgroup, error) {
	ret := _m.Called(ctx, system, input)

	if len(ret) == 0 {
		panic("no return value specified for UpsertTGs")
	}

	var r0 []*talkgroups.Talkgroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []database.UpsertTalkgroupParams) ([]*talkgroups.Talkgroup, error)); ok {
		return rf(ctx, system, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, []database.UpsertTalkgroupParams) []*talkgroups.Talkgroup); ok {
		r0 = rf(ctx, system, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*talkgroups.Talkgroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, []database.UpsertTalkgroupParams) error); ok {
		r1 = rf(ctx, system, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_UpsertTGs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertTGs'
type Store_UpsertTGs_Call struct {
	*mock.Call
}

// UpsertTGs is a helper method to define mock.On call
//   - ctx context.Context
//   - system int
//   - input []database.UpsertTalkgroupParams
func (_e *Store_Expecter) UpsertTGs(ctx interface{}, system interface{}, input interface{}) *Store_UpsertTGs_Call {
	return &Store_UpsertTGs_Call{Call: _e.mock.On("UpsertTGs", ctx, system, input)}
}

func (_c *Store_UpsertTGs_Call) Run(run func(ctx context.Context, system int, input []database.UpsertTalkgroupParams)) *Store_UpsertTGs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].([]database.UpsertTalkgroupParams))
	})
	return _c
}

func (_c *Store_UpsertTGs_Call) Return(_a0 []*talkgroups.Talkgroup, _a1 error) *Store_UpsertTGs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_UpsertTGs_Call) RunAndReturn(run func(context.Context, int, []database.UpsertTalkgroupParams) ([]*talkgroups.Talkgroup, error)) *Store_UpsertTGs_Call {
	_c.Call.Return(run)
	return _c
}

// Weight provides a mock function with given fields: ctx, id, t
func (_m *Store) Weight(ctx context.Context, id talkgroups.ID, t time.Time) float64 {
	ret := _m.Called(ctx, id, t)

	if len(ret) == 0 {
		panic("no return value specified for Weight")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func(context.Context, talkgroups.ID, time.Time) float64); ok {
		r0 = rf(ctx, id, t)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// Store_Weight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Weight'
type Store_Weight_Call struct {
	*mock.Call
}

// Weight is a helper method to define mock.On call
//   - ctx context.Context
//   - id talkgroups.ID
//   - t time.Time
func (_e *Store_Expecter) Weight(ctx interface{}, id interface{}, t interface{}) *Store_Weight_Call {
	return &Store_Weight_Call{Call: _e.mock.On("Weight", ctx, id, t)}
}

func (_c *Store_Weight_Call) Run(run func(ctx context.Context, id talkgroups.ID, t time.Time)) *Store_Weight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(talkgroups.ID), args[2].(time.Time))
	})
	return _c
}

func (_c *Store_Weight_Call) Return(_a0 float64) *Store_Weight_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_Weight_Call) RunAndReturn(run func(context.Context, talkgroups.ID, time.Time) float64) *Store_Weight_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
