// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.32.1
// source: stillbox.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Struct } from "./google/protobuf/struct";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "stillbox";

export enum LiveState {
  LS_STOPPED = 0,
  LS_LIVE = 1,
  LS_PAUSED = 2,
  UNRECOGNIZED = -1,
}

export function liveStateFromJSON(object: any): LiveState {
  switch (object) {
    case 0:
    case "LS_STOPPED":
      return LiveState.LS_STOPPED;
    case 1:
    case "LS_LIVE":
      return LiveState.LS_LIVE;
    case 2:
    case "LS_PAUSED":
      return LiveState.LS_PAUSED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return LiveState.UNRECOGNIZED;
  }
}

export function liveStateToJSON(object: LiveState): string {
  switch (object) {
    case LiveState.LS_STOPPED:
      return "LS_STOPPED";
    case LiveState.LS_LIVE:
      return "LS_LIVE";
    case LiveState.LS_PAUSED:
      return "LS_PAUSED";
    case LiveState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Message {
  response?: CommandResponse | undefined;
  call?: Call | undefined;
  transcription?: CallTranscription | undefined;
  notification?: Notification | undefined;
  popup?: UserPopup | undefined;
  error?: Error | undefined;
  hello?: Hello | undefined;
}

export interface CommandResponse {
  commandId?: number | undefined;
  tgInfo?: TalkgroupInfo | undefined;
}

export interface Call {
  id: string;
  audioName: string;
  audioType: string;
  dateTime: Date | undefined;
  system: number;
  talkgroup: number;
  talkerAlias?: string | undefined;
  source: number;
  frequency: number;
  frequencies: number[];
  patches: number[];
  duration?: number | undefined;
  audio: Uint8Array;
}

export interface CallTranscription {
  id: string;
  system: number;
  talkgroup: number;
  patches: number[];
  transcript: string;
}

export interface Hello {
  serverInfo: ServerInfo | undefined;
}

export interface UserPopup {
  msg: string;
}

export interface Error {
  error: string;
  command: Command | undefined;
}

export interface Notification {
  dateTime: Date | undefined;
  msg: string;
  actionUrl: string;
}

export interface Command {
  commandId?: number | undefined;
  liveCommand?: Live | undefined;
  searchCommand?: Search | undefined;
  tgCommand?: Talkgroup | undefined;
}

export interface TalkgroupInfo {
  tg: Talkgroup | undefined;
  systemName: string;
  name?: string | undefined;
  group?: string | undefined;
  alphaTag?: string | undefined;
  frequency?: number | undefined;
  tags: string[];
  metadata?: { [key: string]: any } | undefined;
  learned: boolean;
}

export interface Live {
  state?: LiveState | undefined;
  filter?: Filter | undefined;
  calls: boolean;
  transcripts: boolean;
}

export interface Talkgroup {
  system: number;
  talkgroup: number;
}

export interface Filter {
  talkgroups: Talkgroup[];
  talkgroupsNot: Talkgroup[];
  talkgroupTagsAll: string[];
  talkgroupTagsAny: string[];
  talkgroupTagsNot: string[];
}

export interface Search {
}

export interface ServerInfo {
  serverName: string;
  version: string;
  built: string;
  platform: string;
  dbSize: string;
}

export interface CallTranscribeRequest {
  call: Call | undefined;
  callback: string;
  token: string;
}

function createBaseMessage(): Message {
  return {
    response: undefined,
    call: undefined,
    transcription: undefined,
    notification: undefined,
    popup: undefined,
    error: undefined,
    hello: undefined,
  };
}

export const Message: MessageFns<Message> = {
  encode(message: Message, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.response !== undefined) {
      CommandResponse.encode(message.response, writer.uint32(10).fork()).join();
    }
    if (message.call !== undefined) {
      Call.encode(message.call, writer.uint32(18).fork()).join();
    }
    if (message.transcription !== undefined) {
      CallTranscription.encode(message.transcription, writer.uint32(26).fork()).join();
    }
    if (message.notification !== undefined) {
      Notification.encode(message.notification, writer.uint32(34).fork()).join();
    }
    if (message.popup !== undefined) {
      UserPopup.encode(message.popup, writer.uint32(42).fork()).join();
    }
    if (message.error !== undefined) {
      Error.encode(message.error, writer.uint32(50).fork()).join();
    }
    if (message.hello !== undefined) {
      Hello.encode(message.hello, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.response = CommandResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.call = Call.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.transcription = CallTranscription.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.notification = Notification.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.popup = UserPopup.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.error = Error.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.hello = Hello.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Message {
    return {
      response: isSet(object.response) ? CommandResponse.fromJSON(object.response) : undefined,
      call: isSet(object.call) ? Call.fromJSON(object.call) : undefined,
      transcription: isSet(object.transcription) ? CallTranscription.fromJSON(object.transcription) : undefined,
      notification: isSet(object.notification) ? Notification.fromJSON(object.notification) : undefined,
      popup: isSet(object.popup) ? UserPopup.fromJSON(object.popup) : undefined,
      error: isSet(object.error) ? Error.fromJSON(object.error) : undefined,
      hello: isSet(object.hello) ? Hello.fromJSON(object.hello) : undefined,
    };
  },

  toJSON(message: Message): unknown {
    const obj: any = {};
    if (message.response !== undefined) {
      obj.response = CommandResponse.toJSON(message.response);
    }
    if (message.call !== undefined) {
      obj.call = Call.toJSON(message.call);
    }
    if (message.transcription !== undefined) {
      obj.transcription = CallTranscription.toJSON(message.transcription);
    }
    if (message.notification !== undefined) {
      obj.notification = Notification.toJSON(message.notification);
    }
    if (message.popup !== undefined) {
      obj.popup = UserPopup.toJSON(message.popup);
    }
    if (message.error !== undefined) {
      obj.error = Error.toJSON(message.error);
    }
    if (message.hello !== undefined) {
      obj.hello = Hello.toJSON(message.hello);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Message>, I>>(base?: I): Message {
    return Message.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Message>, I>>(object: I): Message {
    const message = createBaseMessage();
    message.response = (object.response !== undefined && object.response !== null)
      ? CommandResponse.fromPartial(object.response)
      : undefined;
    message.call = (object.call !== undefined && object.call !== null) ? Call.fromPartial(object.call) : undefined;
    message.transcription = (object.transcription !== undefined && object.transcription !== null)
      ? CallTranscription.fromPartial(object.transcription)
      : undefined;
    message.notification = (object.notification !== undefined && object.notification !== null)
      ? Notification.fromPartial(object.notification)
      : undefined;
    message.popup = (object.popup !== undefined && object.popup !== null)
      ? UserPopup.fromPartial(object.popup)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null) ? Error.fromPartial(object.error) : undefined;
    message.hello = (object.hello !== undefined && object.hello !== null) ? Hello.fromPartial(object.hello) : undefined;
    return message;
  },
};

function createBaseCommandResponse(): CommandResponse {
  return { commandId: undefined, tgInfo: undefined };
}

export const CommandResponse: MessageFns<CommandResponse> = {
  encode(message: CommandResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.commandId !== undefined) {
      writer.uint32(8).int64(message.commandId);
    }
    if (message.tgInfo !== undefined) {
      TalkgroupInfo.encode(message.tgInfo, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CommandResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommandResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.commandId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tgInfo = TalkgroupInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CommandResponse {
    return {
      commandId: isSet(object.commandId) ? globalThis.Number(object.commandId) : undefined,
      tgInfo: isSet(object.tgInfo) ? TalkgroupInfo.fromJSON(object.tgInfo) : undefined,
    };
  },

  toJSON(message: CommandResponse): unknown {
    const obj: any = {};
    if (message.commandId !== undefined) {
      obj.commandId = Math.round(message.commandId);
    }
    if (message.tgInfo !== undefined) {
      obj.tgInfo = TalkgroupInfo.toJSON(message.tgInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CommandResponse>, I>>(base?: I): CommandResponse {
    return CommandResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommandResponse>, I>>(object: I): CommandResponse {
    const message = createBaseCommandResponse();
    message.commandId = object.commandId ?? undefined;
    message.tgInfo = (object.tgInfo !== undefined && object.tgInfo !== null)
      ? TalkgroupInfo.fromPartial(object.tgInfo)
      : undefined;
    return message;
  },
};

function createBaseCall(): Call {
  return {
    id: "",
    audioName: "",
    audioType: "",
    dateTime: undefined,
    system: 0,
    talkgroup: 0,
    talkerAlias: undefined,
    source: 0,
    frequency: 0,
    frequencies: [],
    patches: [],
    duration: undefined,
    audio: new Uint8Array(0),
  };
}

export const Call: MessageFns<Call> = {
  encode(message: Call, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.audioName !== "") {
      writer.uint32(18).string(message.audioName);
    }
    if (message.audioType !== "") {
      writer.uint32(26).string(message.audioType);
    }
    if (message.dateTime !== undefined) {
      Timestamp.encode(toTimestamp(message.dateTime), writer.uint32(34).fork()).join();
    }
    if (message.system !== 0) {
      writer.uint32(40).int32(message.system);
    }
    if (message.talkgroup !== 0) {
      writer.uint32(48).int32(message.talkgroup);
    }
    if (message.talkerAlias !== undefined) {
      writer.uint32(58).string(message.talkerAlias);
    }
    if (message.source !== 0) {
      writer.uint32(64).int32(message.source);
    }
    if (message.frequency !== 0) {
      writer.uint32(72).int64(message.frequency);
    }
    writer.uint32(82).fork();
    for (const v of message.frequencies) {
      writer.int64(v);
    }
    writer.join();
    writer.uint32(90).fork();
    for (const v of message.patches) {
      writer.int32(v);
    }
    writer.join();
    if (message.duration !== undefined) {
      writer.uint32(96).int32(message.duration);
    }
    if (message.audio.length !== 0) {
      writer.uint32(106).bytes(message.audio);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Call {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCall();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.audioName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.audioType = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.dateTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.system = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.talkgroup = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.talkerAlias = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.source = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.frequency = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag === 80) {
            message.frequencies.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 82) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.frequencies.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
        case 11: {
          if (tag === 88) {
            message.patches.push(reader.int32());

            continue;
          }

          if (tag === 90) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.patches.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.duration = reader.int32();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.audio = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Call {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      audioName: isSet(object.audioName) ? globalThis.String(object.audioName) : "",
      audioType: isSet(object.audioType) ? globalThis.String(object.audioType) : "",
      dateTime: isSet(object.dateTime) ? fromJsonTimestamp(object.dateTime) : undefined,
      system: isSet(object.system) ? globalThis.Number(object.system) : 0,
      talkgroup: isSet(object.talkgroup) ? globalThis.Number(object.talkgroup) : 0,
      talkerAlias: isSet(object.talkerAlias) ? globalThis.String(object.talkerAlias) : undefined,
      source: isSet(object.source) ? globalThis.Number(object.source) : 0,
      frequency: isSet(object.frequency) ? globalThis.Number(object.frequency) : 0,
      frequencies: globalThis.Array.isArray(object?.frequencies)
        ? object.frequencies.map((e: any) => globalThis.Number(e))
        : [],
      patches: globalThis.Array.isArray(object?.patches) ? object.patches.map((e: any) => globalThis.Number(e)) : [],
      duration: isSet(object.duration) ? globalThis.Number(object.duration) : undefined,
      audio: isSet(object.audio) ? bytesFromBase64(object.audio) : new Uint8Array(0),
    };
  },

  toJSON(message: Call): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.audioName !== "") {
      obj.audioName = message.audioName;
    }
    if (message.audioType !== "") {
      obj.audioType = message.audioType;
    }
    if (message.dateTime !== undefined) {
      obj.dateTime = message.dateTime.toISOString();
    }
    if (message.system !== 0) {
      obj.system = Math.round(message.system);
    }
    if (message.talkgroup !== 0) {
      obj.talkgroup = Math.round(message.talkgroup);
    }
    if (message.talkerAlias !== undefined) {
      obj.talkerAlias = message.talkerAlias;
    }
    if (message.source !== 0) {
      obj.source = Math.round(message.source);
    }
    if (message.frequency !== 0) {
      obj.frequency = Math.round(message.frequency);
    }
    if (message.frequencies?.length) {
      obj.frequencies = message.frequencies.map((e) => Math.round(e));
    }
    if (message.patches?.length) {
      obj.patches = message.patches.map((e) => Math.round(e));
    }
    if (message.duration !== undefined) {
      obj.duration = Math.round(message.duration);
    }
    if (message.audio.length !== 0) {
      obj.audio = base64FromBytes(message.audio);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Call>, I>>(base?: I): Call {
    return Call.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Call>, I>>(object: I): Call {
    const message = createBaseCall();
    message.id = object.id ?? "";
    message.audioName = object.audioName ?? "";
    message.audioType = object.audioType ?? "";
    message.dateTime = object.dateTime ?? undefined;
    message.system = object.system ?? 0;
    message.talkgroup = object.talkgroup ?? 0;
    message.talkerAlias = object.talkerAlias ?? undefined;
    message.source = object.source ?? 0;
    message.frequency = object.frequency ?? 0;
    message.frequencies = object.frequencies?.map((e) => e) || [];
    message.patches = object.patches?.map((e) => e) || [];
    message.duration = object.duration ?? undefined;
    message.audio = object.audio ?? new Uint8Array(0);
    return message;
  },
};

function createBaseCallTranscription(): CallTranscription {
  return { id: "", system: 0, talkgroup: 0, patches: [], transcript: "" };
}

export const CallTranscription: MessageFns<CallTranscription> = {
  encode(message: CallTranscription, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.system !== 0) {
      writer.uint32(16).int32(message.system);
    }
    if (message.talkgroup !== 0) {
      writer.uint32(24).int32(message.talkgroup);
    }
    writer.uint32(34).fork();
    for (const v of message.patches) {
      writer.int32(v);
    }
    writer.join();
    if (message.transcript !== "") {
      writer.uint32(42).string(message.transcript);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallTranscription {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallTranscription();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.system = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.talkgroup = reader.int32();
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.patches.push(reader.int32());

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.patches.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.transcript = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallTranscription {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      system: isSet(object.system) ? globalThis.Number(object.system) : 0,
      talkgroup: isSet(object.talkgroup) ? globalThis.Number(object.talkgroup) : 0,
      patches: globalThis.Array.isArray(object?.patches) ? object.patches.map((e: any) => globalThis.Number(e)) : [],
      transcript: isSet(object.transcript) ? globalThis.String(object.transcript) : "",
    };
  },

  toJSON(message: CallTranscription): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.system !== 0) {
      obj.system = Math.round(message.system);
    }
    if (message.talkgroup !== 0) {
      obj.talkgroup = Math.round(message.talkgroup);
    }
    if (message.patches?.length) {
      obj.patches = message.patches.map((e) => Math.round(e));
    }
    if (message.transcript !== "") {
      obj.transcript = message.transcript;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallTranscription>, I>>(base?: I): CallTranscription {
    return CallTranscription.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallTranscription>, I>>(object: I): CallTranscription {
    const message = createBaseCallTranscription();
    message.id = object.id ?? "";
    message.system = object.system ?? 0;
    message.talkgroup = object.talkgroup ?? 0;
    message.patches = object.patches?.map((e) => e) || [];
    message.transcript = object.transcript ?? "";
    return message;
  },
};

function createBaseHello(): Hello {
  return { serverInfo: undefined };
}

export const Hello: MessageFns<Hello> = {
  encode(message: Hello, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverInfo !== undefined) {
      ServerInfo.encode(message.serverInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Hello {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHello();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverInfo = ServerInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Hello {
    return { serverInfo: isSet(object.serverInfo) ? ServerInfo.fromJSON(object.serverInfo) : undefined };
  },

  toJSON(message: Hello): unknown {
    const obj: any = {};
    if (message.serverInfo !== undefined) {
      obj.serverInfo = ServerInfo.toJSON(message.serverInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Hello>, I>>(base?: I): Hello {
    return Hello.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Hello>, I>>(object: I): Hello {
    const message = createBaseHello();
    message.serverInfo = (object.serverInfo !== undefined && object.serverInfo !== null)
      ? ServerInfo.fromPartial(object.serverInfo)
      : undefined;
    return message;
  },
};

function createBaseUserPopup(): UserPopup {
  return { msg: "" };
}

export const UserPopup: MessageFns<UserPopup> = {
  encode(message: UserPopup, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.msg !== "") {
      writer.uint32(10).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserPopup {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserPopup();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserPopup {
    return { msg: isSet(object.msg) ? globalThis.String(object.msg) : "" };
  },

  toJSON(message: UserPopup): unknown {
    const obj: any = {};
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserPopup>, I>>(base?: I): UserPopup {
    return UserPopup.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserPopup>, I>>(object: I): UserPopup {
    const message = createBaseUserPopup();
    message.msg = object.msg ?? "";
    return message;
  },
};

function createBaseError(): Error {
  return { error: "", command: undefined };
}

export const Error: MessageFns<Error> = {
  encode(message: Error, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== "") {
      writer.uint32(10).string(message.error);
    }
    if (message.command !== undefined) {
      Command.encode(message.command, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Error {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseError();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.command = Command.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Error {
    return {
      error: isSet(object.error) ? globalThis.String(object.error) : "",
      command: isSet(object.command) ? Command.fromJSON(object.command) : undefined,
    };
  },

  toJSON(message: Error): unknown {
    const obj: any = {};
    if (message.error !== "") {
      obj.error = message.error;
    }
    if (message.command !== undefined) {
      obj.command = Command.toJSON(message.command);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Error>, I>>(base?: I): Error {
    return Error.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Error>, I>>(object: I): Error {
    const message = createBaseError();
    message.error = object.error ?? "";
    message.command = (object.command !== undefined && object.command !== null)
      ? Command.fromPartial(object.command)
      : undefined;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { dateTime: undefined, msg: "", actionUrl: "" };
}

export const Notification: MessageFns<Notification> = {
  encode(message: Notification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.dateTime !== undefined) {
      Timestamp.encode(toTimestamp(message.dateTime), writer.uint32(10).fork()).join();
    }
    if (message.msg !== "") {
      writer.uint32(18).string(message.msg);
    }
    if (message.actionUrl !== "") {
      writer.uint32(26).string(message.actionUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Notification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.dateTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.actionUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Notification {
    return {
      dateTime: isSet(object.dateTime) ? fromJsonTimestamp(object.dateTime) : undefined,
      msg: isSet(object.msg) ? globalThis.String(object.msg) : "",
      actionUrl: isSet(object.actionUrl) ? globalThis.String(object.actionUrl) : "",
    };
  },

  toJSON(message: Notification): unknown {
    const obj: any = {};
    if (message.dateTime !== undefined) {
      obj.dateTime = message.dateTime.toISOString();
    }
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    if (message.actionUrl !== "") {
      obj.actionUrl = message.actionUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Notification>, I>>(base?: I): Notification {
    return Notification.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Notification>, I>>(object: I): Notification {
    const message = createBaseNotification();
    message.dateTime = object.dateTime ?? undefined;
    message.msg = object.msg ?? "";
    message.actionUrl = object.actionUrl ?? "";
    return message;
  },
};

function createBaseCommand(): Command {
  return { commandId: undefined, liveCommand: undefined, searchCommand: undefined, tgCommand: undefined };
}

export const Command: MessageFns<Command> = {
  encode(message: Command, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.commandId !== undefined) {
      writer.uint32(8).int64(message.commandId);
    }
    if (message.liveCommand !== undefined) {
      Live.encode(message.liveCommand, writer.uint32(18).fork()).join();
    }
    if (message.searchCommand !== undefined) {
      Search.encode(message.searchCommand, writer.uint32(26).fork()).join();
    }
    if (message.tgCommand !== undefined) {
      Talkgroup.encode(message.tgCommand, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Command {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.commandId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.liveCommand = Live.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.searchCommand = Search.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.tgCommand = Talkgroup.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Command {
    return {
      commandId: isSet(object.commandId) ? globalThis.Number(object.commandId) : undefined,
      liveCommand: isSet(object.liveCommand) ? Live.fromJSON(object.liveCommand) : undefined,
      searchCommand: isSet(object.searchCommand) ? Search.fromJSON(object.searchCommand) : undefined,
      tgCommand: isSet(object.tgCommand) ? Talkgroup.fromJSON(object.tgCommand) : undefined,
    };
  },

  toJSON(message: Command): unknown {
    const obj: any = {};
    if (message.commandId !== undefined) {
      obj.commandId = Math.round(message.commandId);
    }
    if (message.liveCommand !== undefined) {
      obj.liveCommand = Live.toJSON(message.liveCommand);
    }
    if (message.searchCommand !== undefined) {
      obj.searchCommand = Search.toJSON(message.searchCommand);
    }
    if (message.tgCommand !== undefined) {
      obj.tgCommand = Talkgroup.toJSON(message.tgCommand);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Command>, I>>(base?: I): Command {
    return Command.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Command>, I>>(object: I): Command {
    const message = createBaseCommand();
    message.commandId = object.commandId ?? undefined;
    message.liveCommand = (object.liveCommand !== undefined && object.liveCommand !== null)
      ? Live.fromPartial(object.liveCommand)
      : undefined;
    message.searchCommand = (object.searchCommand !== undefined && object.searchCommand !== null)
      ? Search.fromPartial(object.searchCommand)
      : undefined;
    message.tgCommand = (object.tgCommand !== undefined && object.tgCommand !== null)
      ? Talkgroup.fromPartial(object.tgCommand)
      : undefined;
    return message;
  },
};

function createBaseTalkgroupInfo(): TalkgroupInfo {
  return {
    tg: undefined,
    systemName: "",
    name: undefined,
    group: undefined,
    alphaTag: undefined,
    frequency: undefined,
    tags: [],
    metadata: undefined,
    learned: false,
  };
}

export const TalkgroupInfo: MessageFns<TalkgroupInfo> = {
  encode(message: TalkgroupInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tg !== undefined) {
      Talkgroup.encode(message.tg, writer.uint32(10).fork()).join();
    }
    if (message.systemName !== "") {
      writer.uint32(18).string(message.systemName);
    }
    if (message.name !== undefined) {
      writer.uint32(26).string(message.name);
    }
    if (message.group !== undefined) {
      writer.uint32(34).string(message.group);
    }
    if (message.alphaTag !== undefined) {
      writer.uint32(42).string(message.alphaTag);
    }
    if (message.frequency !== undefined) {
      writer.uint32(48).int32(message.frequency);
    }
    for (const v of message.tags) {
      writer.uint32(58).string(v!);
    }
    if (message.metadata !== undefined) {
      Struct.encode(Struct.wrap(message.metadata), writer.uint32(66).fork()).join();
    }
    if (message.learned !== false) {
      writer.uint32(72).bool(message.learned);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TalkgroupInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTalkgroupInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tg = Talkgroup.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.systemName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.group = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.alphaTag = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.frequency = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.tags.push(reader.string());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.metadata = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.learned = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TalkgroupInfo {
    return {
      tg: isSet(object.tg) ? Talkgroup.fromJSON(object.tg) : undefined,
      systemName: isSet(object.systemName) ? globalThis.String(object.systemName) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      group: isSet(object.group) ? globalThis.String(object.group) : undefined,
      alphaTag: isSet(object.alphaTag) ? globalThis.String(object.alphaTag) : undefined,
      frequency: isSet(object.frequency) ? globalThis.Number(object.frequency) : undefined,
      tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => globalThis.String(e)) : [],
      metadata: isObject(object.metadata) ? object.metadata : undefined,
      learned: isSet(object.learned) ? globalThis.Boolean(object.learned) : false,
    };
  },

  toJSON(message: TalkgroupInfo): unknown {
    const obj: any = {};
    if (message.tg !== undefined) {
      obj.tg = Talkgroup.toJSON(message.tg);
    }
    if (message.systemName !== "") {
      obj.systemName = message.systemName;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.group !== undefined) {
      obj.group = message.group;
    }
    if (message.alphaTag !== undefined) {
      obj.alphaTag = message.alphaTag;
    }
    if (message.frequency !== undefined) {
      obj.frequency = Math.round(message.frequency);
    }
    if (message.tags?.length) {
      obj.tags = message.tags;
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    if (message.learned !== false) {
      obj.learned = message.learned;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TalkgroupInfo>, I>>(base?: I): TalkgroupInfo {
    return TalkgroupInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TalkgroupInfo>, I>>(object: I): TalkgroupInfo {
    const message = createBaseTalkgroupInfo();
    message.tg = (object.tg !== undefined && object.tg !== null) ? Talkgroup.fromPartial(object.tg) : undefined;
    message.systemName = object.systemName ?? "";
    message.name = object.name ?? undefined;
    message.group = object.group ?? undefined;
    message.alphaTag = object.alphaTag ?? undefined;
    message.frequency = object.frequency ?? undefined;
    message.tags = object.tags?.map((e) => e) || [];
    message.metadata = object.metadata ?? undefined;
    message.learned = object.learned ?? false;
    return message;
  },
};

function createBaseLive(): Live {
  return { state: undefined, filter: undefined, calls: false, transcripts: false };
}

export const Live: MessageFns<Live> = {
  encode(message: Live, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.state !== undefined) {
      writer.uint32(8).int32(message.state);
    }
    if (message.filter !== undefined) {
      Filter.encode(message.filter, writer.uint32(18).fork()).join();
    }
    if (message.calls !== false) {
      writer.uint32(24).bool(message.calls);
    }
    if (message.transcripts !== false) {
      writer.uint32(32).bool(message.transcripts);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Live {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLive();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.filter = Filter.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.calls = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.transcripts = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Live {
    return {
      state: isSet(object.state) ? liveStateFromJSON(object.state) : undefined,
      filter: isSet(object.filter) ? Filter.fromJSON(object.filter) : undefined,
      calls: isSet(object.calls) ? globalThis.Boolean(object.calls) : false,
      transcripts: isSet(object.transcripts) ? globalThis.Boolean(object.transcripts) : false,
    };
  },

  toJSON(message: Live): unknown {
    const obj: any = {};
    if (message.state !== undefined) {
      obj.state = liveStateToJSON(message.state);
    }
    if (message.filter !== undefined) {
      obj.filter = Filter.toJSON(message.filter);
    }
    if (message.calls !== false) {
      obj.calls = message.calls;
    }
    if (message.transcripts !== false) {
      obj.transcripts = message.transcripts;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Live>, I>>(base?: I): Live {
    return Live.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Live>, I>>(object: I): Live {
    const message = createBaseLive();
    message.state = object.state ?? undefined;
    message.filter = (object.filter !== undefined && object.filter !== null)
      ? Filter.fromPartial(object.filter)
      : undefined;
    message.calls = object.calls ?? false;
    message.transcripts = object.transcripts ?? false;
    return message;
  },
};

function createBaseTalkgroup(): Talkgroup {
  return { system: 0, talkgroup: 0 };
}

export const Talkgroup: MessageFns<Talkgroup> = {
  encode(message: Talkgroup, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.system !== 0) {
      writer.uint32(8).int32(message.system);
    }
    if (message.talkgroup !== 0) {
      writer.uint32(16).int32(message.talkgroup);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Talkgroup {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTalkgroup();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.system = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.talkgroup = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Talkgroup {
    return {
      system: isSet(object.system) ? globalThis.Number(object.system) : 0,
      talkgroup: isSet(object.talkgroup) ? globalThis.Number(object.talkgroup) : 0,
    };
  },

  toJSON(message: Talkgroup): unknown {
    const obj: any = {};
    if (message.system !== 0) {
      obj.system = Math.round(message.system);
    }
    if (message.talkgroup !== 0) {
      obj.talkgroup = Math.round(message.talkgroup);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Talkgroup>, I>>(base?: I): Talkgroup {
    return Talkgroup.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Talkgroup>, I>>(object: I): Talkgroup {
    const message = createBaseTalkgroup();
    message.system = object.system ?? 0;
    message.talkgroup = object.talkgroup ?? 0;
    return message;
  },
};

function createBaseFilter(): Filter {
  return { talkgroups: [], talkgroupsNot: [], talkgroupTagsAll: [], talkgroupTagsAny: [], talkgroupTagsNot: [] };
}

export const Filter: MessageFns<Filter> = {
  encode(message: Filter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.talkgroups) {
      Talkgroup.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.talkgroupsNot) {
      Talkgroup.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.talkgroupTagsAll) {
      writer.uint32(26).string(v!);
    }
    for (const v of message.talkgroupTagsAny) {
      writer.uint32(34).string(v!);
    }
    for (const v of message.talkgroupTagsNot) {
      writer.uint32(42).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Filter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.talkgroups.push(Talkgroup.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.talkgroupsNot.push(Talkgroup.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.talkgroupTagsAll.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.talkgroupTagsAny.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.talkgroupTagsNot.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Filter {
    return {
      talkgroups: globalThis.Array.isArray(object?.talkgroups)
        ? object.talkgroups.map((e: any) => Talkgroup.fromJSON(e))
        : [],
      talkgroupsNot: globalThis.Array.isArray(object?.talkgroupsNot)
        ? object.talkgroupsNot.map((e: any) => Talkgroup.fromJSON(e))
        : [],
      talkgroupTagsAll: globalThis.Array.isArray(object?.talkgroupTagsAll)
        ? object.talkgroupTagsAll.map((e: any) => globalThis.String(e))
        : [],
      talkgroupTagsAny: globalThis.Array.isArray(object?.talkgroupTagsAny)
        ? object.talkgroupTagsAny.map((e: any) => globalThis.String(e))
        : [],
      talkgroupTagsNot: globalThis.Array.isArray(object?.talkgroupTagsNot)
        ? object.talkgroupTagsNot.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: Filter): unknown {
    const obj: any = {};
    if (message.talkgroups?.length) {
      obj.talkgroups = message.talkgroups.map((e) => Talkgroup.toJSON(e));
    }
    if (message.talkgroupsNot?.length) {
      obj.talkgroupsNot = message.talkgroupsNot.map((e) => Talkgroup.toJSON(e));
    }
    if (message.talkgroupTagsAll?.length) {
      obj.talkgroupTagsAll = message.talkgroupTagsAll;
    }
    if (message.talkgroupTagsAny?.length) {
      obj.talkgroupTagsAny = message.talkgroupTagsAny;
    }
    if (message.talkgroupTagsNot?.length) {
      obj.talkgroupTagsNot = message.talkgroupTagsNot;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Filter>, I>>(base?: I): Filter {
    return Filter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Filter>, I>>(object: I): Filter {
    const message = createBaseFilter();
    message.talkgroups = object.talkgroups?.map((e) => Talkgroup.fromPartial(e)) || [];
    message.talkgroupsNot = object.talkgroupsNot?.map((e) => Talkgroup.fromPartial(e)) || [];
    message.talkgroupTagsAll = object.talkgroupTagsAll?.map((e) => e) || [];
    message.talkgroupTagsAny = object.talkgroupTagsAny?.map((e) => e) || [];
    message.talkgroupTagsNot = object.talkgroupTagsNot?.map((e) => e) || [];
    return message;
  },
};

function createBaseSearch(): Search {
  return {};
}

export const Search: MessageFns<Search> = {
  encode(_: Search, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Search {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearch();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Search {
    return {};
  },

  toJSON(_: Search): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Search>, I>>(base?: I): Search {
    return Search.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Search>, I>>(_: I): Search {
    const message = createBaseSearch();
    return message;
  },
};

function createBaseServerInfo(): ServerInfo {
  return { serverName: "", version: "", built: "", platform: "", dbSize: "" };
}

export const ServerInfo: MessageFns<ServerInfo> = {
  encode(message: ServerInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverName !== "") {
      writer.uint32(10).string(message.serverName);
    }
    if (message.version !== "") {
      writer.uint32(18).string(message.version);
    }
    if (message.built !== "") {
      writer.uint32(26).string(message.built);
    }
    if (message.platform !== "") {
      writer.uint32(34).string(message.platform);
    }
    if (message.dbSize !== "") {
      writer.uint32(42).string(message.dbSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.version = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.built = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.platform = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.dbSize = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerInfo {
    return {
      serverName: isSet(object.serverName) ? globalThis.String(object.serverName) : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      built: isSet(object.built) ? globalThis.String(object.built) : "",
      platform: isSet(object.platform) ? globalThis.String(object.platform) : "",
      dbSize: isSet(object.dbSize) ? globalThis.String(object.dbSize) : "",
    };
  },

  toJSON(message: ServerInfo): unknown {
    const obj: any = {};
    if (message.serverName !== "") {
      obj.serverName = message.serverName;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.built !== "") {
      obj.built = message.built;
    }
    if (message.platform !== "") {
      obj.platform = message.platform;
    }
    if (message.dbSize !== "") {
      obj.dbSize = message.dbSize;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerInfo>, I>>(base?: I): ServerInfo {
    return ServerInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerInfo>, I>>(object: I): ServerInfo {
    const message = createBaseServerInfo();
    message.serverName = object.serverName ?? "";
    message.version = object.version ?? "";
    message.built = object.built ?? "";
    message.platform = object.platform ?? "";
    message.dbSize = object.dbSize ?? "";
    return message;
  },
};

function createBaseCallTranscribeRequest(): CallTranscribeRequest {
  return { call: undefined, callback: "", token: "" };
}

export const CallTranscribeRequest: MessageFns<CallTranscribeRequest> = {
  encode(message: CallTranscribeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.call !== undefined) {
      Call.encode(message.call, writer.uint32(10).fork()).join();
    }
    if (message.callback !== "") {
      writer.uint32(18).string(message.callback);
    }
    if (message.token !== "") {
      writer.uint32(26).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallTranscribeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallTranscribeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.call = Call.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.callback = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallTranscribeRequest {
    return {
      call: isSet(object.call) ? Call.fromJSON(object.call) : undefined,
      callback: isSet(object.callback) ? globalThis.String(object.callback) : "",
      token: isSet(object.token) ? globalThis.String(object.token) : "",
    };
  },

  toJSON(message: CallTranscribeRequest): unknown {
    const obj: any = {};
    if (message.call !== undefined) {
      obj.call = Call.toJSON(message.call);
    }
    if (message.callback !== "") {
      obj.callback = message.callback;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallTranscribeRequest>, I>>(base?: I): CallTranscribeRequest {
    return CallTranscribeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallTranscribeRequest>, I>>(object: I): CallTranscribeRequest {
    const message = createBaseCallTranscribeRequest();
    message.call = (object.call !== undefined && object.call !== null) ? Call.fromPartial(object.call) : undefined;
    message.callback = object.callback ?? "";
    message.token = object.token ?? "";
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
