// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: calls.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAlert = `-- name: AddAlert :exec
INSERT INTO alerts (id, time, talkgroup, weight, score, metadata)
VALUES
(
	$1,
	$2,
	$3,
	$4,
	$5,
	$6
)
`

type AddAlertParams struct {
	ID       uuid.UUID          `json:"id"`
	Time     pgtype.Timestamptz `json:"time"`
	PackedTg int64              `json:"packed_tg"`
	Weight   *float32           `json:"weight"`
	Score    *float32           `json:"score"`
	Metadata []byte             `json:"metadata"`
}

func (q *Queries) AddAlert(ctx context.Context, arg AddAlertParams) error {
	_, err := q.db.Exec(ctx, addAlert,
		arg.ID,
		arg.Time,
		arg.PackedTg,
		arg.Weight,
		arg.Score,
		arg.Metadata,
	)
	return err
}

const addCall = `-- name: AddCall :one
INSERT INTO calls (
	id,
	submitter,
	system,
	talkgroup,
	call_date,
	audio_name,
	audio_blob,
	audio_type,
	audio_url,
	duration,
	frequency,
	frequencies,
	patches,
	tg_label,
	tg_alpha_tag,
	tg_group,
	source
	) VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16) 
RETURNING id
`

type AddCallParams struct {
	Submitter   *int32             `json:"submitter"`
	System      int                `json:"system"`
	Talkgroup   int                `json:"talkgroup"`
	CallDate    pgtype.Timestamptz `json:"call_date"`
	AudioName   *string            `json:"audio_name"`
	AudioBlob   []byte             `json:"audio_blob"`
	AudioType   *string            `json:"audio_type"`
	AudioUrl    *string            `json:"audio_url"`
	Duration    *int32             `json:"duration"`
	Frequency   int                `json:"frequency"`
	Frequencies []int              `json:"frequencies"`
	Patches     []int              `json:"patches"`
	TgLabel     *string            `json:"tg_label"`
	TgAlphaTag  *string            `json:"tg_alpha_tag"`
	TgGroup     *string            `json:"tg_group"`
	Source      int                `json:"source"`
}

func (q *Queries) AddCall(ctx context.Context, arg AddCallParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, addCall,
		arg.Submitter,
		arg.System,
		arg.Talkgroup,
		arg.CallDate,
		arg.AudioName,
		arg.AudioBlob,
		arg.AudioType,
		arg.AudioUrl,
		arg.Duration,
		arg.Frequency,
		arg.Frequencies,
		arg.Patches,
		arg.TgLabel,
		arg.TgAlphaTag,
		arg.TgGroup,
		arg.Source,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getDatabaseSize = `-- name: GetDatabaseSize :one
SELECT pg_size_pretty(pg_database_size(current_database()))
`

func (q *Queries) GetDatabaseSize(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getDatabaseSize)
	var pg_size_pretty string
	err := row.Scan(&pg_size_pretty)
	return pg_size_pretty, err
}

const setCallTranscript = `-- name: SetCallTranscript :exec
UPDATE calls SET transcript = $2 WHERE id = $1
`

func (q *Queries) SetCallTranscript(ctx context.Context, iD uuid.UUID, transcript *string) error {
	_, err := q.db.Exec(ctx, setCallTranscript, iD, transcript)
	return err
}
