// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        int32            `json:"id"`
	Owner     *int32           `json:"owner"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Expires   pgtype.Timestamp `json:"expires"`
	Disabled  *bool            `json:"disabled"`
	ApiKey    uuid.UUID        `json:"api_key"`
}

type Call struct {
	ID          uuid.UUID        `json:"id"`
	Submitter   *int32           `json:"submitter"`
	System      int              `json:"system"`
	Talkgroup   int              `json:"talkgroup"`
	CallDate    pgtype.Timestamp `json:"call_date"`
	AudioName   *string          `json:"audio_name"`
	AudioBlob   []byte           `json:"audio_blob"`
	AudioType   *string          `json:"audio_type"`
	AudioUrl    *string          `json:"audio_url"`
	Frequency   *int32           `json:"frequency"`
	Frequencies []byte           `json:"frequencies"`
	Patches     []byte           `json:"patches"`
	TgLabel     *string          `json:"tg_label"`
	Source      *string          `json:"source"`
	Transcript  *string          `json:"transcript"`
}

type Incident struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	StartTime   pgtype.Timestamp `json:"start_time"`
	EndTime     pgtype.Timestamp `json:"end_time"`
	Location    []byte           `json:"location"`
	Metadata    []byte           `json:"metadata"`
}

type IncidentsCall struct {
	IncidentID uuid.UUID `json:"incident_id"`
	CallID     uuid.UUID `json:"call_id"`
	Notes      []byte    `json:"notes"`
}

type Setting struct {
	Name      string `json:"name"`
	UpdatedBy *int32 `json:"updated_by"`
	Value     []byte `json:"value"`
}

type System struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type Talkgroup struct {
	SystemID    int     `json:"system_id"`
	Tgid        int     `json:"tgid"`
	Name        *string `json:"name"`
	Frequency   *int32  `json:"frequency"`
	AutoCreated *bool   `json:"auto_created"`
	Metadata    []byte  `json:"metadata"`
}

type TalkgroupsTag struct {
	SystemID    int      `json:"system_id"`
	TalkgroupID int      `json:"talkgroup_id"`
	Tags        []string `json:"tags"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	IsAdmin  *bool  `json:"is_admin"`
	Prefs    []byte `json:"prefs"`
}
