// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        int32
	Owner     pgtype.Int4
	CreatedAt pgtype.Timestamp
	Expires   pgtype.Timestamp
	Disabled  pgtype.Bool
	ApiKey    uuid.UUID
}

type Call struct {
	ID          uuid.UUID
	Submitter   pgtype.Int4
	System      int32
	Talkgroup   int32
	CallDate    pgtype.Timestamp
	AudioName   pgtype.Text
	AudioBlob   []byte
	AudioType   pgtype.Text
	AudioUrl    pgtype.Text
	Frequency   pgtype.Int4
	Frequencies []byte
	Patches     []byte
	TgLabel     pgtype.Text
	Source      pgtype.Text
	Transcript  pgtype.Text
}

type Incident struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
	StartTime   pgtype.Timestamp
	EndTime     pgtype.Timestamp
	Location    []byte
	Metadata    []byte
}

type IncidentsCall struct {
	IncidentID uuid.UUID
	CallID     uuid.UUID
	Notes      []byte
}

type Setting struct {
	Name      string
	UpdatedBy pgtype.Int4
	Value     []byte
}

type System struct {
	ID   int32
	Name string
}

type Talkgroup struct {
	SystemID    int32
	Tgid        int32
	Name        pgtype.Text
	Frequency   pgtype.Int4
	AutoCreated pgtype.Bool
	Metadata    []byte
}

type TalkgroupsTag struct {
	SystemID    int32
	TalkgroupID int32
	Tags        []string
}

type User struct {
	ID       int32
	Username string
	Password string
	Email    string
	IsAdmin  pgtype.Bool
	Prefs    []byte
}
