// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID        uuid.UUID          `json:"id"`
	Time      pgtype.Timestamptz `json:"time"`
	Talkgroup int64              `json:"talkgroup"`
	SystemID  int32              `json:"system_id"`
	Tgid      int32              `json:"tgid"`
	Weight    *float32           `json:"weight"`
	Score     *float32           `json:"score"`
	Metadata  []byte             `json:"metadata"`
}

type ApiKey struct {
	ID        int32            `json:"id"`
	Owner     int              `json:"owner"`
	CreatedAt time.Time        `json:"created_at"`
	Expires   pgtype.Timestamp `json:"expires"`
	Disabled  *bool            `json:"disabled"`
	ApiKey    string           `json:"api_key"`
}

type Call struct {
	ID          uuid.UUID          `json:"id"`
	Submitter   *int32             `json:"submitter"`
	System      int                `json:"system"`
	Talkgroup   int                `json:"talkgroup"`
	CallDate    pgtype.Timestamptz `json:"call_date"`
	AudioName   *string            `json:"audio_name"`
	AudioBlob   []byte             `json:"audio_blob"`
	Duration    *int32             `json:"duration"`
	AudioType   *string            `json:"audio_type"`
	AudioUrl    *string            `json:"audio_url"`
	Frequency   int                `json:"frequency"`
	Frequencies []int              `json:"frequencies"`
	Patches     []int              `json:"patches"`
	TgLabel     *string            `json:"tg_label"`
	TgAlphaTag  *string            `json:"tg_alpha_tag"`
	TgGroup     *string            `json:"tg_group"`
	Source      int                `json:"source"`
	Transcript  *string            `json:"transcript"`
}

type Incident struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	StartTime   pgtype.Timestamp `json:"start_time"`
	EndTime     pgtype.Timestamp `json:"end_time"`
	Location    []byte           `json:"location"`
	Metadata    []byte           `json:"metadata"`
}

type IncidentsCall struct {
	IncidentID uuid.UUID `json:"incident_id"`
	CallID     uuid.UUID `json:"call_id"`
	Notes      []byte    `json:"notes"`
}

type Setting struct {
	Name      string `json:"name"`
	UpdatedBy *int32 `json:"updated_by"`
	Value     []byte `json:"value"`
}

type System struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type Talkgroup struct {
	ID          int64    `json:"id"`
	SystemID    int32    `json:"system_id"`
	Tgid        int32    `json:"tgid"`
	Name        *string  `json:"name"`
	AlphaTag    *string  `json:"alpha_tag"`
	TgGroup     *string  `json:"tg_group"`
	Frequency   *int32   `json:"frequency"`
	Metadata    []byte   `json:"metadata"`
	Tags        []string `json:"tags"`
	Alert       bool     `json:"alert"`
	AlertConfig []byte   `json:"alert_config"`
	Weight      float32  `json:"weight"`
}

type TalkgroupsLearned struct {
	ID       int32   `json:"id"`
	SystemID int     `json:"system_id"`
	Tgid     int     `json:"tgid"`
	Name     string  `json:"name"`
	AlphaTag *string `json:"alpha_tag"`
	Ignored  *bool   `json:"ignored"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	IsAdmin  bool   `json:"is_admin"`
	Prefs    []byte `json:"prefs"`
}
