// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddCall(ctx context.Context, arg AddCallParams) (uuid.UUID, error)
	CreateAPIKey(ctx context.Context, owner int, expires pgtype.Timestamp, disabled *bool) (ApiKey, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIKey(ctx context.Context, apiKey string) error
	DeleteUser(ctx context.Context, username string) error
	GetAPIKey(ctx context.Context, apiKey string) (ApiKey, error)
	GetTalkgroupTags(ctx context.Context, systemID int, tgid int) ([]string, error)
	GetTalkgroupsWithAllTags(ctx context.Context, tags []string) ([]Talkgroup, error)
	GetTalkgroupsWithAnyTags(ctx context.Context, tags []string) ([]Talkgroup, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	SetCallTranscript(ctx context.Context, iD uuid.UUID, transcript *string) error
	SetTalkgroupTags(ctx context.Context, tags []string, tgid int) error
	UpdatePassword(ctx context.Context, username string, password string) error
}

var _ Querier = (*Queries)(nil)
