// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: stillbox.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LiveState int32

const (
	LiveState_LS_STOPPED LiveState = 0
	LiveState_LS_LIVE    LiveState = 1
	LiveState_LS_PAUSED  LiveState = 2
)

// Enum value maps for LiveState.
var (
	LiveState_name = map[int32]string{
		0: "LS_STOPPED",
		1: "LS_LIVE",
		2: "LS_PAUSED",
	}
	LiveState_value = map[string]int32{
		"LS_STOPPED": 0,
		"LS_LIVE":    1,
		"LS_PAUSED":  2,
	}
)

func (x LiveState) Enum() *LiveState {
	p := new(LiveState)
	*p = x
	return p
}

func (x LiveState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LiveState) Descriptor() protoreflect.EnumDescriptor {
	return file_stillbox_proto_enumTypes[0].Descriptor()
}

func (LiveState) Type() protoreflect.EnumType {
	return &file_stillbox_proto_enumTypes[0]
}

func (x LiveState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LiveState.Descriptor instead.
func (LiveState) EnumDescriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ToClientMessage:
	//
	//	*Message_Response
	//	*Message_Call
	//	*Message_Transcription
	//	*Message_Notification
	//	*Message_Popup
	//	*Message_Error
	//	*Message_Hello
	ToClientMessage isMessage_ToClientMessage `protobuf_oneof:"toClient_message"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_stillbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetToClientMessage() isMessage_ToClientMessage {
	if x != nil {
		return x.ToClientMessage
	}
	return nil
}

func (x *Message) GetResponse() *CommandResponse {
	if x != nil {
		if x, ok := x.ToClientMessage.(*Message_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Message) GetCall() *Call {
	if x != nil {
		if x, ok := x.ToClientMessage.(*Message_Call); ok {
			return x.Call
		}
	}
	return nil
}

func (x *Message) GetTranscription() *CallTranscription {
	if x != nil {
		if x, ok := x.ToClientMessage.(*Message_Transcription); ok {
			return x.Transcription
		}
	}
	return nil
}

func (x *Message) GetNotification() *Notification {
	if x != nil {
		if x, ok := x.ToClientMessage.(*Message_Notification); ok {
			return x.Notification
		}
	}
	return nil
}

func (x *Message) GetPopup() *UserPopup {
	if x != nil {
		if x, ok := x.ToClientMessage.(*Message_Popup); ok {
			return x.Popup
		}
	}
	return nil
}

func (x *Message) GetError() *Error {
	if x != nil {
		if x, ok := x.ToClientMessage.(*Message_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Message) GetHello() *Hello {
	if x != nil {
		if x, ok := x.ToClientMessage.(*Message_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

type isMessage_ToClientMessage interface {
	isMessage_ToClientMessage()
}

type Message_Response struct {
	Response *CommandResponse `protobuf:"bytes,1,opt,name=response,proto3,oneof"`
}

type Message_Call struct {
	Call *Call `protobuf:"bytes,2,opt,name=call,proto3,oneof"`
}

type Message_Transcription struct {
	Transcription *CallTranscription `protobuf:"bytes,3,opt,name=transcription,proto3,oneof"`
}

type Message_Notification struct {
	Notification *Notification `protobuf:"bytes,4,opt,name=notification,proto3,oneof"`
}

type Message_Popup struct {
	Popup *UserPopup `protobuf:"bytes,5,opt,name=popup,proto3,oneof"`
}

type Message_Error struct {
	Error *Error `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

type Message_Hello struct {
	Hello *Hello `protobuf:"bytes,7,opt,name=hello,proto3,oneof"`
}

func (*Message_Response) isMessage_ToClientMessage() {}

func (*Message_Call) isMessage_ToClientMessage() {}

func (*Message_Transcription) isMessage_ToClientMessage() {}

func (*Message_Notification) isMessage_ToClientMessage() {}

func (*Message_Popup) isMessage_ToClientMessage() {}

func (*Message_Error) isMessage_ToClientMessage() {}

func (*Message_Hello) isMessage_ToClientMessage() {}

type CommandResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId *int64                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3,oneof" json:"command_id,omitempty"`
	// Types that are valid to be assigned to CommandResponse:
	//
	//	*CommandResponse_TgInfo
	CommandResponse isCommandResponse_CommandResponse `protobuf_oneof:"command_response"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_stillbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetCommandId() int64 {
	if x != nil && x.CommandId != nil {
		return *x.CommandId
	}
	return 0
}

func (x *CommandResponse) GetCommandResponse() isCommandResponse_CommandResponse {
	if x != nil {
		return x.CommandResponse
	}
	return nil
}

func (x *CommandResponse) GetTgInfo() *TalkgroupInfo {
	if x != nil {
		if x, ok := x.CommandResponse.(*CommandResponse_TgInfo); ok {
			return x.TgInfo
		}
	}
	return nil
}

type isCommandResponse_CommandResponse interface {
	isCommandResponse_CommandResponse()
}

type CommandResponse_TgInfo struct {
	TgInfo *TalkgroupInfo `protobuf:"bytes,2,opt,name=tg_info,json=tgInfo,proto3,oneof"`
}

func (*CommandResponse_TgInfo) isCommandResponse_CommandResponse() {}

type Call struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AudioName     string                 `protobuf:"bytes,2,opt,name=audioName,proto3" json:"audioName,omitempty"`
	AudioType     string                 `protobuf:"bytes,3,opt,name=audioType,proto3" json:"audioType,omitempty"`
	DateTime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	System        int32                  `protobuf:"varint,5,opt,name=system,proto3" json:"system,omitempty"`
	Talkgroup     int32                  `protobuf:"varint,6,opt,name=talkgroup,proto3" json:"talkgroup,omitempty"`
	TalkerAlias   *string                `protobuf:"bytes,7,opt,name=talker_alias,json=talkerAlias,proto3,oneof" json:"talker_alias,omitempty"`
	Source        int32                  `protobuf:"varint,8,opt,name=source,proto3" json:"source,omitempty"`
	Frequency     int64                  `protobuf:"varint,9,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Frequencies   []int64                `protobuf:"varint,10,rep,packed,name=frequencies,proto3" json:"frequencies,omitempty"`
	Patches       []int32                `protobuf:"varint,11,rep,packed,name=patches,proto3" json:"patches,omitempty"`
	Duration      *int32                 `protobuf:"varint,12,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	Audio         []byte                 `protobuf:"bytes,13,opt,name=audio,proto3" json:"audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Call) Reset() {
	*x = Call{}
	mi := &file_stillbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{2}
}

func (x *Call) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Call) GetAudioName() string {
	if x != nil {
		return x.AudioName
	}
	return ""
}

func (x *Call) GetAudioType() string {
	if x != nil {
		return x.AudioType
	}
	return ""
}

func (x *Call) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *Call) GetSystem() int32 {
	if x != nil {
		return x.System
	}
	return 0
}

func (x *Call) GetTalkgroup() int32 {
	if x != nil {
		return x.Talkgroup
	}
	return 0
}

func (x *Call) GetTalkerAlias() string {
	if x != nil && x.TalkerAlias != nil {
		return *x.TalkerAlias
	}
	return ""
}

func (x *Call) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *Call) GetFrequency() int64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *Call) GetFrequencies() []int64 {
	if x != nil {
		return x.Frequencies
	}
	return nil
}

func (x *Call) GetPatches() []int32 {
	if x != nil {
		return x.Patches
	}
	return nil
}

func (x *Call) GetDuration() int32 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *Call) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

type CallTranscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	System        int32                  `protobuf:"varint,2,opt,name=system,proto3" json:"system,omitempty"`
	Talkgroup     int32                  `protobuf:"varint,3,opt,name=talkgroup,proto3" json:"talkgroup,omitempty"`
	Patches       []int32                `protobuf:"varint,4,rep,packed,name=patches,proto3" json:"patches,omitempty"`
	Transcript    string                 `protobuf:"bytes,5,opt,name=transcript,proto3" json:"transcript,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallTranscription) Reset() {
	*x = CallTranscription{}
	mi := &file_stillbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallTranscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallTranscription) ProtoMessage() {}

func (x *CallTranscription) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallTranscription.ProtoReflect.Descriptor instead.
func (*CallTranscription) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{3}
}

func (x *CallTranscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CallTranscription) GetSystem() int32 {
	if x != nil {
		return x.System
	}
	return 0
}

func (x *CallTranscription) GetTalkgroup() int32 {
	if x != nil {
		return x.Talkgroup
	}
	return 0
}

func (x *CallTranscription) GetPatches() []int32 {
	if x != nil {
		return x.Patches
	}
	return nil
}

func (x *CallTranscription) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerInfo    *ServerInfo            `protobuf:"bytes,1,opt,name=server_info,json=serverInfo,proto3" json:"server_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_stillbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{4}
}

func (x *Hello) GetServerInfo() *ServerInfo {
	if x != nil {
		return x.ServerInfo
	}
	return nil
}

type UserPopup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPopup) Reset() {
	*x = UserPopup{}
	mi := &file_stillbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPopup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPopup) ProtoMessage() {}

func (x *UserPopup) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPopup.ProtoReflect.Descriptor instead.
func (*UserPopup) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{5}
}

func (x *UserPopup) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Command       *Command               `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_stillbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Error) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DateTime      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	ActionUrl     string                 `protobuf:"bytes,4,opt,name=action_url,json=actionUrl,proto3" json:"action_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_stillbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{7}
}

func (x *Notification) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Notification) GetActionUrl() string {
	if x != nil {
		return x.ActionUrl
	}
	return ""
}

type Command struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId *int64                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3,oneof" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*Command_LiveCommand
	//	*Command_SearchCommand
	//	*Command_TgCommand
	//	*Command_RegisterCommand
	//	*Command_SetTranscript
	Command       isCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_stillbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{8}
}

func (x *Command) GetCommandId() int64 {
	if x != nil && x.CommandId != nil {
		return *x.CommandId
	}
	return 0
}

func (x *Command) GetCommand() isCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Command) GetLiveCommand() *Live {
	if x != nil {
		if x, ok := x.Command.(*Command_LiveCommand); ok {
			return x.LiveCommand
		}
	}
	return nil
}

func (x *Command) GetSearchCommand() *Search {
	if x != nil {
		if x, ok := x.Command.(*Command_SearchCommand); ok {
			return x.SearchCommand
		}
	}
	return nil
}

func (x *Command) GetTgCommand() *Talkgroup {
	if x != nil {
		if x, ok := x.Command.(*Command_TgCommand); ok {
			return x.TgCommand
		}
	}
	return nil
}

func (x *Command) GetRegisterCommand() *Register {
	if x != nil {
		if x, ok := x.Command.(*Command_RegisterCommand); ok {
			return x.RegisterCommand
		}
	}
	return nil
}

func (x *Command) GetSetTranscript() *SetTranscript {
	if x != nil {
		if x, ok := x.Command.(*Command_SetTranscript); ok {
			return x.SetTranscript
		}
	}
	return nil
}

type isCommand_Command interface {
	isCommand_Command()
}

type Command_LiveCommand struct {
	LiveCommand *Live `protobuf:"bytes,2,opt,name=live_command,json=liveCommand,proto3,oneof"`
}

type Command_SearchCommand struct {
	SearchCommand *Search `protobuf:"bytes,3,opt,name=search_command,json=searchCommand,proto3,oneof"`
}

type Command_TgCommand struct {
	TgCommand *Talkgroup `protobuf:"bytes,4,opt,name=tg_command,json=tgCommand,proto3,oneof"`
}

type Command_RegisterCommand struct {
	RegisterCommand *Register `protobuf:"bytes,5,opt,name=register_command,json=registerCommand,proto3,oneof"`
}

type Command_SetTranscript struct {
	SetTranscript *SetTranscript `protobuf:"bytes,6,opt,name=set_transcript,json=setTranscript,proto3,oneof"`
}

func (*Command_LiveCommand) isCommand_Command() {}

func (*Command_SearchCommand) isCommand_Command() {}

func (*Command_TgCommand) isCommand_Command() {}

func (*Command_RegisterCommand) isCommand_Command() {}

func (*Command_SetTranscript) isCommand_Command() {}

type TalkgroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tg            *Talkgroup             `protobuf:"bytes,1,opt,name=tg,proto3" json:"tg,omitempty"`
	SystemName    string                 `protobuf:"bytes,2,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Group         *string                `protobuf:"bytes,4,opt,name=group,proto3,oneof" json:"group,omitempty"`
	AlphaTag      *string                `protobuf:"bytes,5,opt,name=alpha_tag,json=alphaTag,proto3,oneof" json:"alpha_tag,omitempty"`
	Frequency     *int32                 `protobuf:"varint,6,opt,name=frequency,proto3,oneof" json:"frequency,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,8,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	Learned       bool                   `protobuf:"varint,9,opt,name=learned,proto3" json:"learned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TalkgroupInfo) Reset() {
	*x = TalkgroupInfo{}
	mi := &file_stillbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TalkgroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkgroupInfo) ProtoMessage() {}

func (x *TalkgroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkgroupInfo.ProtoReflect.Descriptor instead.
func (*TalkgroupInfo) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{9}
}

func (x *TalkgroupInfo) GetTg() *Talkgroup {
	if x != nil {
		return x.Tg
	}
	return nil
}

func (x *TalkgroupInfo) GetSystemName() string {
	if x != nil {
		return x.SystemName
	}
	return ""
}

func (x *TalkgroupInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TalkgroupInfo) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *TalkgroupInfo) GetAlphaTag() string {
	if x != nil && x.AlphaTag != nil {
		return *x.AlphaTag
	}
	return ""
}

func (x *TalkgroupInfo) GetFrequency() int32 {
	if x != nil && x.Frequency != nil {
		return *x.Frequency
	}
	return 0
}

func (x *TalkgroupInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TalkgroupInfo) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TalkgroupInfo) GetLearned() bool {
	if x != nil {
		return x.Learned
	}
	return false
}

type Live struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *LiveState             `protobuf:"varint,1,opt,name=state,proto3,enum=stillbox.LiveState,oneof" json:"state,omitempty"`
	Filter        *Filter                `protobuf:"bytes,2,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	Calls         bool                   `protobuf:"varint,3,opt,name=calls,proto3" json:"calls,omitempty"`
	Transcripts   bool                   `protobuf:"varint,4,opt,name=transcripts,proto3" json:"transcripts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Live) Reset() {
	*x = Live{}
	mi := &file_stillbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Live) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Live) ProtoMessage() {}

func (x *Live) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Live.ProtoReflect.Descriptor instead.
func (*Live) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{10}
}

func (x *Live) GetState() LiveState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return LiveState_LS_STOPPED
}

func (x *Live) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *Live) GetCalls() bool {
	if x != nil {
		return x.Calls
	}
	return false
}

func (x *Live) GetTranscripts() bool {
	if x != nil {
		return x.Transcripts
	}
	return false
}

type Register struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TranscriptWorker bool                   `protobuf:"varint,1,opt,name=transcript_worker,json=transcriptWorker,proto3" json:"transcript_worker,omitempty"`
	WorkerKey        string                 `protobuf:"bytes,2,opt,name=worker_key,json=workerKey,proto3" json:"worker_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_stillbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{11}
}

func (x *Register) GetTranscriptWorker() bool {
	if x != nil {
		return x.TranscriptWorker
	}
	return false
}

func (x *Register) GetWorkerKey() string {
	if x != nil {
		return x.WorkerKey
	}
	return ""
}

type Talkgroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        int32                  `protobuf:"varint,1,opt,name=system,proto3" json:"system,omitempty"`
	Talkgroup     int32                  `protobuf:"varint,2,opt,name=talkgroup,proto3" json:"talkgroup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Talkgroup) Reset() {
	*x = Talkgroup{}
	mi := &file_stillbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Talkgroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Talkgroup) ProtoMessage() {}

func (x *Talkgroup) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Talkgroup.ProtoReflect.Descriptor instead.
func (*Talkgroup) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{12}
}

func (x *Talkgroup) GetSystem() int32 {
	if x != nil {
		return x.System
	}
	return 0
}

func (x *Talkgroup) GetTalkgroup() int32 {
	if x != nil {
		return x.Talkgroup
	}
	return 0
}

type Filter struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Talkgroups       []*Talkgroup           `protobuf:"bytes,1,rep,name=talkgroups,proto3" json:"talkgroups,omitempty"`
	TalkgroupsNot    []*Talkgroup           `protobuf:"bytes,2,rep,name=talkgroups_not,json=talkgroupsNot,proto3" json:"talkgroups_not,omitempty"`
	TalkgroupTagsAll []string               `protobuf:"bytes,3,rep,name=talkgroup_tags_all,json=talkgroupTagsAll,proto3" json:"talkgroup_tags_all,omitempty"`
	TalkgroupTagsAny []string               `protobuf:"bytes,4,rep,name=talkgroup_tags_any,json=talkgroupTagsAny,proto3" json:"talkgroup_tags_any,omitempty"`
	TalkgroupTagsNot []string               `protobuf:"bytes,5,rep,name=talkgroup_tags_not,json=talkgroupTagsNot,proto3" json:"talkgroup_tags_not,omitempty"`
	All              bool                   `protobuf:"varint,6,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_stillbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{13}
}

func (x *Filter) GetTalkgroups() []*Talkgroup {
	if x != nil {
		return x.Talkgroups
	}
	return nil
}

func (x *Filter) GetTalkgroupsNot() []*Talkgroup {
	if x != nil {
		return x.TalkgroupsNot
	}
	return nil
}

func (x *Filter) GetTalkgroupTagsAll() []string {
	if x != nil {
		return x.TalkgroupTagsAll
	}
	return nil
}

func (x *Filter) GetTalkgroupTagsAny() []string {
	if x != nil {
		return x.TalkgroupTagsAny
	}
	return nil
}

func (x *Filter) GetTalkgroupTagsNot() []string {
	if x != nil {
		return x.TalkgroupTagsNot
	}
	return nil
}

func (x *Filter) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type Search struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search) Reset() {
	*x = Search{}
	mi := &file_stillbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search) ProtoMessage() {}

func (x *Search) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search.ProtoReflect.Descriptor instead.
func (*Search) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{14}
}

type ServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Built         string                 `protobuf:"bytes,3,opt,name=built,proto3" json:"built,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	DbSize        string                 `protobuf:"bytes,5,opt,name=db_size,json=dbSize,proto3" json:"db_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_stillbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{15}
}

func (x *ServerInfo) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfo) GetBuilt() string {
	if x != nil {
		return x.Built
	}
	return ""
}

func (x *ServerInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ServerInfo) GetDbSize() string {
	if x != nil {
		return x.DbSize
	}
	return ""
}

type SetTranscript struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Transcript    string                 `protobuf:"bytes,2,opt,name=transcript,proto3" json:"transcript,omitempty"`
	ElapsedMs     *int64                 `protobuf:"varint,3,opt,name=elapsed_ms,json=elapsedMs,proto3,oneof" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTranscript) Reset() {
	*x = SetTranscript{}
	mi := &file_stillbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTranscript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTranscript) ProtoMessage() {}

func (x *SetTranscript) ProtoReflect() protoreflect.Message {
	mi := &file_stillbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTranscript.ProtoReflect.Descriptor instead.
func (*SetTranscript) Descriptor() ([]byte, []int) {
	return file_stillbox_proto_rawDescGZIP(), []int{16}
}

func (x *SetTranscript) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetTranscript) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *SetTranscript) GetElapsedMs() int64 {
	if x != nil && x.ElapsedMs != nil {
		return *x.ElapsedMs
	}
	return 0
}

var File_stillbox_proto protoreflect.FileDescriptor

const file_stillbox_proto_rawDesc = "" +
	"\n" +
	"\x0estillbox.proto\x12\bstillbox\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xfe\x02\n" +
	"\aMessage\x127\n" +
	"\bresponse\x18\x01 \x01(\v2\x19.stillbox.CommandResponseH\x00R\bresponse\x12$\n" +
	"\x04call\x18\x02 \x01(\v2\x0e.stillbox.CallH\x00R\x04call\x12C\n" +
	"\rtranscription\x18\x03 \x01(\v2\x1b.stillbox.CallTranscriptionH\x00R\rtranscription\x12<\n" +
	"\fnotification\x18\x04 \x01(\v2\x16.stillbox.NotificationH\x00R\fnotification\x12+\n" +
	"\x05popup\x18\x05 \x01(\v2\x13.stillbox.UserPopupH\x00R\x05popup\x12'\n" +
	"\x05error\x18\x06 \x01(\v2\x0f.stillbox.ErrorH\x00R\x05error\x12'\n" +
	"\x05hello\x18\a \x01(\v2\x0f.stillbox.HelloH\x00R\x05helloB\x12\n" +
	"\x10toClient_message\"\x8c\x01\n" +
	"\x0fCommandResponse\x12\"\n" +
	"\n" +
	"command_id\x18\x01 \x01(\x03H\x01R\tcommandId\x88\x01\x01\x122\n" +
	"\atg_info\x18\x02 \x01(\v2\x17.stillbox.TalkgroupInfoH\x00R\x06tgInfoB\x12\n" +
	"\x10command_responseB\r\n" +
	"\v_command_id\"\xb0\x03\n" +
	"\x04Call\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\taudioName\x18\x02 \x01(\tR\taudioName\x12\x1c\n" +
	"\taudioType\x18\x03 \x01(\tR\taudioType\x127\n" +
	"\tdate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12\x16\n" +
	"\x06system\x18\x05 \x01(\x05R\x06system\x12\x1c\n" +
	"\ttalkgroup\x18\x06 \x01(\x05R\ttalkgroup\x12&\n" +
	"\ftalker_alias\x18\a \x01(\tH\x00R\vtalkerAlias\x88\x01\x01\x12\x16\n" +
	"\x06source\x18\b \x01(\x05R\x06source\x12\x1c\n" +
	"\tfrequency\x18\t \x01(\x03R\tfrequency\x12 \n" +
	"\vfrequencies\x18\n" +
	" \x03(\x03R\vfrequencies\x12\x18\n" +
	"\apatches\x18\v \x03(\x05R\apatches\x12\x1f\n" +
	"\bduration\x18\f \x01(\x05H\x01R\bduration\x88\x01\x01\x12\x14\n" +
	"\x05audio\x18\r \x01(\fR\x05audioB\x0f\n" +
	"\r_talker_aliasB\v\n" +
	"\t_duration\"\x93\x01\n" +
	"\x11CallTranscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06system\x18\x02 \x01(\x05R\x06system\x12\x1c\n" +
	"\ttalkgroup\x18\x03 \x01(\x05R\ttalkgroup\x12\x18\n" +
	"\apatches\x18\x04 \x03(\x05R\apatches\x12\x1e\n" +
	"\n" +
	"transcript\x18\x05 \x01(\tR\n" +
	"transcript\">\n" +
	"\x05Hello\x125\n" +
	"\vserver_info\x18\x01 \x01(\v2\x14.stillbox.ServerInfoR\n" +
	"serverInfo\"\x1d\n" +
	"\tUserPopup\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"J\n" +
	"\x05Error\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12+\n" +
	"\acommand\x18\x02 \x01(\v2\x11.stillbox.CommandR\acommand\"\x8e\x01\n" +
	"\fNotification\x127\n" +
	"\tdate_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\x12\x1d\n" +
	"\n" +
	"action_url\x18\x04 \x01(\tR\tactionUrl\"\xf0\x02\n" +
	"\aCommand\x12\"\n" +
	"\n" +
	"command_id\x18\x01 \x01(\x03H\x01R\tcommandId\x88\x01\x01\x123\n" +
	"\flive_command\x18\x02 \x01(\v2\x0e.stillbox.LiveH\x00R\vliveCommand\x129\n" +
	"\x0esearch_command\x18\x03 \x01(\v2\x10.stillbox.SearchH\x00R\rsearchCommand\x124\n" +
	"\n" +
	"tg_command\x18\x04 \x01(\v2\x13.stillbox.TalkgroupH\x00R\ttgCommand\x12?\n" +
	"\x10register_command\x18\x05 \x01(\v2\x12.stillbox.RegisterH\x00R\x0fregisterCommand\x12@\n" +
	"\x0eset_transcript\x18\x06 \x01(\v2\x17.stillbox.SetTranscriptH\x00R\rsetTranscriptB\t\n" +
	"\acommandB\r\n" +
	"\v_command_id\"\xf2\x02\n" +
	"\rTalkgroupInfo\x12#\n" +
	"\x02tg\x18\x01 \x01(\v2\x13.stillbox.TalkgroupR\x02tg\x12\x1f\n" +
	"\vsystem_name\x18\x02 \x01(\tR\n" +
	"systemName\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05group\x18\x04 \x01(\tH\x01R\x05group\x88\x01\x01\x12 \n" +
	"\talpha_tag\x18\x05 \x01(\tH\x02R\balphaTag\x88\x01\x01\x12!\n" +
	"\tfrequency\x18\x06 \x01(\x05H\x03R\tfrequency\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x128\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructH\x04R\bmetadata\x88\x01\x01\x12\x18\n" +
	"\alearned\x18\t \x01(\bR\alearnedB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_groupB\f\n" +
	"\n" +
	"_alpha_tagB\f\n" +
	"\n" +
	"_frequencyB\v\n" +
	"\t_metadata\"\xb2\x01\n" +
	"\x04Live\x12.\n" +
	"\x05state\x18\x01 \x01(\x0e2\x13.stillbox.LiveStateH\x00R\x05state\x88\x01\x01\x12-\n" +
	"\x06filter\x18\x02 \x01(\v2\x10.stillbox.FilterH\x01R\x06filter\x88\x01\x01\x12\x14\n" +
	"\x05calls\x18\x03 \x01(\bR\x05calls\x12 \n" +
	"\vtranscripts\x18\x04 \x01(\bR\vtranscriptsB\b\n" +
	"\x06_stateB\t\n" +
	"\a_filter\"V\n" +
	"\bRegister\x12+\n" +
	"\x11transcript_worker\x18\x01 \x01(\bR\x10transcriptWorker\x12\x1d\n" +
	"\n" +
	"worker_key\x18\x02 \x01(\tR\tworkerKey\"A\n" +
	"\tTalkgroup\x12\x16\n" +
	"\x06system\x18\x01 \x01(\x05R\x06system\x12\x1c\n" +
	"\ttalkgroup\x18\x02 \x01(\x05R\ttalkgroup\"\x95\x02\n" +
	"\x06Filter\x123\n" +
	"\n" +
	"talkgroups\x18\x01 \x03(\v2\x13.stillbox.TalkgroupR\n" +
	"talkgroups\x12:\n" +
	"\x0etalkgroups_not\x18\x02 \x03(\v2\x13.stillbox.TalkgroupR\rtalkgroupsNot\x12,\n" +
	"\x12talkgroup_tags_all\x18\x03 \x03(\tR\x10talkgroupTagsAll\x12,\n" +
	"\x12talkgroup_tags_any\x18\x04 \x03(\tR\x10talkgroupTagsAny\x12,\n" +
	"\x12talkgroup_tags_not\x18\x05 \x03(\tR\x10talkgroupTagsNot\x12\x10\n" +
	"\x03all\x18\x06 \x01(\bR\x03all\"\b\n" +
	"\x06Search\"\x92\x01\n" +
	"\n" +
	"ServerInfo\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05built\x18\x03 \x01(\tR\x05built\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x17\n" +
	"\adb_size\x18\x05 \x01(\tR\x06dbSize\"r\n" +
	"\rSetTranscript\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"transcript\x18\x02 \x01(\tR\n" +
	"transcript\x12\"\n" +
	"\n" +
	"elapsed_ms\x18\x03 \x01(\x03H\x00R\telapsedMs\x88\x01\x01B\r\n" +
	"\v_elapsed_ms*7\n" +
	"\tLiveState\x12\x0e\n" +
	"\n" +
	"LS_STOPPED\x10\x00\x12\v\n" +
	"\aLS_LIVE\x10\x01\x12\r\n" +
	"\tLS_PAUSED\x10\x02B\x06Z\x04./pbb\x06proto3"

var (
	file_stillbox_proto_rawDescOnce sync.Once
	file_stillbox_proto_rawDescData []byte
)

func file_stillbox_proto_rawDescGZIP() []byte {
	file_stillbox_proto_rawDescOnce.Do(func() {
		file_stillbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stillbox_proto_rawDesc), len(file_stillbox_proto_rawDesc)))
	})
	return file_stillbox_proto_rawDescData
}

var file_stillbox_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stillbox_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_stillbox_proto_goTypes = []any{
	(LiveState)(0),                // 0: stillbox.LiveState
	(*Message)(nil),               // 1: stillbox.Message
	(*CommandResponse)(nil),       // 2: stillbox.CommandResponse
	(*Call)(nil),                  // 3: stillbox.Call
	(*CallTranscription)(nil),     // 4: stillbox.CallTranscription
	(*Hello)(nil),                 // 5: stillbox.Hello
	(*UserPopup)(nil),             // 6: stillbox.UserPopup
	(*Error)(nil),                 // 7: stillbox.Error
	(*Notification)(nil),          // 8: stillbox.Notification
	(*Command)(nil),               // 9: stillbox.Command
	(*TalkgroupInfo)(nil),         // 10: stillbox.TalkgroupInfo
	(*Live)(nil),                  // 11: stillbox.Live
	(*Register)(nil),              // 12: stillbox.Register
	(*Talkgroup)(nil),             // 13: stillbox.Talkgroup
	(*Filter)(nil),                // 14: stillbox.Filter
	(*Search)(nil),                // 15: stillbox.Search
	(*ServerInfo)(nil),            // 16: stillbox.ServerInfo
	(*SetTranscript)(nil),         // 17: stillbox.SetTranscript
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 19: google.protobuf.Struct
}
var file_stillbox_proto_depIdxs = []int32{
	2,  // 0: stillbox.Message.response:type_name -> stillbox.CommandResponse
	3,  // 1: stillbox.Message.call:type_name -> stillbox.Call
	4,  // 2: stillbox.Message.transcription:type_name -> stillbox.CallTranscription
	8,  // 3: stillbox.Message.notification:type_name -> stillbox.Notification
	6,  // 4: stillbox.Message.popup:type_name -> stillbox.UserPopup
	7,  // 5: stillbox.Message.error:type_name -> stillbox.Error
	5,  // 6: stillbox.Message.hello:type_name -> stillbox.Hello
	10, // 7: stillbox.CommandResponse.tg_info:type_name -> stillbox.TalkgroupInfo
	18, // 8: stillbox.Call.date_time:type_name -> google.protobuf.Timestamp
	16, // 9: stillbox.Hello.server_info:type_name -> stillbox.ServerInfo
	9,  // 10: stillbox.Error.command:type_name -> stillbox.Command
	18, // 11: stillbox.Notification.date_time:type_name -> google.protobuf.Timestamp
	11, // 12: stillbox.Command.live_command:type_name -> stillbox.Live
	15, // 13: stillbox.Command.search_command:type_name -> stillbox.Search
	13, // 14: stillbox.Command.tg_command:type_name -> stillbox.Talkgroup
	12, // 15: stillbox.Command.register_command:type_name -> stillbox.Register
	17, // 16: stillbox.Command.set_transcript:type_name -> stillbox.SetTranscript
	13, // 17: stillbox.TalkgroupInfo.tg:type_name -> stillbox.Talkgroup
	19, // 18: stillbox.TalkgroupInfo.metadata:type_name -> google.protobuf.Struct
	0,  // 19: stillbox.Live.state:type_name -> stillbox.LiveState
	14, // 20: stillbox.Live.filter:type_name -> stillbox.Filter
	13, // 21: stillbox.Filter.talkgroups:type_name -> stillbox.Talkgroup
	13, // 22: stillbox.Filter.talkgroups_not:type_name -> stillbox.Talkgroup
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_stillbox_proto_init() }
func file_stillbox_proto_init() {
	if File_stillbox_proto != nil {
		return
	}
	file_stillbox_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_Response)(nil),
		(*Message_Call)(nil),
		(*Message_Transcription)(nil),
		(*Message_Notification)(nil),
		(*Message_Popup)(nil),
		(*Message_Error)(nil),
		(*Message_Hello)(nil),
	}
	file_stillbox_proto_msgTypes[1].OneofWrappers = []any{
		(*CommandResponse_TgInfo)(nil),
	}
	file_stillbox_proto_msgTypes[2].OneofWrappers = []any{}
	file_stillbox_proto_msgTypes[8].OneofWrappers = []any{
		(*Command_LiveCommand)(nil),
		(*Command_SearchCommand)(nil),
		(*Command_TgCommand)(nil),
		(*Command_RegisterCommand)(nil),
		(*Command_SetTranscript)(nil),
	}
	file_stillbox_proto_msgTypes[9].OneofWrappers = []any{}
	file_stillbox_proto_msgTypes[10].OneofWrappers = []any{}
	file_stillbox_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stillbox_proto_rawDesc), len(file_stillbox_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stillbox_proto_goTypes,
		DependencyIndexes: file_stillbox_proto_depIdxs,
		EnumInfos:         file_stillbox_proto_enumTypes,
		MessageInfos:      file_stillbox_proto_msgTypes,
	}.Build()
	File_stillbox_proto = out.File
	file_stillbox_proto_goTypes = nil
	file_stillbox_proto_depIdxs = nil
}
